graphql/graphql-js

- src/__fixtures__/schema-kitchen-sink.graphql
- src/language/__tests__/schema-parser-test.js
- src/language/__tests__/schema-printer-test.js
- src/language/ast.js
- src/language/parser.js
- src/language/printer.js
- src/type/__tests__/directive-test.js
- src/type/directives.js
- src/utilities/__tests__/buildASTSchema-test.js
- src/utilities/__tests__/extendSchema-test.js
- src/utilities/__tests__/schemaPrinter-test.js
- src/utilities/buildASTSchema.js
- src/utilities/schemaPrinter.js
- src/validation/__tests__/UniqueDirectivesPerLocation-test.js
- src/validation/rules/UniqueDirectivesPerLocation.js
Code is based on #1541 but without introspection changes
and without breaking change detection
> Added partial support for repeatable directives

- src/utilities/__tests__/buildClientSchema-test.js
- src/utilities/buildClientSchema.js
Prevents situations like #1970
> buildClientSchema: add dev check for invalid introspection argument

- src/error/__tests__/GraphQLError-test.js
- src/language/__tests__/lexer-test.js
- src/language/__tests__/parser-test.js
- src/language/__tests__/printLocation-test.js
- src/language/printLocation.js
- src/utilities/__tests__/stripIgnoredCharacters-test.js
Context: https://github.com/graphql/graphql-js/pull/1786
> Print minified location

- src/utilities/__tests__/buildClientSchema-test.js
Context: https://github.com/graphql/graphql-js/issues/2005
> buildClientSchema: add test for missing standard scalar

- src/jsutils/nodejsCustomInspectSymbol.js
> Defensively verify that Symbol.for is available

- src/subscription/__tests__/subscribe-test.js
- src/subscription/subscribe.js
Currently, errors in `createSourceEventStream` from `buildExecutionContext` will be returned in an `ExecutionResult`, while all other GraphQL errors will be thrown. This is inconsistent with the handling in `subscribe`, and makes it harder to build error handling logic, as there are then two ways to handle the same class of errors.
This makes the error handling consistent and updates the documentation to describe the new logic.
This is technically breaking, but is unlikely to cause problems for any properly-written code, as full error handling logic required handling resolved `ExecutionResult` objects with `errors` anyway.
> Make error handling consistent in createSourceEventStream

- src/execution/execute.js
- src/execution/values.js
- src/jsutils/defineToStringTag.js
- src/language/lexer.js
- src/type/definition.js
- src/utilities/TypeInfo.js
- src/utilities/findBreakingChanges.js
- src/validation/ValidationContext.js
- src/validation/rules/OverlappingFieldsCanBeMerged.js
See: https://flow.org/en/docs/types/utilities/#toc-existential-type
> Flow: Remove some of the 'existential type' usages

- src/execution/__tests__/variables-test.js
- src/execution/execute.js
- src/execution/values.js
- src/index.js
- src/jsutils/Path.js
- src/jsutils/printPathArray.js
- src/utilities/__tests__/coerceInputValue-test.js
- src/utilities/coerceInputValue.js
- src/utilities/coerceValue.js
- src/utilities/index.js
- src/utilities/isValidJSValue.js
> Limits errors in getVariableValues()

- src/type/definition.js
> Convert type definitions subtypes to be exact

- src/type/__tests__/definition-test.js
- src/type/definition.js
> definition: replace object spread with explicit assignments

- src/type/__tests__/predicate-test.js
- src/type/definition.js
- src/type/introspection.js
> definitions: make constructed fields non-optional

- src/jsutils/ObjMap.js
- src/jsutils/__tests__/toObjMap-test.js
- src/jsutils/toObjMap.js
- src/type/__tests__/definition-test.js
- src/type/__tests__/directive-test.js
- src/type/__tests__/enumType-test.js
- src/type/__tests__/extensions-test.js
- src/type/__tests__/predicate-test.js
- src/type/definition.js
- src/type/directives.js
- src/type/introspection.js
- src/type/schema.js
- src/utilities/__tests__/buildClientSchema-test.js
> Add 'extensions' to all Type System objects

- .babelrc.js
> Switch all 'for..of' loops to assume they iterating only arrays

- src/validation/ValidationContext.js
- src/validation/__tests__/validation-test.js
- src/validation/validate.js
**TL;DR:** This PR adds an "onError" argument to the `validate` function that allows for custom error handling when performing validation. A user can use this in many ways -- for instance, they can use this callback to bail early, and prevent performing potentially expensive validation operations hundreds or thousands of times in environments where detailed error messages are less important.
We _should_ fix the root cause of the slowness that I describe below, however -- it's risky to have a utility like this enabled in production, given that it gets slower and slower the more types you have and the more errors you have in your query.
Read on for the story of why I decided to implement this. 😀
----
At Airbnb, we have a GraphQL server that acts as a gateway to many other GraphQL servers -- …
> [validation] Add "onError" option to allow for custom error handling behavior when performing validation

- src/execution/execute.js
- src/jsutils/suggestionList.js
- src/polyfills/find.js
- src/polyfills/flatMap.js
- src/validation/rules/OverlappingFieldsCanBeMerged.js
Since #2099 makes it zero-cost to use 'for..of' it's better to improve
code readability and consistency
> Convert more cycles to 'for..of'

- src/error/formatError.js
- tstypes/error/GraphQLError.d.ts
- tstypes/error/formatError.d.ts
- tstypes/error/index.d.ts
- tstypes/error/locatedError.d.ts
- tstypes/error/printError.d.ts
One remaining diff is that in TS, we define `formatError` as
```ts
export interface GraphQLFormattedError<
TExtensions extends Record<string, any> = Record<string, any>
> {
readonly message: string;
readonly locations?: ReadonlyArray<SourceLocation>;
readonly path?: ReadonlyArray<string | number>;
readonly extensions?: TExtensions;
}
``` 
whereas in flow, we define it like
```
export type GraphQLFormattedError = {|
+message: string,
+locations: $ReadOnlyArray<SourceLocation> | void,
+path: $ReadOnlyArray<string | number> | void,
+extensions?: { [key: string]: mixed, ... },
|};
```
(comments stripped)
Don't have much flow expereince, but playing in the [playground](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcxCBPHDMAcXwEMcALARQBkAxAgW1sMIwBMAovnwEAPABVBWPgDsAzgEs4CgFxgA3mADaAawy …
> Sync tstypes/errors with flow

- tstypes/execution/execute.d.ts
- tstypes/execution/index.d.ts
- tstypes/execution/values.d.ts
- tstypes/jsutils/Path.d.ts
Specifically:
Create `tstypes/jsutils/Path.d.ts` and pull some utility functions out to there (as is done in the implementation)
Add typeResolver options
> Sync execution TS definitions with Flow.

- tstypes/index.d.ts
- tstypes/jsutils/Path.d.ts
- tstypes/type/definition.d.ts
- tstypes/type/directives.d.ts
- tstypes/type/index.d.ts
- tstypes/type/introspection.d.ts
- tstypes/type/scalars.d.ts
- tstypes/type/schema.d.ts
- tstypes/type/validate.d.ts
Specifically:
Add `extensions` field in lots of places
Reorder fields
Both this and #2106 add Path.d.ts, but they're the same. If theres a merge conflict, just pick one.
> Sync type TS definitions with Flow

- tstypes/utilities/TypeInfo.d.ts
- tstypes/utilities/buildASTSchema.d.ts
- tstypes/utilities/coerceInputValue.d.ts
- tstypes/utilities/coerceValue.d.ts
- tstypes/utilities/extendSchema.d.ts
- tstypes/utilities/findBreakingChanges.d.ts
- tstypes/utilities/findDeprecatedUsages.d.ts
- tstypes/utilities/getOperationRootType.d.ts
- tstypes/utilities/index.d.ts
- tstypes/utilities/separateOperations.d.ts
- tstypes/utilities/stripIgnoredCharacters.d.ts
- tstypes/utilities/typeComparators.d.ts
- tstypes/utilities/typeFromAST.d.ts
- tstypes/utilities/valueFromAST.d.ts
Removed a ton from `tstypes/utilities/findBreakingChanges.d.ts`.
> Sync utilities TS definitions with flow

- tstypes/utilities/coerceInputValue.d.ts
- tstypes/validation/validate.d.ts
Mistakenly imported some items using incorrect relative imports in the pervious TS merger. This fixes that.
> Fix relative imports

- src/polyfills/flatMap.js
- Fix for flow-bin 0.96, which complains about flatMap not existing.
When on flow-bin 0.96, we get flow complaints with the flatMap polyfill:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/polyfills/flatMap.js.flow:12:30
Cannot get Array.prototype.flatMap because property flatMap is missing in Array [1].
node_modules/graphql/polyfills/flatMap.js.flow
9│ // $FlowFixMe
10│ const flatMap = Array.prototype.flatMap
11│   ? function(list, fn) {
12│       return Array.prototype.flatMap.call(list, fn);
13│     }
14│   : function(list, fn) {
15│       let result = [];
/private/tmp/flow/flowlib_3d33be40/core.js
[1] 242│ declare class Array<T> extends $ReadOnlyArray<T> {
```
I believe line 10, the first $FlowFixMe there does the exact same thing as well. …
> fix: added FlowFixMe on Array.prototype.flatMap

- tstypes/language/visitor.d.ts
Otherwise, TS will reposrt errors when a visit function only conditionally returns BREAK (not all paths return a value error)
> tstypes: Use `any` as BREAK type.

- src/polyfills/flatMap.js
> Flow: fix errors in 'flatMap.js' on old Flow versions

- src/utilities/__tests__/findBreakingChanges-test.js
- src/utilities/findBreakingChanges.js
> findDangerousChanges: sort fields inside 'defaultValue'

- src/language/__tests__/lexer-test.js
- src/language/__tests__/printLocation-test.js
- src/language/printLocation.js
Simplifies tests and terminal output
> printLocation: Remove trailing whitespace from empty lines

- src/execution/__tests__/abstract-test.js
- src/execution/__tests__/lists-test.js
- src/execution/__tests__/variables-test.js
- src/execution/execute.js
- src/subscription/__tests__/subscribe-test.js
- src/type/__tests__/enumType-test.js
- src/utilities/__tests__/coerceInputValue-test.js
- src/utilities/__tests__/findDeprecatedUsages-test.js
- src/utilities/coerceInputValue.js
- src/utilities/findDeprecatedUsages.js
> Unify rest of error messages

- src/validation/ValidationContext.js
The onError argument was probably meant to be optional,
just like in ASTValidationContext and ValidationContext.
> Make onError optional in SDLValidationContext

- src/language/__tests__/lexer-test.js
- src/language/lexer.js
Implements and adds the tests described by https://github.com/graphql/graphql-spec/pull/601
> RFC: Number lexer lookahead restriction

- src/type/definition.js
- src/type/schema.js
- src/utilities/extendSchema.js
We should have consistent behaviour for all properties returned by
`toConfig` and since `extensions` is optional that mean
`extensionASTNodes` should also be optional
> toConfig: allows 'extensionASTNodes' to be undefined

- src/type/__tests__/enumType-test.js
- src/type/__tests__/scalars-test.js
- src/type/__tests__/serialization-test.js
- src/type/scalars.js
- src/validation/__tests__/ValuesOfCorrectType-test.js
> Update built-in scalar's parseLiteral method to throw TypeError

- src/execution/__tests__/variables-test.js
- src/execution/values.js
> Fixes variable values of non-null type with default value

- src/validation/__tests__/KnownArgumentNames-test.js
Tests that arguments passed to an argument-less directive are properly reported as an error.
The test suite did not catch that this did not work properly in the Python port, so I added these tests.
> Add two more tests to KnownArgumentNames validation rule

- tstypes/type/directives.d.ts
- tstypes/type/scalars.d.ts
> tstypes: fix typings for 'isSpecifiedDirective'/'isSpecifiedScalarType'

- src/utilities/__tests__/findBreakingChanges-test.js
- src/utilities/findBreakingChanges.js
> findBreakingChanges: better message for removing standard scalar

- src/type/__tests__/predicate-test.js
- src/type/directives.js
- src/type/introspection.js
- src/type/scalars.js
- tstypes/type/directives.d.ts
- tstypes/type/introspection.d.ts
- tstypes/type/scalars.d.ts
Fixes #2153
Previous disscussion: https://github.com/graphql/graphql-js/pull/1837#issuecomment-488250420
> Change 'isSpecified*' & 'isIntrospectionType' accept only correct types

- src/execution/values.d.ts
This fixes the typescript definition to match flow and prevent errors when passing a read-only array.
> Fix typescript definition for getVariableValues

- src/__fixtures__/kitchen-sink.graphql
- src/error/GraphQLError.js
- src/language/__tests__/printer-test.js
- src/validation/__tests__/ValuesOfCorrectType-test.js
https://developer.mozilla.org/en-US/docs/Glossary/Falsy
> Sometimes written falsey, although in English usually turning
> a word into > an adjective with a -y, any final e is dropped
> (noise => noisy, ice => icy, shine => shiny)
> grammar: 'falsey' => 'falsy'

- docs/Guides-ConstructingTypes.md
- docs/Tutorial-Authentication.md
- docs/Tutorial-BasicTypes.md
- docs/Tutorial-ExpressGraphQL.md
- docs/Tutorial-ObjectTypes.md
- docs/Tutorial-PassingArguments.md
There were lots of `console.logs` that were coded like synchronous code, but express' `listen` function provides callback and is best practice to provide the callback for post-listen operations.
It was  already correct in this documentation: https://github.com/graphql/graphql-js/blob/master/docs/Tutorial-Mutations.md
> docs: follow express' best practice

- src/utilities/__tests__/buildClientSchema-test.js
Instead of repeating basically the same enum value five times, i changed
the test to be less repetitive but have more variance in test scenarios.
> Vary the test case for building client schemas with enum

- src/type/introspection.d.ts
Addresses https://github.com/graphql/graphql-js/issues/2260
> TS: `introspectionTypes` should be array of `GraphQLNamedType`

- .travis.yml
Update TravisCi to run the full `test:ci` commands on Node 12, which was promoted to LTS on 2019-10-21 ([source](https://nodejs.org/en/about/releases/)).
> Update TravisCi to run full CI suite on Node 12

- .github/CONTRIBUTING.md
The `npm run watch` command was removed in commit c3dd670, making this section no longer valid.
> Remove outdated "Live Feedback" section from CONTRIBUTING.modified

- src/utilities/__tests__/coerceInputValue-test.js
- src/utilities/coerceInputValue.js
Remove a duplicate colon in coercion error messages with path.
> Remove duplicate colon in coercion error message

- src/type/__tests__/introspection-test.js
- src/validation/rules/ProvidedRequiredArguments.js
- src/validation/rules/ScalarLeafs.js
- src/validation/rules/UniqueArgumentNames.js
- src/validation/rules/UniqueDirectiveNames.js
In #2519, the internal functions for validation error messages have been removed, but some have been forgotten.
> Remove forgotten internal error message functions (#2159)

- src/utilities/extendSchema.js
`directives` are always array but it can be empty:
https://github.com/graphql/graphql-js/blob/2d583c7f5e60853266545628fa71faa7351b1f71/src/type/schema.js#L131
So ATM this statement doesn't check anything.
> extendSchema: remove dead check on number of directives

- src/utilities/__tests__/buildASTSchema-test.js
- src/utilities/__tests__/extendSchema-test.js
- src/utilities/buildASTSchema.js
- src/utilities/extendSchema.js
> buildSchema/extendSchema: add support for extensions

- src/type/validate.js
In both 'GraphQLFieldConfig' and 'GraphQLDirectiveConfig' arguments are
specified as map and can't duplicate by definition.
> validateSchema: remove validation arguments uniqueness

- src/execution/__tests__/executor-test.js
- src/type/__tests__/enumType-test.js
- src/type/definition.js
- src/utilities/__tests__/astFromValue-test.js
- src/utilities/__tests__/coerceInputValue-test.js
- src/utilities/coerceInputValue.js
- src/utilities/valueFromAST.js
- src/validation/__tests__/ValuesOfCorrectType-test.js
- src/validation/rules/ValuesOfCorrectType.js
> enum: 'parseLiteral/parseValue/serialize' now throw on invalid values

- src/validation/rules/OverlappingFieldsCanBeMerged.js
This caching is unneeded since fragment names are always collected into
map and does contains duplicates, see:
https://github.com/graphql/graphql-js/blob/6c377ac482e61b8179bb7dd0e44fa0ede8e1a91c/src/validation/rules/OverlappingFieldsCanBeMerged.js#L711
> OverlappingFieldsCanBeMerged: remove excessive caching

- cspell.json
- package.json
- src/execution/execute.js
- src/jsutils/__tests__/isCollection-test.js
- src/jsutils/isCollection.js
- src/polyfills/arrayFrom.js
- src/polyfills/symbols.js
- src/subscription/mapAsyncIterator.js
- src/subscription/subscribe.js
- src/utilities/astFromValue.js
- src/utilities/coerceInputValue.js
- yarn.lock
We used only couple functions from 'iterall' and it's the only
dependency we have at the moment.
Having no dependencies significantly simplify ESM builds and Deno
support in future
Partially resolves: #2277
Bonus: All supported Node versions already natively support Array.from
so it should improve perfomance
> Remove 'iterall' as dependency. 'graphql' becomes zero dependency lib 🎉

- .eslintrc.yml
- package.json
- resources/eslint-rules/no-dir-import.js
- src/index.d.ts
- src/index.js
- src/language/__tests__/parser-benchmark.js
- src/language/__tests__/parser-test.js
- src/language/__tests__/printer-test.js
- src/language/__tests__/schema-parser-test.js
- src/language/__tests__/schema-printer-test.js
- src/language/__tests__/visitor-test.js
- src/utilities/__tests__/buildASTSchema-benchmark.js
- src/utilities/__tests__/buildClientSchema-benchmark.js
- src/utilities/__tests__/introspectionFromSchema-benchmark.js
- src/utilities/__tests__/stripIgnoredCharacters-test.js
- src/validation/__tests__/validateGQL-benchmark.js
- src/validation/__tests__/validateInvalidGQL-benchmark.js
- src/validation/__tests__/validateSDL-benchmark.js
> ESLint: Forbid importing directories

- .babelrc
- resources/add-extension-to-import-paths.js
> build: mjs files import other files using full paths with extensions

- src/type/__tests__/serialization-test.js
- src/type/scalars.js
It is good to have opportunity to pass objects which have valueOf() method in resolvers of Int and Float types.
For example, I have such objects as "Money", "Price" and so on in my app, and they have valueOf() method which return value. Now I need to call valueOf() method in every resolver of such field or write custom scalar or directive.
I think changes I did  are implied in native type behavior of Int, Float and Boolean fields.
> Change serialization for Int, Float and Boolean to work with objects

- src/jsutils/__tests__/suggestionList-test.js
- src/jsutils/suggestionList.js
- src/validation/__tests__/FieldsOnCorrectType-test.js
- src/validation/__tests__/KnownTypeNames-test.js
- src/validation/__tests__/ValuesOfCorrectType-test.js
> suggestionList: lexicographically sort options with the same lexical distance

- src/index.js
- src/validation/index.js
- tstypes/index.d.ts
- tstypes/validation/index.d.ts
Backport of #2399 on `14.x.x` branch
> validation: Add missing rule exports

- src/index.d.ts
- src/index.js
- src/validation/__tests__/LoneSchemaDefinitionRule-test.js
- src/validation/__tests__/UniqueDirectiveNamesRule-test.js
- src/validation/__tests__/UniqueEnumValueNamesRule-test.js
- src/validation/__tests__/UniqueOperationTypesRule-test.js
- src/validation/__tests__/UniqueTypeNamesRule-test.js
- src/validation/index.d.ts
- src/validation/index.js
- src/validation/rules/LoneSchemaDefinitionRule.d.ts
- src/validation/rules/LoneSchemaDefinitionRule.js
- src/validation/rules/UniqueDirectiveNamesRule.d.ts
- src/validation/rules/UniqueDirectiveNamesRule.js
- src/validation/rules/UniqueEnumValueNamesRule.d.ts
- src/validation/rules/UniqueEnumValueNamesRule.js
- src/validation/rules/UniqueOperationTypesRule.d.ts
- src/validation/rules/UniqueOperationTypesRule.js
- src/validation/rules/UniqueTypeNamesRule.d.ts
- src/validation/rules/UniqueTypeNamesRule.js
- src/validation/specifiedRules.js
Big thanks to @trevor-scheer for reporting it here:
https://github.com/graphql/graphql-js/pull/2402/files#r371545963
> Fixing double 'Rule' suffix that was accidentally introduced in #2402

- src/type/__tests__/schema-test.js
- src/type/schema.js
It introduces small perfomance penalty but simplify writing code around
GraphQLSchema a lot. Also good long term solution would be to have
separate dev and production (without `devAssert` checks) builds.
> schema: Always validate basic config structure

- src/type/__tests__/schema-test.js
- src/utilities/__tests__/extendSchema-test.js
- src/utilities/__tests__/schemaPrinter-test.js
- src/utilities/extendSchema.js
- src/utilities/schemaPrinter.js
Fixes #2362
It's a step toward having reversable `buildSchema`:
```
sdl === printSchema(buildSchema(sdl))
```
At the same time if you need fully predictable SDL output (e.g. to diff
schemas) you can achieve this using `llexicographicSortSchema`:
```
printSchema(lexicographicSortSchema(schema))
```
But if some reason you can't use `lexicographicSortSchema` please open
an issue and describe your use case in more details.
> schemaPrinter: preserve order of types

- src/validation/rules/ExecutableDefinitions.d.ts
- src/validation/rules/ExecutableDefinitions.js
- src/validation/rules/LoneSchemaDefinition.d.ts
- src/validation/rules/LoneSchemaDefinition.js
- src/validation/rules/PossibleTypeExtensions.d.ts
- src/validation/rules/PossibleTypeExtensions.js
- src/validation/rules/UniqueDirectiveNames.d.ts
- src/validation/rules/UniqueDirectiveNames.js
- src/validation/rules/UniqueEnumValueNames.d.ts
- src/validation/rules/UniqueEnumValueNames.js
- src/validation/rules/UniqueFieldDefinitionNames.d.ts
- src/validation/rules/UniqueFieldDefinitionNames.js
- src/validation/rules/UniqueOperationTypes.d.ts
- src/validation/rules/UniqueOperationTypes.js
- src/validation/rules/UniqueTypeNames.d.ts
- src/validation/rules/UniqueTypeNames.js
It's recommended to update to 14.6.0 and start using correct exports
added in #2400 but if you stuck on the earlier version you could use these
exports as a temporary workaround.
Note: these exports are deprecated and will be removed in v16
> validation: Export rules missing in <14.6.0 using legacy names

- src/type/__tests__/introspection-test.js
- src/type/introspection.js
Actually a bug fix but since it's affect introspection can be a small breaking change.
> introspection: expose fields/values with empty deprecationReason

- src/type/__tests__/introspection-test.js
- src/type/introspection.js
- src/utilities/__tests__/buildClientSchema-test.js
- src/utilities/__tests__/getIntrospectionQuery-test.js
- src/utilities/__tests__/schemaPrinter-test.js
- src/utilities/buildClientSchema.js
- src/utilities/getIntrospectionQuery.d.ts
- src/utilities/getIntrospectionQuery.js
- src/utilities/introspectionFromSchema.js
Code is taken from #1541 with additional tests for `getIntrospectionQuery`
> introspection: Add support for repeatable directives

- src/__fixtures__/schema-kitchen-sink.graphql
- src/language/__tests__/schema-parser-test.js
- src/language/__tests__/schema-printer-test.js
- src/language/ast.d.ts
- src/language/ast.js
- src/language/parser.js
- src/language/printer.js
- src/language/visitor.d.ts
- src/language/visitor.js
- src/type/__tests__/introspection-test.js
- src/type/__tests__/schema-test.js
- src/type/introspection.js
- src/type/schema.d.ts
- src/type/schema.js
- src/utilities/__tests__/buildASTSchema-test.js
- src/utilities/__tests__/buildClientSchema-test.js
- src/utilities/__tests__/getIntrospectionQuery-test.js
- src/utilities/__tests__/schemaPrinter-test.js
- src/utilities/buildClientSchema.js
- src/utilities/extendSchema.js
- src/utilities/getIntrospectionQuery.js
- src/utilities/introspectionFromSchema.js
- src/utilities/schemaPrinter.js
Implements https://github.com/graphql/graphql-spec/pull/466
> Add support for adding description to schema

- src/error/locatedError.d.ts
- src/error/locatedError.js
- src/type/validate.js
- src/utilities/assertValidName.d.ts
- src/utilities/assertValidName.js
If you want to bind error to node please use `locatedError`:
```
const error = isValidNameError(name);
if (error) {
someFunction(locatedError(error, node));
}
```
> isValidNameError: Remove node argument

- resources/benchmark-fork.js
> Benchmark: set 'NODE_ENV=production' before running the benchmarks

- src/execution/__tests__/executor-test.js
The assertion for testing the asyncResult was wrong and this also concealed that the async result was not properly awaited.
> Fix the test for an async unmet isTypeOf check

- src/execution/execute.js
- src/jsutils/isInvalid.js
- src/jsutils/isNullish.js
- src/utilities/__tests__/astFromValue-test.js
- src/utilities/__tests__/valueFromASTUntyped-test.js
- src/utilities/astFromValue.js
- src/utilities/valueFromAST.js
- src/utilities/valueFromASTUntyped.js
- src/validation/rules/ValuesOfCorrectTypeRule.js
We shouldn't have special casing for NaN since it masks programmer mistakes.
Also it makes it imposible to implement custom scalar that can encode NaN.
> NaN values should be checked inside scalar's `serialize` method

- src/utilities/__tests__/TypeInfo-test.js
test name has been duplicated and not adapted
> TypeInfo-test: use proper test name

- src/validation/__tests__/UniqueDirectivesPerLocationRule-test.js
- src/validation/rules/UniqueDirectivesPerLocationRule.js
> UniqueDirectivesPerLocation: check for directive uniqueness in extensions

- src/utilities/coerceInputValue.js
- src/utilities/valueFromAST.js
- src/validation/rules/ValuesOfCorrectTypeRule.js
Adapt comments for code which is now also used for enums, not only scalars (change in 15.0.0-rc.1).
> Adapt some comments after serialization of enums changed

- .eslintrc.yml
- package.json
AFAIK, the are no way to specify `rulesdir` inside '.eslintrc' config
because of that IDE can't run ESLint with default CLI options
> ESLint: move custom rule into CLI argument

- src/README.md
The tests failed locally because of a mistype :)
> Docs: fix spelling error in src/README.md

- src/type/__tests__/schema-test.js
- src/type/schema.js
Small fix to show an error message when one provided type has no name and to avoid error messages like "multiple types named undefined" when multiple provided types have no name.
> schema: fix error message when provided type has no name

- src/type/definition.d.ts
Was added in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32694
The motivation for removal #2481
> TS(definition): remove TS-specific TArgs

- src/execution/execute.d.ts
- src/graphql.d.ts
- src/subscription/subscribe.d.ts
Reverts https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26763
Since we can't gurantee that response match types it was basically
glorified type cast.
> TS: remove TS-specific TData from ExecutionResult

- src/execution/execute.d.ts
It's internal function so not a breaking change
> TS: remove TS-specific TSource argument for resolveFieldValueOrError

- src/type/validate.js
This is to fix #2504 regression that throws `TypeError` not normal `GraphQLError` when running `validateTypeImplementsInterface` if `astNode` is not provided to `GraphQLType`
> Fix #2504 access field astNode's type by optional chaining

- docs/APIReference-TypeSystem.md
- src/type/__tests__/definition-test.js
- src/type/__tests__/introspection-test.js
- src/type/definition.d.ts
- src/type/definition.js
- src/type/directives.d.ts
- src/type/directives.js
- src/type/introspection.js
- src/utilities/__tests__/buildASTSchema-test.js
- src/utilities/__tests__/buildClientSchema-test.js
- src/utilities/__tests__/extendSchema-test.js
- src/utilities/__tests__/findBreakingChanges-test.js
- src/utilities/__tests__/getIntrospectionQuery-test.js
- src/utilities/__tests__/schemaPrinter-test.js
- src/utilities/buildASTSchema.js
- src/utilities/buildClientSchema.js
- src/utilities/extendSchema.js
- src/utilities/getIntrospectionQuery.d.ts
- src/utilities/getIntrospectionQuery.js
- src/utilities/printSchema.js
This in an implementation for a spec proposal:
* Spec proposal: [[RFC] Custom Scalar Specification URIs](https://github.com/graphql/graphql-spec/pull/649)
* Original issue: [[RFC] Custom Scalar Specification URIs](https://github.com/graphql/graphql-spec/issues/635)
```javascript
const { graphql, buildSchema } = require("graphql");
const schema = buildSchema(`
"""
A UUID
"""
scalar UUID @specified(by: "https://tools.ietf.org/html/rfc4122")
type Query {
someUUID: UUID
}
`);
const root = {
someUUID: () => {
return "750fce86-fc2f-4b25-a7df-fd0941d3fa08";
}
};
const query = `
{
__type(name: "UUID") {
kind
name
description
specifiedBy
}
}`;
graphql(schema, query, root).then(response => {
console.log(JSON.stringify(response, null, 4));
});
```
```
{
"data": {
"__type": {
"kind": "SCALAR", …
```
> Add `@specifiedBy` directive

- src/index.d.ts
- src/index.js
- src/language/index.js
Reported here: https://github.com/graphql/graphql-js/pull/2233#issuecomment-621312122
> Exported `Token` and `Location` as ES6 classes

- src/utilities/buildASTSchema.js
Empty schema constructed as `new GraphQLSchema({ directives: [] })`
still contains introspection types
> buildASTSchema: pass empty schema as literal

- src/language/lexer.d.ts
- src/type/definition.d.ts
- src/type/schema.d.ts
- src/utilities/getIntrospectionQuery.d.ts
- src/validation/rules/KnownTypeNamesRule.d.ts
> TS: sync TS typings with Flow typings

- src/__testUtils__/__tests__/genFuzzStrings-test.js
- src/__tests__/starWarsData.js
- src/__tests__/starWarsIntrospection-test.js
- src/__tests__/starWarsValidation-test.js
- src/execution/__tests__/abstract-promise-test.js
- src/execution/__tests__/abstract-test.js
- src/execution/__tests__/directives-test.js
- src/execution/__tests__/executor-test.js
- src/execution/__tests__/lists-test.js
- src/execution/__tests__/nonnull-test.js
- src/execution/__tests__/resolve-test.js
- src/execution/__tests__/schema-test.js
- src/execution/__tests__/union-interface-test.js
> tests: Improve type coverage

- src/index.d.ts
- src/index.js
- src/validation/__tests__/NoSchemaIntrospectionCustomRule-test.js
- src/validation/index.d.ts
- src/validation/index.js
- src/validation/rules/custom/NoSchemaIntrospectionCustomRule.d.ts
- src/validation/rules/custom/NoSchemaIntrospectionCustomRule.js
> Add NoSchemaIntrospectionCustomRule

- src/execution/__tests__/executor-test.js
- src/execution/execute.js
- src/jsutils/Path.d.ts
- src/jsutils/Path.js
- src/subscription/subscribe.js
- src/utilities/coerceInputValue.js
Imagine you have the schema:
```graphql
type A {
int: Int
union: C
}
type B {
int: Int
union: C
}
union C = A | B
type Query {
root: C
}
```
You could write the query:
```graphql
{
root {
... on A {
union {
... on A {
alias1: union { # EXAMPLE1
int
}
alias2: union {
int
}
}
... on B {
alias1: union {
int
}
alias2: union {
int
}
}
}
}
... on B {
union {
... on A {
alias1: union { # EXAMPLE2
int
}
alias2: union {
int
}
}
... on B {
alias1: union {
int
}
alias2: union {
int
}
}
}
}
}
}
```
In the resolver for `A.union`, in `resolveInfo` (the fourth argument to resolve) you would not be able to tell if you are in position `EXAMPLE1` or `EXAMPLE2` without looking into the `loc` data in `fieldNodes`. This makes it challenging to write certain classes of lookahead engine.
Namely in both EXAMPLE1 …
> Add parentType to path to avoid path ambiguity

- README.md
- docs/APIReference-Language.md
Noticed a small grammar mistake. I went to fix it and then noticed some more so I'm including them also. Cleaner language hopefully makes for easier understanding.
> Docs: some language cleanup in readme and API reference

- docs/APIReference-Language.md
- src/language/source.d.ts
- src/language/source.js
- src/language/visitor.d.ts
- src/language/visitor.js
I was going to sync the comments for Source but I noticed the docs were way behind, so I just updated both.
> Sync JSDoc comments with docs changes

- src/execution/execute.js
The `__type`  field should also be mentioned in the jsdoc comment.
> Make documentation for 'getFieldDef' more accurate

- docs/APIReference-ExpressGraphQL.md
- docs/Guides-ConstructingTypes.md
- docs/Tutorial-Authentication.md
- docs/Tutorial-BasicTypes.md
- docs/Tutorial-ExpressGraphQL.md
- docs/Tutorial-Mutations.md
- docs/Tutorial-ObjectTypes.md
- docs/Tutorial-PassingArguments.md
- graphql-js tutorial has an error in [running-an-express-graphql-server](https://graphql.org/graphql-js/running-an-express-graphql-server/graphql-express) try to import modules.
I just followed the document at graphql-js tutorials.
But there is problem when I import graphqlHTTP from 'express-grapqhl'.
(The squared black blank is my user name.)
Because they updated express-grapqhl modules and updated official `README.md` 27 days ago. [express-graphql history](https://github.com/graphql/express-graphql/commit/0f74f05cc2d09d20aa3822472132f9f4701df8c7) (see below image)
So I changed require statement in graphql-js tutorials.
`var graphqlHTTP = require('express-graphql')`
to
`var { graphqlHTTP } = require('express-graphql')`
And it works!
> docs: Changed how to import graphqlHTTP in graphql-express modules

- src/type/__tests__/definition-test.js
- src/type/definition.js
> GraphQLScalarType: default 'parseLiteral' should handle variables

- docs/APIReference-Utilities.md
`introspectionQuery` has been deleted and replaced with `getIntrospectionQuery`
Fixes https://github.com/graphql/graphql-js/issues/2717
See also https://github.com/graphql/graphql-js/issues/2503
> introspectionQuery -> getIntrospectionQuery

- src/error/locatedError.d.ts
- src/error/locatedError.js
- src/execution/execute.d.ts
- src/execution/execute.js
- src/subscription/subscribe.js
Also move handling for error that not inherit from Error to `locatedError`
> execute/subscribe: simplify to improve debugging experience

- src/language/parser.js
> parser: Export `Parser` class as unstable API

- src/execution/__tests__/lists-test.js
- src/execution/execute.js
- src/jsutils/isAsyncIterable.js
- src/subscription/subscribe.js
Returning AsyncIterables in resolver methods is useful when `@stream` is supported and can be added without any breaking changes. This is split out from https://github.com/graphql/graphql-js/pull/2319
> Support returning async iterables from resolver functions

- src/utilities/getIntrospectionQuery.js
This makes the flow definition of `specifiedByUrl` identical to the TS definition in https://github.com/graphql/graphql-js/blob/master/src/utilities/getIntrospectionQuery.d.ts#L65
This also will make the next `graphql-js` release no longer have a breaking flow change compared to v15.0.0: I discovered this flow issue as I was upgrading from v15.0 to v15.3.
> Make specifiedByUrl in IntrospectionScalarType's flow type optional

- src/polyfills/symbols.js
Added check for specific symbols in polyfills/symbols because in nodejs 8 Symbol exists, but Symbol.asyncIterator is not.
This cause an error 
`
message: "Subscription field must return Async Iterable. Received: { next: [function next], return: [function return], throw: [function throw], @@asyncIterator: [function] }."
`
just because `isAsyncIterable` returns false
Checking for specific symbols in Symbol will fix it
> Added check for specific symbols in polyfills/symbols

- src/language/__tests__/printer-test.js
- src/language/printer.js
Hi! We are using the `print` function to pretty-print our queries. It works quite well, but there is one thing that I think could be improved upon, and that's the rendering of arguments.
This first image illustrates our problem. The main query takes a lot of parameters, and when formatting the query, all of these are put on the same line.
This next image illustrates the result of the changes made in this PR. All parameters are put on individual lines, and object values are also "prettified".
1. Should a parameter be kept on one line if there is only the one?
2. Should perhaps array values also be broken over multiple lines, or is the following okay?
> Make print() break arguments over multiple lines

- docs/APIReference-Utilities.md
This method is not named `parseSchemaIntoAST` anymore, but is instead called `parse`.
I'm not sure how the process is, but the error can also be found here https://github.com/graphql/graphql.github.io/blob/9a6e78630448d9235664209a0026c7a19912ce5e/site/graphql-js/APIReference-Utilities.md
> Update outdated documentation

- resources/benchmark-fork.js
- src/execution/__tests__/list-async-benchmark.js
- src/execution/__tests__/list-asyncIterable-benchmark.js
- src/execution/__tests__/list-sync-benchmark.js
- src/execution/__tests__/lists-test.js
- src/execution/execute.js
Updated to follow the pattern used in https://github.com/leebyron/iterall/issues/24 to avoid a memory leak. This approach does significantly reduce the memory used.
> Testing async iterables for memory leaks

- integrationTests/ts/index.ts
- src/utilities/typedQueryDocumentNode.d.ts
I've written up detailed reasoning in https://github.com/dotansimha/graphql-typed-document-node/pull/38
I didn't remove the "FIXME" comment, as I'm not sure what you would prefer to do with it. Nominal typing wouldn't actually solve anything here, because the variables and responses are plain objects, not nominal types. What's needed is just accurate structural typing. I really don't view this as a hack because:
1. We're not lying about any of the types that exist at runtime
2. The `__apiType` property does accurately document/describe the API behavour
3. The type errors TypeScript would produce if you use these `TypedQueryDocumentNode`s incorrectly matches up with the issues you would see at runtime.
> fix: ensure variance of types matches how values are used

- src/utilities/__tests__/buildClientSchema-test.js
- src/utilities/__tests__/getIntrospectionQuery-test.js
- src/utilities/buildClientSchema.js
- src/utilities/getIntrospectionQuery.d.ts
- src/utilities/getIntrospectionQuery.js
- src/utilities/introspectionFromSchema.js
> introspection: Add missing support for deprecated input values

- src/utilities/__tests__/separateOperations-test.js
- src/utilities/separateOperations.js
> separateOperations: distinguish query and fragment names

- src/error/GraphQLError.js
- src/language/source.js
- src/type/definition.js
- src/type/directives.js
- src/type/schema.js
- src/utilities/TypeInfo.js
- src/validation/ValidationContext.js
As mentioned by @IvanGoncharov in https://github.com/graphql/graphql-js/pull/2828#discussion_r554132661
> fix: type annotation cannot appear on a constructor declaration

- src/language/blockString.js
- src/utilities/coerceInputValue.js
- src/validation/validate.js
As mentioned by @IvanGoncharov in https://github.com/graphql/graphql-js/pull/2828#discussion_r556488760
> fix: no need to mark param optional if default value is given

- src/jsutils/__tests__/naturalCompare-test.js
- src/jsutils/naturalCompare.js
- src/jsutils/suggestionList.js
- src/utilities/findBreakingChanges.js
- src/utilities/lexicographicSortSchema.js
- src/validation/rules/FieldsOnCorrectTypeRule.js
> Replace 'localeCompare' with function independent from locale

- .github/workflows/ci.yml
- README.md
- resources/checkgit.sh
- resources/gitpublish.sh
Updates the CI, scripts and Readme badges to switch branches from `master` to `main`
**Reviewer:** @IvanGoncharov 
Related #2860
> ci: migrate master to main

- src/__tests__/starWarsQuery-test.js
- src/execution/__tests__/executor-test.js
- src/execution/execute.js
- src/graphql.js
- src/subscription/__tests__/subscribe-test.js
- src/subscription/subscribe.js
> Remove support for positional args in graphql/execute/subscribe func

- .github/CONTRIBUTING.md
- README.md
This PR removes the reference to the Facebook CLA, and adds instructions for signing the GraphQL Specification membership agreement via the LF's EasyCLA tool.
Signed-off-by: Brian Warner <brian@bdwarner.com>
> Add EasyCLA instructions, replace FB CLA

- src/language/experimentalOnlineParser/onlineParser.js
This typescript eslint rule﻿[`prefer-regexp-exec`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-regexp-exec.md) is enabled so we should use `exec` over `match`. Cherry-picked from #2828
> refactor: use regexp-exec

- src/language/__tests__/visitor-test.js
- src/language/printer.js
- src/language/visitor.d.ts
- src/language/visitor.js
Visitor in 4th form can always be written as 2nd form.
This is PR part of general effort to simplify `visit` typings before TS
migration.
> visitor: remove 4th form of visitor

- .eslintrc.yml
ATM, minimal supported Node.js version is 12 so we drop this restriction
> ESLint: Allow 'async' functions

- src/execution/execute.d.ts
- src/graphql.d.ts
- src/subscription/subscribe.d.ts
Removal of positional args was done in #2904 but TS typings were not updated.
> Synchronise TS typings for graphql.js/execute.js/subscribe.js

- src/error/GraphQLError.js
- src/jsutils/keyMap.js
- src/jsutils/keyValMap.js
- src/jsutils/promiseForObject.js
- src/language/experimentalOnlineParser/onlineParser.js
- src/validation/ValidationContext.js
- src/validation/rules/OverlappingFieldsCanBeMergedRule.js
Results in measurable performance increase and significantly lower memory
usage in a few benchmarks.
> Replace 'Array.reduce' with 'for of'

- src/utilities/getIntrospectionQuery.d.ts
- fix: match flow types
- feat: use recursive types
> fix: update introspection types

- src/__testUtils__/__tests__/dedent-test.js
- src/__testUtils__/dedent.js
- src/error/__tests__/GraphQLError-test.js
- src/language/__tests__/lexer-test.js
- src/language/__tests__/parser-test.js
- src/language/__tests__/printLocation-test.js
- src/language/__tests__/schema-parser-test.js
- src/language/printer.js
- src/utilities/__tests__/buildASTSchema-test.js
- src/utilities/__tests__/extendSchema-test.js
- src/utilities/__tests__/stripIgnoredCharacters-test.js
- src/utilities/printSchema.js
Remove special behaviour for printing `DocumentNode` that added trailing
new line.
This change allows to tools to add newline only if it required by code
convention or OS convention.
Scripts and CLI tool can return previous behaviour by adding `\n`.
> print/printSchema: remove trailing new line

- src/language/blockString.d.ts
- src/language/directiveLocation.d.ts
- src/language/kinds.d.ts
- src/language/lexer.d.ts
- src/language/source.d.ts
- src/language/tokenKind.d.ts
- src/type/definition.d.ts
- src/type/directives.d.ts
- src/type/introspection.d.ts
- src/type/schema.d.ts
- src/utilities/TypeInfo.d.ts
- src/validation/validate.d.ts
Split PR #2985
- feat: remove unexported type
- feat: exported type should be readonly
- feat: add get Symbol.toStringTag
- feat: add internal annotations
- fix: match type as per flow def
-  feat: add type for [Symbol.toStringTag] getter
- fix: match input type with flow
- fix: match return return type with flow
> fix: discrepancies between Flow and TS types

- src/__testUtils__/__tests__/dedent-test.js
- src/__testUtils__/dedent.js
Split dedentString from dedent
> testUtils: refactor out dedentString from dedent

- docs/APIReference-TypeSystem.md
- src/type/__tests__/definition-test.js
- src/type/__tests__/introspection-test.js
- src/type/definition.d.ts
- src/type/definition.js
- src/type/introspection.js
- src/utilities/__tests__/buildASTSchema-test.js
- src/utilities/__tests__/extendSchema-test.js
- src/utilities/__tests__/getIntrospectionQuery-test.js
- src/utilities/__tests__/printSchema-test.js
- src/utilities/buildClientSchema.js
- src/utilities/extendSchema.js
- src/utilities/getIntrospectionQuery.d.ts
- src/utilities/getIntrospectionQuery.js
- src/utilities/printSchema.js
- I followed as "[[RFC] Custom Scalar Specification URLs](https://github.com/graphql/graphql-spec/pull/649)".
- `@specifiedBy` directive uses "specifiedBy" field on `__Type`. ref: [schema-introspection](https://github.com/graphql/graphql-spec/blob/main/spec/Section%204%20--%20Introspection.md#schema-introspection)
```gql
type __Type {
kind: __TypeKind!
name: String
description: String
...
specifiedBy: String
}
```
- But I didn't fix `IntrospectionOptions` fields because keeping backward compatible.
> Use specifiedBy instead of specifiedByUrl

- src/type/definition.js
- src/type/directives.js
- src/utilities/printSchema.js
Fields and Directives both define arguments according to identical logic. This generalizes that and shares the implementation across both constructions.
> Generalize defineArguments()

- src/language/parser.d.ts
- src/language/parser.js
- src/language/visitor.js
This replaces manual assignment of `loc` on each node in Parser with a `node()` function. This simplifies the parser and also ensures the `loc` field does not appear at all when `noLocation` is provided.
> Improve parser location API

- src/index.d.ts
- src/index.js
- src/type/definition.d.ts
- src/type/definition.js
- src/type/index.d.ts
- src/type/index.js
This introduces type definitions `GraphQLNamedInputType` and `GraphQLNamedOutputType` as the subsets of `GraphQLNamedType`, and adds function overrides for `getNamedType()` such that if an input or output type is provided, one of these refined subset types is returned.
> Refine getNamedType() for Input and Output types

- src/execution/values.js
- src/jsutils/instanceOf.js
- src/jsutils/memoize3.js
- src/jsutils/promiseReduce.js
- src/language/__tests__/predicates-test.js
- src/language/visitor.js
- src/subscription/__tests__/mapAsyncIterator-test.js
- src/subscription/__tests__/simplePubSub.js
- src/subscription/mapAsyncIterator.js
- src/type/validate.js
- src/utilities/lexicographicSortSchema.js
- src/validation/ValidationContext.js
In preparation to TS convertion
> Flow: add missing names to arguments of function types

- flow-typed/core.js
- src/__testUtils__/kitchenSinkQuery.js
- src/language/__tests__/printer-test.js
- src/utilities/__tests__/printSchema-test.js
In preparation for TS migration
> Workaround for Flow issue with 'String.raw'

- src/error/GraphQLError.js
- src/error/__tests__/locatedError-test.js
- src/error/locatedError.js
- src/execution/__tests__/abstract-test.js
- src/execution/__tests__/executor-test.js
- src/jsutils/__tests__/inspect-test.js
- src/language/__tests__/predicates-test.js
- src/language/lexer.js
- src/language/parser.js
- src/utilities/__tests__/buildClientSchema-test.js
- src/utilities/__tests__/coerceInputValue-test.js
- src/utilities/buildASTSchema.js
- src/utilities/extendSchema.js
- src/utilities/findBreakingChanges.js
- src/utilities/introspectionFromSchema.js
- src/utilities/lexicographicSortSchema.js
In preparation for TS convertion
> Flow: Replace force type conversion with explicit $FlowFixMe comments

- src/execution/execute.js
- src/jsutils/promiseReduce.js
- src/subscription/subscribe.js
Also resulted in ~10% perfomance increase for `execute` at least on my machine:
> collectFields: use ES6 collections instead of Object.create(null)

- src/index.d.ts
- src/index.js
- src/jsutils/Maybe.d.ts
- src/language/ast.d.ts
- src/language/ast.js
- src/language/directiveLocation.d.ts
- src/language/directiveLocation.js
- src/language/index.d.ts
- src/language/index.js
- src/language/kinds.d.ts
- src/language/kinds.js
- src/type/definition.d.ts
- src/type/definition.js
- src/type/index.d.ts
- src/type/index.js
- src/utilities/TypeInfo.d.ts
- src/utilities/TypeInfo.js
- src/utilities/getIntrospectionQuery.d.ts
- src/utilities/getIntrospectionQuery.js
- src/utilities/index.d.ts
- src/utilities/index.js
- src/validation/index.d.ts
- src/validation/index.js
- src/validation/validate.d.ts
- src/validation/validate.js
Typescript strips all non-TSDoc documents in generated definitions
> `*.d.ts`: Switch comments to comment to TSDoc

- src/error/formatError.d.ts
This change was made back when TS typings was hosted on DefinetlyTyped
see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36205
If such function is requested it should be implemented similar to
extensions in `GraphQL*Type` classes.
> TS: Drop template argument from GraphQLFormattedError

- src/execution/__tests__/stream-test.ts
- src/execution/execute.ts
This seems to work with me for my project.
not quite sure what to do about isDone which seems to be used just when return is  called (parenthetically, should that be renamed to isReturned for clarity/distinction between `isDone` and `done` attributes?)
namely, should the isDone check go up top prior to checking for the next resolved promise, within the next resolved promise check, or maybe both.
in general, not sure how we are really handling secure stopping issues, seems like -- for example -- there could be condition in which we await a promise which never resolves, but that is ok, because return has been called?
but still quite the novice with all of this async stuff
---From my opinionated perspective, I realize that graphql-js is a reference lib, and has a zero-dependency footprint, …
> fix(race): concurrent next calls with defer/stream

- src/language/__tests__/lexer-test.ts
- src/language/ast.ts
- src/language/lexer.ts
- src/language/parser.ts
The lexer needed some cleanup, I found myself doing this as part of a Unicode RFC, but factoring all that out to make the Unicode RFC PR easier to follow.
* Always use hexadecimal form for code values.
* Remove use of `isNaN` for checking source over-reads.
* Defines `isSourceCharacter`
* Add more documentation and comments, also replaces regex with lexical grammar
* Simplifies error messages
* Adds additional tests
> Refactor Lexer

- src/validation/__tests__/SingleFieldSubscriptionsRule-test.ts
- src/validation/__tests__/harness.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
This PR implements the spec changes in the following GraphQL Spec RFC:
https://github.com/graphql/graphql-spec/pull/776
> RFC: Assert subscription field is not introspection.

- src/execution/execute.ts
The function implements the "Executing Field" section of the spec and should be called `executeField` rather than `resolveField` to reduce ambiguity.
Motivation: (1) correctness and (2) lays the groundwork for -- possibly -- providing a custom function for fields to optimize their execution, say, by not calling `getArgumentValues` if the arguments are passed unparsed to some external graphql service, or what have you.
Right now, if we would add a custom `execute` function, we would have to have a code block within a function called `resolveField` that calls the custom execute. Resolving is a part of executing, and so there is a semantic clash that could get pretty confusing (at least for me).
> execute: Rename resolveField function and update comments

- resources/build-npm.js
Example `v16.0.0-alpha.3.experimental-stream-defer.2`
Reported by @robrichard
> build-npm: correctly set NPM tag on experimental pre-releases

- .mocharc.yml
https://github.com/TypeStrong/ts-node/issues/266
> allows passing --watch to npm run testonly

- .eslintrc.yml
- resources/eslint-internal-rules/index.js
- resources/eslint-internal-rules/require-to-string-tag.js
- src/language/__tests__/lexer-test.ts
- src/language/__tests__/parser-test.ts
- src/language/ast.ts
- src/language/lexer.ts
- src/utilities/TypeInfo.ts
- src/utilities/__tests__/TypeInfo-test.ts
- src/validation/ValidationContext.ts
- src/validation/__tests__/ValidationContext-test.ts
> Add 'Symbol.toStringTag' into every publicly exported class

- src/jsutils/__tests__/instanceOf-test.ts
- src/jsutils/instanceOf.ts
> Avoid relying on constructor.name for instanceOf error check.

- src/__testUtils__/__tests__/genFuzzStrings-test.ts
- src/__testUtils__/genFuzzStrings.ts
- src/__tests__/starWarsData.ts
- src/execution/__tests__/lists-test.ts
- src/execution/__tests__/union-interface-test.ts
- src/execution/execute.ts
- src/jsutils/__tests__/suggestionList-test.ts
- src/jsutils/inspect.ts
- src/language/__tests__/blockString-test.ts
- src/type/__tests__/validation-test.ts
- src/utilities/findBreakingChanges.ts
- src/utilities/separateOperations.ts
I extracted all breaking changes into separate commit so this one
contains only non-breaking changes, mostly tests and internal funcs
> Switch tests & internal funcs to accept ReadonlyArrays

- src/type/index.ts
`TypeKind` is currently exported as a type in `type/index.ts` but then re-exported as a value in `index.ts`. This causes the following error in webpack since type export are removed.
```
ERROR in ../../node_modules/graphql/index.mjs 32:0-128:26
export 'TypeKind' (reexported as 'TypeKind') was not found in './type/index.mjs'
```
`TypeKind` seems to be a value so I changed it to be exported as a value in `type/index.ts`.
Tested that this fixes the issue in an app.
> Export TypeKind as value

- src/execution/collectFields.ts
- src/execution/execute.ts
- src/subscription/subscribe.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
Taken from #3184, changing source branch to be on main repo to more easily stack PRs.
> refactor: collectFields to separate utility

- .eslintrc.yml
- integrationTests/integration-test.js
- integrationTests/webpack/entry.js
- integrationTests/webpack/package.json
- integrationTests/webpack/test.js
- integrationTests/webpack/webpack.config.json
> integrationTests: Add test for webpack

- src/jsutils/__tests__/instanceOf-test.js
- src/jsutils/instanceOf.js
This backports #3172 to the `15.x.x` branch so that users of GraphQL
v15.x can take advantage of it. GraphQL v16.x has some breaking changes
and is not possible to run when you have other libraries depending on
the behavior of v15, such as GraphQL Code Generator.
> Backport instanceOf Error Check Improvements

- benchmark/benchmark.js
- integrationTests/integration-test.js
- resources/build-deno.js
- resources/build-npm.js
Backport of #2972 to 15.x.x branch
> Remove deprecated rmdirSync usage from internal scripts

- .eslintrc.yml
- package-lock.json
- package.json
- src/__testUtils__/dedent.ts
- src/__tests__/starWarsSchema.ts
- src/error/GraphQLError.ts
- src/error/formatError.ts
- src/execution/collectFields.ts
- src/execution/execute.ts
- src/index.ts
- src/jsutils/isIterableObject.ts
- src/jsutils/keyMap.ts
- src/jsutils/keyValMap.ts
- src/language/lexer.ts
- src/language/parser.ts
- src/language/printer.ts
- src/language/visitor.ts
- src/type/definition.ts
- src/type/schema.ts
- src/utilities/printSchema.ts
- src/utilities/stripIgnoredCharacters.ts
- src/validation/validate.ts
Add [`eslint-plugin-tsdoc`](https://tsdoc.org/pages/packages/eslint-plugin-tsdoc/) to start working on doc generation.
> build: add eslint-plugin-tsdoc

- cspell.yml
- src/language/__tests__/lexer-test.ts
- src/language/__tests__/printString-test.ts
- src/language/lexer.ts
- src/language/printString.ts
- src/language/printer.ts
- src/type/__tests__/introspection-test.ts
Depends on #3115
Implements RFC at graphql/graphql-spec#849.
* Replaces `isSourceCharacter` with `isUnicodeScalarValue`
* Adds `isSupplementaryCodePoint`, used in String, BlockStrings, and Comments to ensure correct lexing of JavaScript's UTF-16 source.
* Updates `printCodePointAt` to correctly print supplementary code points.
* Adds variable-width Unicode escape sequences
* Adds explicit support for legacy JSON-style fixed-width Unicode escape sequence surrogate pairs.
* Adds `printString` to no longer rely on `JSON.stringify`. Borrows some implementation details from Node.js internals for string printing.
Implements:
> When producing a {StringValue}, implementations should use escape sequences to
> represent non-printable control characters (U+0000 to U+001F and U+007F to
> U+009F). …
> RFC: Support full Unicode in lexer

- src/language/__tests__/parser-test.ts
- src/language/parser.ts
The specification disallows these in the SDL grammar definition, and using one of these enum values would result in a schema that would throw validation errors on creation.
Fixes #3221.
I also changed the type of `EnumValueDefinitionNode.name` from `NameNode` to `EnumValueNode`, so this is definitely breaking. We might even want to rename the `name` property to `value`, but that would be even more breaking.
> Disallow "true", "false", and "null" as enum values

- src/execution/__tests__/executor-test.ts
- src/execution/execute.ts
> execute: Forbid to return `null` from `serialize` function

- src/language/__tests__/schema-parser-test.ts
- src/language/parser.ts
> parser: add specialized error for extension with descriptions

- src/type/__tests__/definition-test.ts
- src/type/definition.ts
`GraphQLInputObjectType.toConfig()` currently doesn't preserve `deprecationReason`s on its fields. Anything internal depending on this function omits the `deprecationReason` from a `GraphQLInputObjectType`'s fields.
This was easy to remedy - we just needed to copy the field's `deprecationReason` property during the mapping of fields done in `toConfig()`.
I experienced this issue when using `extendSchema` on a `GraphQLSchema` object which had a `GraphQLInputObjectType` with fields marked `@deprecated`. The reason would be dropped from the extended schema.
> fix: Preserve `deprecationReason` on `GraphQLInputField`s

- src/type/__tests__/definition-test.js
- src/type/definition.js
Backported from #3257
Co-authored-by: Ivan Goncharov <ivan.goncharov.ua@gmail.com>
> backport: Preserve `deprecationReason` on `GraphQLInputField`s

- src/type/definition.ts
Tried out the 16.0.0-rc and noticed the change from return type of `GraphQLFieldResolver` from [any in 15.x](https://github.com/graphql/graphql-js/blob/acc468bb550222d6ac0893d0655720d540e24566/src/type/definition.d.ts#L467-L476) to `unknown`. While this type change is correct, it'd be better if the generic could be specified by a consumer library, for instance if maintaining the previous behavior of `any` is desired in a library usage.
> Add TResult to GraphQLFieldResolver signature

- integrationTests/integration-test.js
With previous timeout Webpack test was failing on CI from time to time
> integrationTests: increase timeout to 60s

- src/index.ts
- src/language/__tests__/visitor-test.ts
- src/language/index.ts
- src/language/visitor.ts
See https://github.com/graphql/graphql-js/issues/3245#issuecomment-907177003
I checked `Allow edits by maintainers`. So you can make changes on this PR instead of creating a new one by checking out this branch using GitHub CLI. Also you can leave comments here then I can also do the changes you want :)
> Bring `visitorKeys` back

- benchmark/visit-benchmark.js
- benchmark/visitInParallel-benchmark.js
- src/index.ts
- src/language/__tests__/visitor-test.ts
- src/language/index.ts
- src/language/visitor.ts
- src/utilities/TypeInfo.ts
speed up to `visit` and especially to `visitInParallel` (almost x2 speed up).
However, this optimization is only possible if we know all possible `kind`s of nodes in advance.
> visitor: speed up visitInParallel by dropping support for unknown nodes

- src/type/__tests__/introspection-test.ts
- src/type/introspection.ts
- src/utilities/__tests__/getIntrospectionQuery-test.ts
- src/utilities/__tests__/printSchema-test.ts
> type/introspection: add missing `__Directive.args(includeDeprecated:)`

- src/validation/__tests__/KnownTypeNamesRule-test.ts
- src/validation/__tests__/VariablesAreInputTypesRule-test.ts
- src/validation/rules/VariablesAreInputTypesRule.ts
> VariablesAreInputTypesRule: add test for ignoring unknown types

- src/validation/rules/ExecutableDefinitionsRule.ts
- src/validation/rules/FieldsOnCorrectTypeRule.ts
- src/validation/rules/FragmentsOnCompositeTypesRule.ts
- src/validation/rules/KnownArgumentNamesRule.ts
- src/validation/rules/KnownDirectivesRule.ts
- src/validation/rules/KnownFragmentNamesRule.ts
- src/validation/rules/KnownTypeNamesRule.ts
- src/validation/rules/LoneAnonymousOperationRule.ts
- src/validation/rules/NoFragmentCyclesRule.ts
- src/validation/rules/NoUndefinedVariablesRule.ts
- src/validation/rules/NoUnusedFragmentsRule.ts
- src/validation/rules/NoUnusedVariablesRule.ts
- src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
- src/validation/rules/UniqueArgumentNamesRule.ts
- src/validation/rules/UniqueDirectivesPerLocationRule.ts
- src/validation/rules/UniqueFragmentNamesRule.ts
- src/validation/rules/UniqueInputFieldNamesRule.ts
- src/validation/rules/UniqueOperationNamesRule.ts
- src/validation/rules/ValuesOfCorrectTypeRule.ts
- src/validation/rules/VariablesAreInputTypesRule.ts
- src/validation/rules/VariablesInAllowedPositionRule.ts
* Added missing documentation
* Added links to GraphQL spec
> Improve documentation of validation rules

- src/execution/execute.ts
- src/execution/subscribe.ts
- src/graphql.ts
> Add devAssert about removal of positional arguments

- src/index.ts
- src/type/index.ts
- src/type/scalars.ts
Closes #2524
(Replaces abandoned #2582)
> Export GRAPHQL_MAX_INT and GRAPHQL_MIN_INT

- src/language/__tests__/blockString-fuzz.ts
- src/language/__tests__/blockString-test.ts
- src/language/blockString.ts
- src/language/characterClasses.ts
- src/language/lexer.ts
- src/utilities/__tests__/printSchema-test.ts
- src/utilities/printSchema.ts
- src/utilities/stripIgnoredCharacters.ts
Fixes #2577
Fixes #2589
cc @Cito
> printSchema: handle descriptions that are non-printable as block strings

- src/execution/execute.ts
Altered a couple of them to be more in line with the names in the current spec
> execute: fix spec section names in comments

- src/language/__tests__/lexer-test.ts
This PR is in preparation for https://github.com/graphql/graphql-js/pull/3281
Question marks are valid characters after that PR, so we need to pick something new
> lexer-tests: Use tildas as invalid characters

- src/error/__tests__/locatedError-test.ts
- src/error/locatedError.ts
- src/jsutils/toError.ts
> Preserve non-error values thrown from resolvers

- .eslintrc.yml
- package-lock.json
- package.json
- resources/eslint-internal-rules/index.js
- resources/eslint-internal-rules/require-coverage-ignore-reason.js
It blocks us from using ESLint8, see:
https://github.com/istanbuljs/eslint-plugin-istanbul/pull/17
> Drop "eslint-plugin-istanbul" and implement as internal ESLint rule

- README.md
hello, I was trying out graphql-js today and noticed that the Readme documentation doesn't match the current object-based interface
> Update doc examples to reflect the current API

- package.json
- resources/build-npm.js
It's far from an ideal solution but it least it makes it more explicit
> package.json: Specify NPM release tag explicitly

- src/index.ts
- src/type/definition.ts
- src/type/index.ts
Required to migrate `graphql-relay` to `graphql@16`
> type/definition: export `resolve*Thunk` functions

- .github/workflows/ci.yml
> gh/actions: run benchmark and NPM diff on correct base commits

- .github/CONTRIBUTING.md
GraphQL was moved to GraphQL Foundation many years ago.
> CONTRIBUTING.md: remove reference to Facebook bug bounty program

- src/validation/__tests__/UniqueArgumentDefinitionNamesRule-test.ts
- src/validation/rules/UniqueArgumentDefinitionNamesRule.ts
- Added validation tests for type and interface extensions
- Added link to GraphQL spec
> UniqueArgumentDefinitionNamesRule: Improve tests

- src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.ts
- src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
We have spotted some `RangeError: Maximum call stack size exceeded` exceptions while testing our own setup, and traced it to this validation rule.
Note: I don't feel 100% confident that I understand the logic flow and intent of this code in detail. Perhaps the bugfix I'm providing is isolated, or perhaps it's a whole class of use case that has been omitted in tests in which cases this might break some valid use cases but not be detected?
>  Prevent Infinite Loop in OverlappingFieldsCanBeMergedRule

- src/type/schema.ts
schema.toConfig() doesn't carry through the `enableDeferStream` setting currently; this fixes that omission.
Note: this is a PR to the defer-stream branch.
> Add enableDeferStream to GraphQLSchema::toConfig()

- src/error/GraphQLError.ts
- src/error/__tests__/GraphQLError-test.ts
When using the `GraphQL` error within my schema code I usually only use the `message` and `extensions` parameters. However, this requires passing 4 undefined values to the constructor.
```ts
throw new GraphQLError("Oops.", undefined, undefined, undefined, undefined, { code: "SERVER_GOES_BRRT" })
```
This API allows writing this code, which feels less verbose to me.
```ts
throw new GraphQLError({
message: "Oops.",
extensions: { code: "SERVER_GOES_BRRT" },
})
```
Given that the `execute` and `subscribe` function signatures also evolved into a single object, this change feels natural to me. Please let me know what you think.
An alternative API might be the following, where the message is ALWAYS the first argument.
```ts
throw new GraphQLError("Oops.", {
extensions: { code: "SERVER_GOES_BRRT" …
```
> feat: allow providing an object to the GraphQLError constructor

- src/execution/index.ts
- src/execution/values.ts
- src/index.ts
> Expose `getArgumentValues` as public API

- .github/workflows/canary.yaml
- .github/workflows/ci.yml
> ci: add stub action for canary releases on PRs

- src/execution/index.ts
- src/execution/values.ts
- src/index.ts
> feat: expose getArgumentValues

- src/type/definition.ts
according #3231 returning `null` was no longer allowed.
> correct outdated documentation

- src/error/GraphQLError.ts
The GraphQLError constructor has two overloads. The GraphQLErrorArgs one
is recommended and the one with a bunch of position arguments is
deprecated.
When typechecking, TypeScript chooses the *first* matching overload (see
eg
https://github.com/microsoft/TypeScript/issues/1860#issuecomment-72154737).
Passing just a message argument matches both overloads, so this
currently displays as deprecated.
This PR reverses the order so that passing just a message does not
display as deprecated.
> GraphQLError: switch constructor overload order

- src/utilities/__tests__/printSchema-test.ts
Extracted from #3362
Co-authored-by: spawnia <benedikt@franke.tech>
> tests(printSchema): test omitting schema of common names

- src/error/GraphQLError.ts
Not positive, but given that the deprecated method calls `error.toJSON()` I'm assuming the docs should reflect this?
> Update documentation on deprecated formatError(..)

- codecov.yml
This PR updates the Codecov config to pass the valid option.
https://docs.codecov.com/docs/pull-request-comments#disable-comment
> To disable the comment, simply set the top-level comment key to false in your codecov.yml, as shown below.
> pass valid value to codecov config

- src/language/__tests__/printer-test.ts
- src/language/__tests__/schema-printer-test.ts
- src/language/printer.ts
- src/type/__tests__/introspection-test.ts
- src/type/__tests__/scalars-test.ts
- src/utilities/__tests__/buildClientSchema-test.ts
- src/utilities/__tests__/findBreakingChanges-test.ts
- src/utilities/__tests__/sortValueNode-test.ts
Matches prettier output, see:
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEmCGAKHAJwHMlNgckBGAXwEoMaQAaECABxgEtoBnZUEUIQA7gAUiCfihwAbETgCe-VgCNCOMAGs4MAMo4AtnAAyXKHGQAzObzhqN23XvabzxZDEIBXeyDiGqnAAJsEhJjhQxN44xHAAYhCEhjgw3FHIIDjeMBAsIAAWMIayAOoFXPC8rmBwelKVXABulYqZYLwqIOZ2hDBiGsQp1rZ+AFa8AB567rJwAIreEPAjsnasroS9mcQa7AUAjrL57ITmMKVcwTAFyAAcAAwbwnale5mncL1NlqwHS-ABhxpFleABaCwhEL5Qhwf5cWEDWLDJA2NZ+OyGLieHwY2YLAGWVGjVgwHCqS7XW5IABMpI0XFk7gAwhBDCj-LwAKz5bx2AAq5OkaPWICavgAklAwrA9GAzpwAILSvQwRRzVZ2Gg0IA
> print: add spaces inside input object

- .babelrc-npm.json
- .eslintrc.yml
- benchmark/benchmark.js
- benchmark/buildASTSchema-benchmark.js
- benchmark/buildClientSchema-benchmark.js
- benchmark/fixtures.js
- benchmark/introspectionFromSchema-benchmark.js
- benchmark/parser-benchmark.js
- benchmark/validateGQL-benchmark.js
- benchmark/validateInvalidGQL-benchmark.js
- benchmark/validateSDL-benchmark.js
- benchmark/visit-benchmark.js
- benchmark/visitInParallel-benchmark.js
- integrationTests/node/index.js
- integrationTests/node/package.json
- integrationTests/node/test.js
- integrationTests/ts/package.json
- integrationTests/ts/test.js
- integrationTests/webpack/entry.js
- integrationTests/webpack/package.json
- integrationTests/webpack/test.js
- integrationTests/webpack/webpack.config.json
- package.json
- resources/build-npm.js
- resources/utils.js
As disscussed during graphql-js-wg:
https://github.com/graphql/graphql-js-wg/blob/main/agendas/2022-03-30.md
> Switch NPM package to support only ESM

- src/error/GraphQLError.ts
- src/error/index.ts
- src/index.ts
Also rename `GraphQLErrorArgs` to `GraphQLErrorOptions`.
It align naming with standard JS `Error` where constructor's second argument called `options`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error
> Expose GraphQLErrorOptions type

- .eslintrc.yml
- src/jsutils/instanceOf.ts
The `process` object is only available in Node.js and Node.js-like environments (e.g. webpack).
By introducing this simple change, the code can run in a browser environment without requiring polyfilling Node.js APIs such as the following:
```html
<script>
window.process = globalThis.process = {
env: {
NODE_ENV: "development"
}
};
</script>
```
`globalThis` is part of the ECMA 2020 specification and is supported on any relevant platform.
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis
- https://tc39.es/ecma262/multipage/global-object.html#sec-globalthis
- https://node.green/#ES2020-features-globalThis
The eslint config specifies ecma version 2020 but it seems like the `globalThis` is not automatically provided. I added the `es2020` env. …
> fix: only access Node.js globals if available

- src/error/GraphQLError.ts
- src/error/index.ts
- src/index.ts
Backport of https://github.com/graphql/graphql-js/pull/3554
> Expose GraphQLErrorOptions type (#3554)

- src/jsutils/didYouMean.ts
- src/jsutils/formatList.ts
- src/type/__tests__/validation-test.ts
- src/type/validate.ts
Hello `graphql-js` folks 👋 While playing with schema and SDL validation, I noticed that the reference implementation does not follow the following rule from the [latest spec](https://spec.graphql.org/draft/#sec-Root-Operation-Types):
> The query, mutation, and subscription root types must all be different types if provided.
Not sure if that's an error in the spec or in the reference implementation 🤔 I went ahead and proposed a fix in here, but happy to open a PR on the spec instead if that's the preferred. This is after all a breaking change, even though I doubt that it would have a big impact. (At least I've never seen a schema that does this.)
> fix(validate): no reusing root types

- .eslintrc.yml
- resources/benchmark.ts
- resources/build-deno.ts
- resources/build-npm.ts
- resources/gen-version.ts
> Remove superficial ESLint config

- src/validation/__tests__/validation-test.ts
- src/validation/validate.ts
This reverts commit b4ad1282ce38449a953d9375307c9e45f8151a70 from #3574
For the context see #3519
> Revert "Remove deprecated `TypeInfo` argument of `validate` function"

- src/index.ts
- src/type/definition.ts
- src/type/index.ts
= If a type is a non-null type, then the wrapped type must be nullable.
= Introduces `GraphQLNullableInputType` and `GraphQLNullableOutputType` to properly represent the result when `isNonNullType` is called on parameters of type `GraphQLInputType` or `GraphQLOutputType`.
> Fix typing for `isNonNullType`

- src/type/definition.ts
Motivation:
1. Makes it easier to understand the type hierarchy.
2. Adding a new type, were it ever to happen, would require fewer code changes.
Depends on #3597
> Refactor `GraphQL*Type` TS types to be more DRY

- benchmark/GraphQLSchema-benchmark.js
Nessary as part of a current and possible future disscussion on perfomance penalties of schema
transformation.
> benchmark: test performance cost of re-creating schema

- resources/utils.ts
`git rev-list` inside `resources/gen-changelog.js` returned empty list
and that caused `assert` to be triggered.
Moreover `execSync` always return string and can't return null or
undefined.
> gen-changelog: fix crash due to 'git rev-list' returning empty string

- .eslintrc.yml
- .github/workflows/cmd-run-benchmark.yml
- benchmark/introspectionFromSchema-benchmark.js
- resources/benchmark.ts
This is stacked PR, for descriptions of various changes please look into the description of underlying commits.
> benchmark: various improvments to benchmark

- src/execution/execute.ts
- src/execution/subscribe.ts
- src/type/__tests__/schema-test.ts
- src/type/schema.ts
- src/utilities/TypeInfo.ts
- src/utilities/__tests__/TypeInfo-test.ts
Motivation: generalize it and remove code dublication in two places and
also allow to use as public API outside of graphql-js
> Add new 'GraphQLSchema.getField' method

- .github/workflows/cmd-publish-pr-on-npm.yml
- .github/workflows/github-actions-bot.yml
- resources/diff-npm-package.ts
`writeFileSync` by default use utf-8, see
https://nodejs.org/api/fs.html#fswritefilesyncfile-data-options
> Remove 'utf-8' as argument of `writeFileSync`

- resources/benchmark.ts
- resources/build-npm.ts
- resources/diff-npm-package.ts
- resources/utils.ts
Extracted from #3564
Motivation: `__dirname` and `require.resolve` is CJS specific mechanism
and we use them in multiple places. Even without ESM migration this
function makes internal scripts more high-level and thus readable.
> resources: add new `localRepoPath` utility function

- .github/workflows/pull_request.yml
- resources/diff-npm-package.ts
This folder already used for stryker's and c8's reports.
Motivation: Makes it easier to manage ignore files for various tools.
> diff-npm-package: move report into shared 'reports' folder

- .github/workflows/cmd-publish-pr-on-npm.yml
- .github/workflows/cmd-run-benchmark.yml
- .github/workflows/github-actions-bot.yml
Motivation: API calls to GH are async and require top-level await.
Also add 'node:' prefix to all node modules.
> github actions: switch embedded JS to ESM

- .github/workflows/ci.yml
Git 2.32.0 introduced breaking change that silently broke this script
https://stackoverflow.com/questions/68292683/fatal-ls-files-i-must-be-used-with-either-o-or-c-with-git-2-32-0
> GH actions: fix 'checkForCommonlyIgnoredFiles'

- .github/workflows/ci.yml
- .github/workflows/cmd-publish-pr-on-npm.yml
- .github/workflows/cmd-run-benchmark.yml
- .github/workflows/deploy-artifact-as-branch.yml
- .github/workflows/pull_request.yml
Right now we pass NPM token in github action and plan to have automatic
releases that is why it is critical to lint action files.
I didn't find any JS-based solution and the only validator I could find
is https://github.com/rhysd/actionlint
> Lint GitHub Actions

- resources/benchmark.ts
Consequently failed measurements due to context switches are bad.
It mean something is bad with our setup:
* Our test are taking too long to run (e.g. due to `count` being too
big)
* Machine that we measure on is doing some heave background task.
* Some other factors, that are hard to predict.
Currently, it's easy to solve this issue locally just by disabling
background task on your machine, but it is non-trivial task to solve on
CI.
> benchmark: replace failing on context switching with warning

- resources/diff-npm-package.ts
#3623 creates the reports folder via the report path, rather than the reports folder path. This did not trigger an error, because no changes were found.
> diff-npm-package: fix reports dir creation

- src/utilities/__tests__/extendSchema-test.ts
- src/utilities/extendSchema.ts
Without this change:
```
const extendedSchema = extendSchema(schema, parse(extensionSDL));
extendSchema.getDirective('skip') === GraphQLSkipDirective
// false
```
Maybe in future we need more comprehensive solution, but for now it's enouch to just match behaviour that we already have to standard types.
> extendSchema: Do not modify standard directives

- .github/workflows/cmd-publish-pr-on-npm.yml
- .github/workflows/cmd-run-benchmark.yml
- .github/workflows/github-actions-bot.yml
I did 'require => import' change together with top-level await change in #3612
I assumed if top-level `async` is working it means `import` should also work.
In reality, `actions/github-script` was passing code to async function
constructor. That means top-level await is not really top-level since it
gets injected into a function and we still execute in CJS context and
`import` will fail.
> ci: Fix imports in 'actions/github-script'

- src/type/definition.ts
This is related to #3597, in the sense that #3597 made the `GraphQLNonNull<GraphQL*Type>` => `GraphQLNonNull<GraphQLNullable*Type>` change in other code points related to the `isNonNullType` function, but not within `GraphQLWrappingType` or assertNonNullType.
This PR was prompted by the uncovering of a bug by a different PR, see: https://github.com/graphql/graphql-js/pull/3617#discussion_r885544662
> fix: update remaining `GraphQLNonNull<GraphQLType>` codepoints to `GraphQLNonNull<GraphQLNullableType>` 

- src/type/definition.ts
Now GraphQLType is union of named types and wrapping types.
Spotted during review of #3622
> Reuse GraphQLWrappingType in 'GraphQLType' definition

- .github/workflows/ci.yml
This depedency was originaly added because those jobs were doing actual
deploying, now that they simply build artifacts there are no reasons for
them to be locked on other jobs
> ci: speed up 'ci' workflow by removing unneeded internal dependencies

- resources/benchmark.ts
1. use local git clone instead of git archive | tar
2. normalize module path within sampleCode
Motivation: Windows users should not be required to use WSL to run benchmark (or any other scripts). The library should be cross-platform as possible both at runtime and in development.
Furthermore: it may be valuable to benchmark in multiple environemnts, including unix-type environments, WSL, and native Windows runtimes.
> benchmark: add Windows compatibility

- src/execution/__tests__/subscribe-test.ts
Two test groups use essentially the same logic to set up a subscription with an improper subscribeFn, testing both `subscribe` and `createSourceEventStream`.
This PR extracts the duplicated logic into a single common `subscribeWithBadFn` function.
For convenience, the common function is typed to appropriately return a `Promise<ExecutionResult>` rather than a `Promise<ExecutionResult | AsyncGenerator<...>>`). Because the `subscribeFn` is expected to be "bad," an `AsyncGenerator` should never be returned. If a valid `subscribeFn` is mistakenly passed, an assertion failure is triggered.
extracted from #3620
> subscribe-test: extract `subscribeWithBadFn` function

- src/execution/__tests__/subscribe-test.ts
- src/execution/subscribe.ts
…rather than a systems error
to match spec (in parallel to field-level resolver errors in execute)
note the addition of the path, as execution has begun
> change incorrect subscribe return type to a GraphQLError

- src/execution/__tests__/subscribe-test.ts
- src/execution/subscribe.ts
with respect to possible promises
motivations:
1. no need to enter event loop unnecessarily
2. further step toward integration of `subscribe` workflow into `execute`
> align return types from execution and subscription

- src/execution/__tests__/subscribe-test.ts
- src/execution/subscribe.ts
Deprecates the positional arguments to `createSourceEventStream`, to be removed in the next major version, in favor of named arguments.
Motivation:
1. aligns `createSourceEventStream` with the other exported entrypoints `graphql`, `execute`, and `subscribe`
2. allows simplification of `mapSourceToResponse`
suggested by @IvanGoncharov
> createSourceEventStream: introduce named arguments and deprecate positional arguments

- src/execution/__tests__/subscribe-test.ts
- src/execution/subscribe.ts
See #3634, which introduced a named argument form for the exported function and deprecated the original positional argument overload. This is to be backported to v16.
This PR removes the deprecated format from v17. It is a BREAKING CHANGE and cannot be backported.
This PR depends on #3634.
> createSourceEventStream: remove deprecated positional argument overload

- src/execution/__tests__/executor-test.ts
- src/execution/__tests__/subscribe-test.ts
- src/execution/execute.ts
- src/language/__tests__/source-test.ts
- src/language/source.ts
- src/type/__tests__/assertName-test.ts
- src/type/__tests__/definition-test.ts
- src/type/__tests__/directive-test.ts
- src/type/__tests__/predicate-test.ts
- src/type/__tests__/schema-test.ts
- src/type/assertName.ts
- src/type/definition.ts
- src/type/directives.ts
- src/type/schema.ts
- src/utilities/__tests__/buildASTSchema-test.ts
- src/utilities/__tests__/extendSchema-test.ts
- src/utilities/buildASTSchema.ts
- src/utilities/buildClientSchema.ts
- src/utilities/extendSchema.ts
- src/validation/__tests__/validation-test.ts
- src/validation/validate.ts
`graphql` provides TS types since `14.5.0` (released 3 years ago)
and we fully switched to TS in `15.0.0` so I think it's time to drop
runtime typechecks.
Motivations: This type checks were added long time ago since we shifted
towards TS we just maintained them without adding new ones.
In general, this check increase bundle size add runtime cost and we
can't realistically check all arguments to all functions.
Instead we should focus on adding more asserts on stuff that can't be
checked by TS.
> Remove 'devAssert' checks that duplicate TS types

- src/execution/execute.ts
After we drop runtime type checks that were duplicating TS types in #3642 
this function became a wrapper for 'assertValidSchema' so all clients
that rely on it can now use 'assertValidSchema' directly.
> Remove 'assertValidExecutionArguments' function

- src/execution/execute.ts
1. `executeOperation` can take only one parameter, `operation` is included within `exeContext`
2. use spread syntax to retrieve properties from `exeContext`
@IvanGoncharov this is a small hopefully straightforward PR that can be merged (as two separate commits or as a squashed commit if you would prefer) if #3639 or #3644 are blocked.
> refactor: use `exeContext` strategically

- src/execution/__tests__/subscribe-test.ts
- src/execution/execute.ts
= introduces `buildPerEventExecutionContext` that creates an `ExecutionContext` for each subscribe event from the original `ExecutionContext` used to create the event stream
= `subscribe` now directly builds the `ExecutionContext` instead of relying on `createSourceEventStream`
= introduces `createSourceEventStreamImpl` and `executeImpl` functions that operate on the built `ExecutionContext` rather the `ExecutionArgs`
= `subscribe` calls the `createSourceEventStreamImpl` function on the original context and eventuallys calls `executeImpl` on the per event context created by `buildEventExecutionContext`.
Motivation:
1. remove unnecessary `buildExecutionContext` call, reducing duplicate work
2. paves the way for easily enhancing the `buildPerEventExecutionContext` to add a new …
> refactor: subscribe: introduce `buildPerEventExecutionContext`

- benchmark/list-async-benchmark.js
- benchmark/list-sync-benchmark.js
- resources/benchmark.ts
As discussed in the graphql-js WG meeting.
Taken from https://github.com/graphql/graphql-js/pull/2757
> Async benchmarks

- cspell.yml
cspell itself and its dictionaries improved a lot so now we remove some of our custom config
> Cleanup words/files ignores in `cspell.yml`

- resources/build-npm.ts
- src/error/GraphQLError.ts
- tsconfig.json
As part of #3649 research I added all options explicitly and also
enable ones that didn't require any code change.
We should enable rest of them in a separate PRs.
> tsconfig: Explicitly list all type checking options

- integrationTests/ts/kitchenSink-test.ts
- integrationTests/ts/tsconfig.json
- src/error/GraphQLError.ts
- src/execution/__tests__/union-interface-test.ts
- src/execution/values.ts
- src/language/ast.ts
- src/language/parser.ts
- src/language/visitor.ts
- src/type/definition.ts
- src/type/schema.ts
- src/type/validate.ts
- src/utilities/buildASTSchema.ts
- src/utilities/extendSchema.ts
- src/validation/rules/UniqueArgumentDefinitionNamesRule.ts
- src/validation/rules/UniqueArgumentNamesRule.ts
- src/validation/rules/UniqueFieldDefinitionNamesRule.ts
- tsconfig.json
`exactOptionalPropertyTypes` is recommended option that was added in TS 4.4 but our public API
was not compatible with it. 
Meaning if the project was using graphql-js and had this enabled this flag they lost the ability to pass `undefined` values explicitly.
Context: discovered as part of #3649 investigation.
> Fix: make public API compatible with 'exactOptionalPropertyTypes'

- src/language/parser.ts
Continuation of #3670
Basically allow to have code like this:
```js
parse(document, GraphQLServerConfig.parserOptions)
```
to pass TS check with 'exactOptionalPropertyTypes'
> Parser: allow 'options' to explicitly accept undefined

- src/validation/validate.ts
Motivation: I'm working on the similar code in parser and don't want to
replicate ESLint disable comment so figured out a proper way to solve
it. Also throwing error with message will help with debuging if someone
will have an issue with `validate` code.
> validate: remove warning about throwing literal

- src/language/__tests__/parser-test.ts
- src/language/parser.ts
Motivation: Parser CPU and memory usage are linear to the number of tokens in a document however, in extreme cases, it becomes quadratic due to memory exhaustion.
On my machine, it happens on queries with 2k tokens.
For example:
```
{ a a <repeat 2k times> a }
```
It takes 741ms on my machine.
But if we create a document of the same size but a smaller number of tokens, it would be a lot faster.
Example:
```
{ a(arg: "a <repeat 2k times> a" }
```
Now it takes only 17ms to process, which is 43 times faster.
If we just limit document size, we should make this limit small since it takes only two bytes to create a token, e.g. ` a`.
But that will create issues for legit documents with long tokens (comments, descriptions, strings, long names, etc.).
That's why this PR adds a mechanism to limit …
> parser: limit maximum number of tokens

- src/type/schema.ts
- src/type/validate.ts
- src/validation/ValidationContext.ts
- src/validation/rules/KnownTypeNamesRule.ts
- src/validation/rules/NoFragmentCyclesRule.ts
- src/validation/rules/NoUndefinedVariablesRule.ts
- src/validation/rules/NoUnusedFragmentsRule.ts
- src/validation/rules/NoUnusedVariablesRule.ts
- src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
Motivation: I was inspecting code for unrelated reason and just spotted this pattern.
I think it worth to refactor it since it easier to understand intention looking on code that uses Set's has/add methods.
Benchmark shows no measurable changes in CPU/memory usages.
> Replace all instances of `ObjMap<boolean>` with ES6 Set

- src/execution/execute.ts
- src/jsutils/__tests__/AccumulatorMap-test.ts
- src/jsutils/promiseForObject.ts
- src/type/validate.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
Motivation: Spotted during investigation of unrelated issue.
Maps and sets are iteratable, so no need to call these methods.
> Remove superficial `.values()` and `.entries()` calls

- src/utilities/extendSchema.ts
Explanation: `Object.create(null)` returns value of `any` type.
So below construct is not reported by TS even in "strict" mode:
```ts
const foo = Object.create(null);
```
Fixing this issue in `extendSchema` requires adding more code since we
can't put all extensions nodes into one collection without loosing
type-safety.
This PR also makes buildSchema/extendSchema ~40% faster
> Motivation: looked into this it as part of #3687

- src/__testUtils__/__tests__/expectEqualPromisesOrValues-test.ts
- src/__testUtils__/__tests__/expectMatchingValues-test.ts
- src/__testUtils__/__tests__/expectPromise-test.ts
- src/__testUtils__/expectEqualPromisesOrValues.ts
- src/__testUtils__/expectMatchingValues.ts
- src/__testUtils__/expectPromise.ts
- src/execution/__tests__/subscribe-test.ts
adds tests for `expectPromise` and `expectEqualPromisesOrValues`
#3620 introduced `expectEqualPromisesOrValues` with a TODO of moving to testUtils and testing.
This PR accomplishes that, and also moves the related `expectPromise` function, adding tests for that utility function as well.
> polish: add tests for `expectPromise` and `expectEqualPromisesOrValues`

- resources/benchmark.ts
Context: only recently benchmark.ts was moved into `resources` folder.
After this move it make sense to reuse utility code
> benchmark: use 'execOutput' from 'util.ts'

- src/execution/__tests__/mapAsyncIterable-test.ts
- src/execution/execute.ts
- src/execution/mapAsyncIterable.ts
1. rename to mapAsyncIterable => to better reflect function argument
2. use `expectPromise` in tests
extracted from #3694
> polish: mapAsyncIterator

- resources/benchmark.ts
- resources/diff-npm-package.ts
- resources/gen-changelog.ts
- resources/utils.ts
Context: This code existed before we started to use TS for scripts and I
wrote it incorrectly assuming that not every `exec` call will return
string.
Also improved a typing for `options` arguments reusing type from
`@types/node`.
> resources: merge execOutput and exec into single function

- src/language/ast.ts
- src/language/directiveLocation.ts
- src/language/kinds.ts
- src/language/tokenKind.ts
- src/type/introspection.ts
- src/utilities/findBreakingChanges.ts
Fixes #3685
Since we decide to get rid of TS enums in v17 anyway just add this
workaround to v16
> Workaround for codesandbox having bug with TS enums

- src/execution/__tests__/flattenAsyncIterable-test.ts
- src/execution/execute.ts
- src/execution/flattenAsyncIterable.ts
Fixes the bug demonstrated in #3709 (which has already been incorporated
into the defer-stream branch).
This fix is extracted from #3703, which also updates the typing and API
around execute. This particular change doesn't affect the API (other
than making the `subscribe` return type more honest, as its returned
generator could yield AsyncExecutionResult before this change as well).
> defer/stream: fix flattenAsyncIterable concurrency

- integrationTests/integration-test.ts
- resources/benchmark.ts
- resources/diff-npm-package.ts
- resources/gen-changelog.ts
- resources/utils.ts
Extracted from #3700
CodeQL correctly reported that we using user supplied data in our scripts
that can lead to shell injection.
Running those scripts on untrusted PRs both locally and on CI can be problematic
Note I reviewed all places and none of them can be exploited but it good practice
to switch to spawnSync if we can.
Aditional benefit it automatically solves all the issues with command arguments
being misenterpritade by the shell.
> resources: replace execSync with spawnSync

- src/execution/__tests__/defer-test.ts
- src/execution/__tests__/lists-test.ts
- src/execution/__tests__/mutations-test.ts
- src/execution/__tests__/nonnull-test.ts
- src/execution/__tests__/simplePubSub.ts
- src/execution/__tests__/stream-test.ts
- src/execution/__tests__/subscribe-test.ts
- src/execution/execute.ts
- src/execution/index.ts
- src/graphql.ts
- src/index.ts
This PR changes the `execute`, `subscribe`, and `graphql` APIs on the
`defer-stream` branch back to having the same API as on `main`: they can only
produce a single `ExecutionResult` (or a stream of `ExecutionResult`s for
`subscribe`) which never has a `hasNext` field, and do not support incremental
delivery.
Incremental delivery is now provided by the new entry points
`experimentalExecuteIncrementally` and `experimentalSubscribeIncrementally`. (We
will remove "experimental" once the proposal has been merged into the GraphQL
spec.)
This will make upgrading to graphql@17 easier, and increases the clarity
of return types.
Use distinct types for "the only result of a single-payload execution",
"the first payload of a multi-payload execution", and "subsequent
payloads of a multi-payload …
> defer/stream: split incremental delivery into new entry points

- src/execution/execute.ts
As far as I can tell, the ordering of subsequentPayloads is not used for
anything, so this lets use convert the O(n) indexOf and splice
operations in yieldSubsequentPayloads to sublinear.
> defer/stream: use Set for subsequentPayloads

- .github/workflows/ci.yml
Motivation: codeql are quite popular now, moreover various projects use it
as metric on how secure certain OSS project is. Example: https://github.com/
ossf/scorecard/blob/main/docs/checks.md#sast
Also, it can uncover some real security issues both in our sorce code and GitHub
workflows.
So I don't see a lot of harm by enabling it, we can always ignore certain files
or disable it completely.
Fixes #3162
> ci: Add CodeQL analysis

- src/execution/__tests__/defer-test.ts
- src/execution/__tests__/flattenAsyncIterable-test.ts
- src/execution/__tests__/lists-test.ts
- src/execution/__tests__/mutations-test.ts
- src/execution/__tests__/nonnull-test.ts
- src/execution/__tests__/stream-test.ts
- src/execution/__tests__/subscribe-test.ts
- src/execution/__tests__/sync-test.ts
- src/execution/collectFields.ts
- src/execution/execute.ts
- src/execution/flattenAsyncIterable.ts
- src/execution/index.ts
- src/graphql.ts
- src/index.ts
- src/type/directives.ts
- src/type/index.ts
- src/validation/__tests__/DeferStreamDirectiveLabelRule-test.ts
- src/validation/__tests__/DeferStreamDirectiveOnRootFieldRule-test.ts
- src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.ts
- src/validation/__tests__/StreamDirectiveOnListFieldRule-test.ts
- src/validation/__tests__/harness.ts
- src/validation/index.ts
- src/validation/rules/DeferStreamDirectiveLabelRule.ts
- src/validation/rules/DeferStreamDirectiveOnRootFieldRule.ts
- src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
- src/validation/rules/StreamDirectiveOnListFieldRule.ts
- src/validation/specifiedRules.ts
- website/docs/tutorials/defer-stream.md
- website/sidebars.js
Continued from https://github.com/graphql/graphql-js/pull/2839
This is the reference impementation of the defer/stream spec proposal. The corresponding PR for spec changes are here: https://github.com/graphql/graphql-spec/pull/742
Please limit comments on this PR to code review of this implementation. Discussion on the defer/stream spec is located in a dedicated repo: https://github.com/robrichard/defer-stream-wg/discussions
> Reference implementation of defer and stream spec

- package.json
- resources/integration-test.ts
Motivation: allow to reuse more stuff from 'resources/utils.ts'
Working on rebasing #3361 that adds even more code into integrationTests
so want to keep it simple by reusing code from 'utils.ts'
> ci: Move 'integration-test.ts' into 'resources'

- resources/benchmark.ts
- resources/build-docusaurus.ts
- resources/diff-npm-package.ts
- resources/gen-changelog.ts
- resources/integration-test.ts
- resources/utils.ts
Motivation: it's hard to debug scripts if stdout is not inherit
at the same time we need to capture output of some git/npm commands.
AFAIK node.js doesn't allow both "inherit" and "pipe" stdout, so
instead we create wrapper for npm/git where subcommands that doesn't
return values just "inherit" stdout.
> resources/utils.ts: npm/git will inherit stdout by default

- src/execution/__tests__/stream-test.ts
- src/execution/execute.ts
Implementing what was discussed in https://github.com/robrichard/defer-stream-wg/discussions/45
> Filter subsequent payloads when parent field is null

- resources/gen-changelog.ts
- resources/utils.ts
Motivation: since we switched to ESM now we can use top-level await to simplify code
> changelog: use top-level await to simplify code

- resources/build-deno.ts
- resources/build-npm.ts
- resources/utils.ts
Motivation: Remove custom code for finding *.ts files and reuse code from typescript library
> build-npm/deno: use TS to find all *.ts files

- .eslintignore
- .eslintrc.yml
- .gitignore
- .prettierignore
- integrationTests/node/index.mjs
- integrationTests/node/package.json
- integrationTests/node/test.js
- integrationTests/ts/esm.ts
- integrationTests/ts/package.json
- integrationTests/webpack/entry-esm.mjs
- integrationTests/webpack/package.json
- integrationTests/webpack/test.js
- integrationTests/webpack/webpack.config.json
- resources/build-npm.ts
- resources/integration-test.ts
- resources/utils.ts
I also just re-published graphql@16.0.1 as graphql-esm@16.0.1 https://npm.im/graphql-esm, tested it in an example project using libraries with full ESM support https://github.com/PabloSzx/test-graphql-esm, everything works perfectly 👌 
It can be tested right now doing this:
```json
{
"dependencies": {
"graphql": "npm:graphql-esm@^16.0.1"
}
}
```
> deploy full ESM with "type": "module" in "latest-esm" npm tag

- integrationTests/node/index.cjs
- resources/utils.ts
Context: previously we switched from `exec` to `spawn` to fix security issues. But `spawn` doesn't throw on failed command, this change tooks it into account.
> resources/util: spawn command fail on error

- .github/workflows/ci.yml
- .github/workflows/cmd-publish-pr-on-npm.yml
- .github/workflows/cmd-run-benchmark.yml
- .github/workflows/deploy-artifact-as-branch.yml
- .github/workflows/github-actions-bot.yml
- .github/workflows/mutation-testing.yml
- .github/workflows/push.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- src/execution/__tests__/defer-test.ts
- src/execution/execute.ts
when not streamed!
depends on #3746
> add filtering for asyncIterable lists

- src/execution/__tests__/stream-test.ts
note that filtering is still required for synchronous error bubbling with stream.
With defer, patches are not executed if the initial field set execution fails, but with stream, the initial items (perhaps of zero length) will execute and will create the stream record.
> polish: add additional test

- src/execution/execute.ts
Each commit is meant to merged separately, i.e. "Rebase and Merge" rather than "Squash and Merge"
419fd37f: moves `executeStreamField` out of try block to better illustrate which code might throw
2991c79a: tiny refactor pushing the result of `handleFieldError` rather than explicit null, following convention elsewhere
71a8db4f: rename `fieldPath` to `itemPath` when dealing with items, as elsewhere
4df02ca7: skip unnecessary filtering when asyncIterator's next method throws, aligning stream to non-stream
> incrementalDelivery: refactoring and streamlining

- src/execution/execute.ts
`buildPerEventExecutionContext` must use a new rootValue, and re-initialize the execution "state" portion of the `ExecutionContext`
> fix: re-initialize subsequentPayloads

- src/execution/__tests__/executor-test.ts
- src/execution/execute.ts
Fixes #3528
Ensures that if `executeFields` encounters a mix of promises and thrown errors, the promises will be awaited before throwing the error.
> Fix crash in node when mixing sync/async resolvers

- src/execution/__tests__/executor-test.ts
- src/execution/execute.ts
Fixes #3528 in the `16.x.x` branch.
> Fix crash in node when mixing sync/async resolvers (backport of #3706)

- resources/utils.ts
Context: broke changelog generation in case of empty list since it returned `['']` instead of `[]`
> resources/utils: fix `git().revList`

- .github/workflows/github-actions-bot.yml
sub-workflows cannot be called from parent workflow without sufficient permissions
> fix(github-actions-bot): add additional permissions

- src/execution/__tests__/stream-test.ts
- src/execution/execute.ts
extracted from #3754 
This is actually more than a simple refactoring, as it includes a bug fix.
When a non-null list is streamed and completeValue for a list item fails, the error should bubble up to the list itself and no further payloads should be sent.
Previously, this was case only when the field resolver for the list returned an iterable, but not when it returned an async iterable. In the latter case, the null correctly bubbles to the list itself for the given payload (`items: null` rather than `items: [null`), but further payloads would still be sent. This PR aligns async iterables to the behavior of iterables where further payloads will not be sent.
> fix(incrementalDelivery): fix null bubbling with async iterables

- .eslintrc.yml
Motivation: it useful to have rules in this order to make it easier to add new ESLint rules and also inspect docs of existing rules
> eslintrc: reorder rules to match order in the official docs

- README.md
I don't think we need any additional instructions since now the code is on main and published under the main alpha tag?
> Remove outdated instructions on experimental tag

- src/utilities/__tests__/extendSchema-test.ts
- src/utilities/extendSchema.ts
👋 
Closes https://github.com/graphql/graphql-js/issues/3629
When calling `extendSchema(schema, schemaModification)`, extended schema description is calculated as `schemaDef?.description?.value`, where
* `schemaDef` is a _nullable_ schema definition, that will not be null only if `schemaModification` declares the `type schema` (it happens only when we call `buildSchema` _or_ call `extendSchema(schema, 'extend type __Schema { ... }')`)
* `schemaDef?.description` is not undefined only when `extendSchema` is called from `buildSchema`, otherwise it's undefined because we don't allow a construction like:
```
"my awesome description" // error - graphql-js doesn't allow you to set the description when you extend schema
extend type __Schema { ... }
```
As a result, every `extendSchema` call …
> extendSchema: preserve "description" and "extensions"

- .github/workflows/ci.yml
- .github/workflows/cmd-publish-pr-on-npm.yml
- .github/workflows/cmd-run-benchmark.yml
- .github/workflows/deploy-artifact-as-branch.yml
- .github/workflows/github-actions-bot.yml
- .github/workflows/mutation-testing.yml
- .github/workflows/pull_request.yml
- .github/workflows/pull_request_opened.yml
- .github/workflows/push.yml
Context: #3751 added permissions to workflows.
It broke some of the workflows and was partially fixed in #3759 
This PR attempt to fix the rest of the workflows and also clean up permissions in general. 
Assigning granular permissions is error-prone, especially if we need to account for top-level workflow permissions. 
This PR attempt to solve this by explicitly listing permissions on each individual job. 
It slightly increases verbosity for some workflows but is more maintainable by keeping permissions closer to the required steps.
> workflows: fix and cleanup permissions

- .github/workflows/ci.yml
- .github/workflows/pull_request.yml
see https://github.com/graphql/graphql-js/actions/runs/3688795010/workflow error:
> The workflow is not valid. .github/workflows/pull_request.yml (Line: 5, Col: 3): Error calling workflow 'graphql/graphql-js/.github/workflows/ci.yml@07f38221a71005a56927e4327c9d188c222403f7'. The nested job 'Run CodeQL security scan' is requesting 'security-events: write', but is only allowed 'security-events: none'.
> fix permissions for codeql-action

- src/execution/__tests__/stream-test.ts
- src/execution/execute.ts
If a field resolves asynchronously, then it will always complete asynchronously.
Adds additional test cases to complete code coverage.
> polish: do not repeat isPromise check

- src/execution/__tests__/nonnull-test.ts
- src/execution/__tests__/stream-test.ts
- src/execution/execute.ts
Promise resolution order changes in some instances, resulting in different orders for some errors within the errors array, as well as in different values of hasNext within incremental delivery payloads.
This PR introduces an async `completePromisedValue` helper function rather than using a promise chain (see below links).
https://github.com/tc39/proposal-faster-promise-adoption
https://github.com/tc39/ecma262/issues/2770
https://github.com/tc39/ecma262/pull/2772
https://github.com/tc39/ecma262/pull/1250
https://v8.dev/blog/fast-async
Depends on #3793
> enhancement: remove extra ticks

- src/execution/__tests__/defer-test.ts
- src/execution/__tests__/executor-test.ts
- src/execution/execute.ts
Currently, when the defer/stream directives are not present in the schema, defer/stream will not be triggered, and so the directives will be ignored even when used with the original function.
But -- if the directives are in the schema, the original functions will sometimes throw (if the first result from `execute` is synchronous), but sometimes return maps with errors (when the first result from `execute` is async or when any (sync or async) `subscribe` payload has incremental results.
This PR just aligns the behavior in terms of throwing or returning a map with errors. We really shouldn't return a map with errors after execution has begun.
I think another viable alternative that potentially makes more sense is to have the original `execute` and `subscribe` functions ignore the …
> original `execute` should throw if defer/stream directives are present

- src/execution/execute.ts
We could not demonstrate via actual benchmarking that the tick reduction from awaiting a promise prior to returning it translates into real-world performance gains. See #3796.
In any case, the promise must be awaited (irrespective of performance) to allow the catch block to handle rejection errors. Simply returning `completed` would result in test failures.
> polish: remove misleading comment

- src/execution/__tests__/stream-test.ts
expect.fail() was mistakenly introduced in #3760 under the assumption that expect.fail() will always cause the test to fail, and that `.next()` should be called at most once.
Actually, thought, expect.fail() just throws an error, `.next()` is called more than once, the error is produced and wrapped by GraphQL, but then, it is filtered, so the test passes.
Fortunately, that's actually the desired behavior! It's ok if the number of calls to next() is more than 1 (in our case it is 2). The exact number of calls to next() depends on the # of ticks that it takes for the deferred fragment to resolve, which should be as low as possible, but that is a separate objective (with other PRs in the mix already aimed at reducing).
So the test as written is intending to be overly strict, but is broken …
> polish: clarify filtering test semantics

- src/execution/__tests__/variables-test.ts
- src/execution/values.ts
Errors thrown in the `parseValue` function for custom scalars are not propagated correctly using the `originalError` variable of the GraphQLError on invalid input. As a result, error codes from the `extensions.code` are not propagated correctly.
The fix is simple: Replace `error.orginalError` with `error`, since `error.orginalError` does not exist yet.
see:
https://github.com/graphql/graphql-js/blob/8be83d8d528991aed04ca17434b7e26e56f649cf/src/execution/values.ts#L134
I have added test-cases to avoid this problem in the future.
> fix: invalid originalError propagation in custom scalars

- resources/build-docusaurus.ts
> internal: fix website build error

- src/__testUtils__/viralSDL.ts
- src/__testUtils__/viralSchema.ts
- src/utilities/__tests__/buildASTSchema-test.ts
- src/utilities/__tests__/printSchema-test.ts
- src/utilities/printSchema.ts
This PR implements the tests and fixes necessary for [Spec RFC #987](https://github.com/graphql/graphql-spec/pull/987).
This PR is made of three main commits:
1. Test printing a schema that has `Query`, `Mutation` and `Virus` types, but only supports `query` operations (via the `Query` type) and does _not_ support `mutation` operations.
2. Test parsing this same schema text, and assert that the schema does not have a mutation type.
3. Fix the printing of the schema.
The fourth commit addresses the following failing test that I didn't know what to do about:
https://github.com/graphql/graphql-js/blob/76e47fcd7d432f515d5bb99e95af1851148a0c54/src/utilities/__tests__/buildClientSchema-test.ts#L65-L81
I don't understand the reasoning behind this test. It seems to me that the schema output from …
>  Fix ambiguity around when schema definition may be omitted

- package-lock.json
- src/execution/__tests__/variables-test.ts
- src/execution/values.ts
This is the same fix for invalid error propagation on custom scalars, but now backported for 16.x.x
see:
https://github.com/graphql/graphql-js/pull/3837
> Fix/invalid error propagation custom scalars (backport for 16.x.x)

- integrationTests/node/index.cjs
- integrationTests/node/index.mjs
- resources/inline-invariant.ts
Current build script rewrites invariant to avoid function call if invariant true.
However, the rewriting should take into account the import name as rewritten (by TS?):
Current output for cjs is:
https://github.com/graphql/graphql-js/blob/ba59ddd4afbe1129616ddb1ccbc79d2cd8dbf615/execution/execute.js#L14
while the call is still:
https://github.com/graphql/graphql-js/blob/ba59ddd4afbe1129616ddb1ccbc79d2cd8dbf615/execution/execute.js#L723-L724
yielding an error of the sort: `invariant is not defined`
> internal: fix inlineInvariant for cjs builds that require filenames with explicit extensions

- .github/workflows/ci.yml
Context: it was disabled due to bug in docusaurus plugin which was fixed a long time ago.
> ci: uncomment package-lock.json check for unmet dependencies

- integrationTests/node/test.js
- src/__testUtils__/dedent.ts
- src/__testUtils__/inspectStr.ts
- src/language/blockString.ts
- src/language/printer.ts
- src/utilities/printSchema.ts
Motivation: since we droped support for node14 we can finally use this function.
> Use `replaceAll` instead of RegExp with global flag

- src/jsutils/formatList.ts
- src/language/__tests__/lexer-test.ts
- src/language/__tests__/visitor-test.ts
- src/language/visitor.ts
- src/utilities/TypeInfo.ts
- src/validation/rules/KnownDirectivesRule.ts
Motivation: since we droped support for node14 we can finally use this function.
> Use ES2021 `Array.at`

- src/utilities/__tests__/printSchema-test.ts
- src/utilities/printSchema.ts
Motivation: empty description is definetly a corner case but spec allow them so we should correctly print them
> printSchema: correctly print empty description

- src/language/printer.ts
- src/language/visitor.ts
Context: only nodes are mapped in reducer and leafs inside nodes stays as is.
> ASTReducer: correctly type scalar values

- src/type/definition.ts
Context: revert back to use bind since it way faster
Reverts: https://github.com/graphql/graphql-js/commit/ac7098505ac3f5485ad3ac79351f0e64175bde23#diff-abcb97c7918631025353ea7ae5c1913946f00eb9d5d7ea9fe6060b6cfd92d480L761
> GraphQLObjectType: partial revert of #3143, due to perf regression

- src/type/__tests__/definition-test.ts
- src/type/definition.ts
Context: Continuation of #3642
Some discussion here: https://github.com/graphql/graphql-js/pull/3642#issuecomment-1154255542
> GraphQLInputObjectType: remove check that duplicate TS types

- src/type/definition.ts
Motivation: simplifies a code a bit and also saves some memory (measurable in bencmark) because we don't lock entire config in memory
> GraphQL*Type: bind only single property instead of entire context

- src/execution/__tests__/abstract-test.ts
- src/type/definition.ts
Context: GraphQLInterfaceTypeConfig has template parameters but they are not infered by GraphQLInterfaceType. I noticed it while trying to type resolvers, please see changes in `abstract-test.ts`
> GraphQLInterface: add missing template parameters

- src/language/__tests__/printer-test.ts
- src/language/printer.ts
This builds upon #2797 to add multiline support for ObjectValues and ListValues.
Example:
```graphql
{
trip(
obj: {wheelchair: false, smallObj: {a: 1}, largeObj: {wheelchair: false, smallObj: {a: 1}, arriveBy: false, includePlannedCancellations: true, transitDistanceReluctance: 2000, anotherLongFieldName: "Lots and lots and lots and lots of text"}, arriveBy: false, includePlannedCancellations: true, transitDistanceReluctance: 2000, anotherLongFieldName: "Lots and lots and lots and lots of text"}
) {
dateTime
}
another(
list: [["small array", "small", "small"], ["Lots and lots and lots and lots of text", "Lots and lots and lots and lots of text", "Lots and lots and lots and lots of text"]]
) {
dateTime
}
}
```
is now
```graphql
{
trip(
obj: {
wheelchair: false,
smallObj: { a: 1 }, …
```
> Make print() break long List and Object Values over multiple line

- src/execution/__tests__/defer-test.ts
There were many fields added to the schema in defer-test to accommodate specific tests. This schema can be simplified and the individual tests can get the specific behavior needed by using common fields and passing in custom resolvers in the `rootValue`.
`stream-test` already follows this same pattern.
> simplify schema in defer tests

- src/index.ts
- src/utilities/index.ts
- src/utilities/printSchema.ts
GraphQL schemas can end up quite large. Sharding the schema into multiple files is supported by [clients like relay](https://github.com/facebook/relay/blob/main/compiler/crates/relay-compiler/src/config.rs#L966) to allow you to split a large schema into multiple smaller files. This can reduce merge conflicts, and make things easier on the file system, git's operations and your IDE's syntax highlighting.
This PR exports the `printDirective` function, which will allow you to write your own custom implementation of `printSchema` for your own sharding mechanism. `printType` is already exported
> Expose printDirective function to enable schema sharding

- .eslintrc.cjs
- integrationTests/webpack/test.js
- package-lock.json
- package.json
Motivation: 'node' is in unmaintained state for year but recently ESLint community started to maintain it's fork
> eslint: replace unmaintained 'node' plugin with it's fork

- src/execution/__tests__/defer-test.ts
> remove unnecessary duplicated fields from defer tests

- src/jsutils/instanceOf.ts
- Backports c51c89596f27fe7a8067528a091a53dc466c543b from #3501 (I tried cherry-picking but the object was inaccessible, I simply moved the changes)
- Closes #3758
> check "globalThis.process" before accessing it

- src/execution/__tests__/lists-test.ts
- src/execution/__tests__/stream-test.ts
- src/execution/execute.ts
Currently, they are presented as errors in the next pending item.
Of course, there may or not be a next pending item; there may not be a way to definitively know the reason for the error, such that the error is a function of a problem with the collection itself.
As discussed in a prior incremental delivery WG meeting, this must be changed for both the non-streaming and streaming cases; this PR makes the minor adjustments addressing both cases.
> asyncIterable: locate async iterator errors to the collection

- src/execution/__tests__/stream-test.ts
- src/execution/execute.ts
- src/jsutils/__tests__/promiseWithResolvers-test.ts
- src/jsutils/promiseWithResolvers.ts
Promise.withResolvers is currently a [stage 2 proposal for JS](https://github.com/tc39/proposal-promise-with-resolvers). This adds an equivalent jsutil to standardize usage.
> introduce promiseWithResolvers helper

- src/execution/IncrementalPublisher.ts
- src/execution/__tests__/stream-test.ts
- src/execution/execute.ts
extracted from #3886
depends on #3903
more refactors from the without-branching branch, a bit more fundamental than #3891
[set as patch release because it does have an observable effect on the number of payloads, see below]
= iterate only through completed items
= remove extra ticks by making the publisher manage changes to its state synchronously.
= use children array instead of promises to manage hierarchy
= have IncrementalPublisher instantiate new IncrementalDataRecords
= The new publisher sometimes cause an empty `{ hasNext: false }` to be emitted. In particular, because the publisher is faster than it was, it may emit a stream result before the stream's asynchronous iterator has completed.
= The new publisher may sometimes reduce the number of `{ hasNext: false }` records that are …
> introduce new IncrementalPublisher class

- src/jsutils/instanceOf.ts
Big shout out to @phryneas, who managed to reproduce this issue and come up with this fix.
Fixes: #3919 #3920 #3921
Context: #3887 changed code and introced optinal chaining. `globalThis.process?.env.NODE_ENV` is transpiled into
```
(_globalThis$process = globalThis.process) === null ||
_globalThis$process === void 0
? void 0
: _globalThis$process.env.NODE_ENV;
```
Bundlers incorrectly replace (probably RegExp) `process.env.NODE_ENV` with `"development"` resulting in:
```
(_globalThis$process = globalThis.process) === null ||
_globalThis$process === void 0
? void 0
: _globalThis$"development";
```
Technically it's not a graphql issue but an issue with bundler but since it caused so much pain in comutinity this is an attempt to fix it within our codebase.
> instanceOf: workaround bundler issue with `process.env`

- src/execution/IncrementalPublisher.ts
- src/execution/execute.ts
as memory then cannot be freed
This affects both the existing branching executor on main as well as the non-branching, deduplicated version in #3886
We want to ensure that after an incremental result is sent to the client, no subsequent results reference this result so that garbage collection can free the memory associated with the result.  To effect this, two changes are required:
1. Prior to this change, we performed filtering by modifying the children stored on a parent; now we add a flag on the filtered item itself, so that we no longer need a backreference from child to parent.
2. We no longer store a permanent reference on the ExecutionContext to the children of the initial result. Rather, we have the IncrementalPublisher provide a new InitialResultRecord that carries its own errors …
> incremental: subsequent result records should not store parent references

- website/docusaurus.config.cjs
If you go to https://graphql-js.org/docs/tutorials/authentication-and-express-middleware and click `Edit this page` you'll be taken to `https://github.com/graphql/graphql-js/edit/main/website/docs/docs/tutorials/authentication-and-express-middleware.md`.
Instead you should be taken to `https://github.com/graphql/graphql-js/edit/main/website/docs/tutorials/authentication-and-express-middleware.md` - the `docs/` in the edit URL is incorrect since Docusaurus already adds that for you.
> Fix edit URL in documentation

- src/utilities/__tests__/buildClientSchema-test.ts
- src/utilities/getIntrospectionQuery.ts
This PR adds support for introspecting four-fold nested lists, which in turn allows proper representation of GeoJSON multipolygons (https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.7).
Closes #2643
> Add support for fourfold nested lists in introspection

- src/utilities/__tests__/buildClientSchema-test.ts
- src/utilities/getIntrospectionQuery.ts
This PR adds support for introspecting four-fold nested lists, which in turn allows proper representation of GeoJSON multipolygons (https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.7).
See https://github.com/graphql/graphql-js/issues/2643
> Support fourfold nested lists

- website/docs/tutorials/index.md
- graphql need named parameters
- need JSON.stringify to log proper output
- fix json output
> Fix invalid sample code

- src/execution/IncrementalPublisher.ts
- src/execution/__tests__/defer-test.ts
- src/execution/__tests__/lists-test.ts
- src/execution/__tests__/nonnull-test.ts
- src/execution/__tests__/oneof-test.ts
- src/execution/__tests__/stream-test.ts
- src/execution/__tests__/subscribe-test.ts
- src/execution/execute.ts
- src/execution/index.ts
- src/graphql.ts
extracted from #3929
the publisher itself can determine whether to return a single result or the initial result + stream
the only desired change is to replace the following code block with the below:
[FROM:](https://github.com/graphql/graphql-js/blob/fae5da500bad94c39a7ecd77a4c4361b58d6d2da/src/execution/execute.ts#L293-L340)
```ts
const incrementalPublisher = exeContext.incrementalPublisher;
const initialResultRecord = incrementalPublisher.prepareInitialResultRecord();
try {
const result = executeOperation(exeContext, initialResultRecord);
if (isPromise(result)) {
return result.then(
(data) => {
const errors =
incrementalPublisher.getInitialErrors(initialResultRecord);
const initialResult = buildResponse(data, errors);
incrementalPublisher.publishInitial(initialResultRecord);
if …
```
> incremental publisher should handle all response building

- src/execution/__tests__/defer-test.ts
- src/execution/__tests__/stream-test.ts
to minimize later diffs, we can watch how the tests change, rather than simple introducing tons of new tests
depends on https://github.com/graphql/graphql-js/pull/3930
> add tests with regard to duplication

- src/execution/IncrementalPublisher.ts
- src/execution/__tests__/defer-test.ts
- src/execution/__tests__/mutations-test.ts
- src/execution/__tests__/stream-test.ts
- src/execution/collectFields.ts
- src/execution/execute.ts
- src/jsutils/getBySet.ts
- src/jsutils/isSameSet.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
This in the main PR implements the major ideas from the latest incremental delivery proposal, https://github.com/graphql/defer-stream-wg/discussions/69 which is centered around the idea of deduplication of execution and delivery.
This PR is part of the following stack:
#3886 = main PR (this PR!) switching to deduplication of execution/delivery
#3897 = adds pending
#3911 = adds helpers to resolvers to further delay execution of deferred fields or manage concurrency
#3895 = consolidates payloads
TODO:
[x] convert existing tests
[x] error handling
[x] filter late nulls correctly
[x] defer/streams interactions
[x] completed
[x] pending
[ ] ids and subpaths instead of paths
[ ] even more tests?
> RFC: incremental delivery: without branching, with deduplication

- src/execution/IncrementalPublisher.ts
- src/execution/__tests__/defer-test.ts
- src/execution/__tests__/mutations-test.ts
- src/execution/__tests__/stream-test.ts
> incremental delivery: add pending notifications

- src/execution/IncrementalPublisher.ts
- src/execution/__tests__/defer-test.ts
- src/execution/__tests__/mutations-test.ts
- src/execution/__tests__/stream-test.ts
to match new format at https://github.com/graphql/defer-stream-wg/discussions/69
> incremental: utilize `id` and `subPath` rather than `path` and `label`

- src/execution/IncrementalPublisher.ts
We can use a non-null assertion to access `items ` on the completed StreamItemsRecord, similar to how `data` is accessed with a non-null assertion for completed DeferredGroupedFieldSet records, avoiding initialization of empty arrays/objects simply to avoid type errors.
> skip unnecessary initialization of empty items array

- src/type/directives.ts
- src/utilities/__tests__/printSchema-test.ts
Follow up from https://github.com/graphql/graphql-js/pull/3513.
I think it is fine for the spec text in https://github.com/graphql/graphql-spec/pull/825 to refer to `OneOf Input Object`, as the spec explains what that is in another section. In a directive definition, that explanation by itself does not make much sense without prior knowledge.
Channeling the RFC champion @benjie.
> Improve description for `@oneOf` directive

- package.json
- resources/utils.ts
- use url.fileURLToPath instead of URL.pathname
- use double quote instead on single quote for shell command
> fix for development on Windows

- benchmark/repeated-fields-benchmark.js
- src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
Applies fixes from https://github.com/graphql/graphql-js/pull/3958 into 16.x.x, fewer changes as no stream support in 16.
> OverlappingFieldsCanBeMergedRule: Fix performance degradation

- .eslintrc.cjs
- src/__testUtils__/kitchenSinkQuery.ts
- src/execution/__tests__/defer-test.ts
- src/execution/__tests__/stream-test.ts
- src/utilities/__tests__/printSchema-test.ts
Motivation: creates noise in PRs. Example:
https://github.com/graphql/graphql-js/pull/3969/files#diff-aae429dd10be4b186d38688c851313bf9dd9acb66700e9adc9984aa5162ec723R683
> tests: remove empty strings in string literals

- src/execution/IncrementalPublisher.ts
- src/execution/__tests__/defer-test.ts
- src/execution/__tests__/stream-test.ts
i.e. no fields and no enclosed deferred fragments
These fragments can be thought of to be completely skipped, because including them will just result in emitting metadata but no actual data. Alternatively, these fragments can be thought of as being inlined.
This could probably be considered a bug fix, in that Example F @ https://github.com/graphql/defer-stream-wg/discussions/69 explicitly states that these fragments should be skipped.
> fix: suppress records for deferred fragments that are completely empty

- src/execution/IncrementalPublisher.ts
current loop assumes that the first analyzed DeferredFragmentRecord has been released as pending and thereofre has an `id`, which happens to be the case in this scenario, but is not reliable, uncovered by #3982.
Demonstrates the peril of `!` which might point to requiring additional types, but we can leave that for a different PR.
> fix(incremental): fix logic around selecting id/subPath

- src/utilities/__tests__/printSchema-test.ts
- src/utilities/printSchema.ts
> Add support for @oneOf directives in printSchema

- src/execution/IncrementalPublisher.ts
- src/execution/buildFieldPlan.ts
- src/execution/collectFields.ts
- src/execution/execute.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
minimizes changes to CollectFields a la #3982 but still creates a single memoized incremental field plan per list item.
@robrichard
> simplify CollectFields for `@defer` and `@stream`

- .github/CONTRIBUTING.md
In GraphQL.js working group we discussed and put process in place. But we never officially wrote down in docs. You can watch this recording https://youtu.be/BBxc_HmB71I?si=cvdUMI47vBsT9F2y&t=1316 or check the transcript. These are the changes we agreed in the working group, just putting them in writing.
> docs: reviewer and merge process

- src/execution/IncrementalPublisher.ts
- src/execution/__tests__/defer-test.ts
The publish method checks to see if a subsequent result is empty; this same logic should be employed to suppress pending notices for empty records.
This has already been achieved for subsequent results that are children of the initial result, as we generated the pending notices from the list of initially published records.
For subsequent results that are children of other subsequent results, we previously generated the pending notice prior to actually publishing.
This change integrates the logic: the publishing method itself returns a pending notice as required. This results in a bug-fix for subsequent records of other subsequent records as well as a reduction of code for subsequent results to the initial result.
> fix(incremental): skip all empty subsequent results

- src/execution/__tests__/defer-test.ts
- src/execution/buildFieldPlan.ts
- src/execution/collectFields.ts
- src/execution/execute.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
Implements Option A from https://github.com/graphql/defer-stream-wg/discussions/80
> allow nested defers at the same level

- resources/utils.ts
see: https://github.com/nodejs/node/issues/3675
and in particular: https://github.com/nodejs/node/issues/3675#issuecomment-308963807
> fix(benchmark): select npm.cmd on windows

- resources/benchmark.ts
changed in v8 11.3 / node 20
see: https://chromium.googlesource.com/v8/v8/+/73c45833472086ca1c6ab4140cdb058d1890e930%5E%21/src/flags/flag-definitions.h
fixes benchmarking, see https://github.com/graphql/graphql-js/actions/runs/8314729475/job/22752257524#step:6:142
> benchmark: update v8 flag

- src/execution/execute.ts
inline much of the original executeOperation
leave out executeRootGroupedFieldSet, will help reduce the diff for #4026
> rename executeImpl to executeOperation

- src/validation/__tests__/DeferStreamDirectiveOnValidOperationsRule-test.ts
- src/validation/rules/DeferStreamDirectiveOnValidOperationsRule.ts
Fixes the error message created by the DeferStreamDirectiveOnValidOperationsRule for the stream directive.
> Fix stream directive validation error message

- src/execution/buildFieldPlan.ts
- src/execution/collectFields.ts
- src/execution/execute.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
in the non-deferred case.
depends on #4026
> perf: allow skipping of field plan generation

- src/execution/execute.ts
> perf: introduce completePromisedListItemValue 

- src/execution/execute.ts
refactoring that will streamline when we introduce two versions of this function to optimize the loop when not streaming
depends on #4051
> refactor: introduce completeIterableValue

- src/execution/IncrementalPublisher.ts
- src/execution/execute.ts
As convention, we will lazily instantiate arrays/sets when adding the first item.
This applies to arrays/sets on execution/incremental context, as well as the second member of the GraphQLWrappedResult tuple holding the array of incremental data records.
> perf: use undefined for empty

- src/execution/__tests__/defer-test.ts
Group field sets should be properly consolidated when some of the fields in a sibling defer are masked by parent fields.
> Add test for consolidating grouped field sets properly into deferred fragments

- cspell.yml
- src/jsutils/instanceOf.ts
- website/docs/tutorials/going-to-production.md
- website/sidebars.js
As surfaced in [Discord](https://discord.com/channels/625400653321076807/862957336082645006/1206980831915282532) this currently is a breaking change in the 16.x.x release line which is preventing folks from upgrading towards a security fix. This PR should result in a patch release on the 16 release line.
This change was originally introduced to support CFW and browser environments which should still be supported with the `typeof` check CC @n1ru4l
This also adds a check whether `.env` is present as in the DOM using `id="process"` defines that as a global which we don't want to access on accident. as shown in https://github.com/graphql/graphql-js/pull/4017
Bundles also target `process.env.NODE_ENV` specifically which fails when it replaces `globalThis.process.env.NODE_ENV` as this becomes …
> fix: remove `globalThis` check and align with what bundlers can accept

- src/execution/IncrementalGraph.ts
- src/execution/IncrementalPublisher.ts
- src/execution/__tests__/defer-test.ts
- src/execution/__tests__/stream-test.ts
- src/execution/execute.ts
- src/execution/types.ts
- src/jsutils/BoxedPromiseOrValue.ts
- src/jsutils/__tests__/BoxedPromiseOrValue-test.ts
A Graph object exposes an iterator for the completed incremental data such that the Incremental Publisher can properly be conceptualized as an operator on a stream, similar to the spec changes.
depends on #4099
> incremental: introduce IncrementalGraph class to manage tree of subsequent results

- package.json
- resources/checkgit.sh
The publish scripts require the shell to be `bash`, which despite being the shell I use is not the one that `npm version` seems to use currently. Fixed by forcing the script to run through `bash -c`
This will NOT work on Windows. Probably it already didn't.
> Fix publish scripts

- .github/CONTRIBUTING.md
`npm publish npmDist` fails:
```
$ npm publish npmDist                  
npm ERR! code E404                                                            
npm ERR! 404 Not Found - GET https://registry.npmjs.org/npmDist - Not found                                                                                                                    
npm ERR! 404                                                                  
npm ERR! 404  'npmDist@*' is not in this registry.                            
npm ERR! 404 This package name is not valid, because                                                                                                                                           
npm ERR! 404  1. name can no longer contain capital letters                   
npm ERR! 404 …
```
> Update release instructions in CONTRIBUTING.md

- src/execution/IncrementalGraph.ts
- src/execution/__tests__/stream-test.ts
- src/execution/execute.ts
- src/execution/types.ts
The incremental graph can handle a stream as a stream, rather than creating a linked list where each incremental data record also includes the next record in addition to any new defers and/or streams.
Enables easily batching all available stream items within the same incremental entry.
Depends on #4094
> incremental: handle Stream as stream rather than linked list

- src/execution/IncrementalPublisher.ts
polished IncrementalPublisher:
= completeDeferredFragment will always return undefined if the deferredFragmentRecord has already been removed from the graph
= removeDeferredFragment need not be called twice
> polish(IncrementalPublisher): remove unnecessary check and method call

- src/type/__tests__/enumType-test.ts
- src/type/definition.ts
Many of the type configuration objects in GraphQL-js have properties that accept thunks:
- GraphQLObjectTypeConfig.fields
- GraphQLObjectTypeConfig.interfaces
- GraphQLInterfaceTypeConfig.fields
- GraphQLInterfaceTypeConfig.interfaces
- GraphQLInputObjectTypeConfig.fields
- GraphQLUnionTypeConfig.types
These are because their definitions may contain references to other types which may form cycles, and thus a thunk is required to enable their definition.
This PR allows setting `GraphQLEnumTypeConfig.values` to be a thunk. At first, this might seem unnecessary (and, well, it has been this way for 9 years so you can be forgiven for thinking that) but it can be quite useful when building enums that reference types. For example: you might have a field that returns a union (`Person.pets`), and …
> Enable passing values configuration to GraphQLEnumType as a thunk

- src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.js
- src/validation/rules/OverlappingFieldsCanBeMergedRule.js
Backports the fix from https://github.com/graphql/graphql-js/pull/3442 into the v15.x tree.
> Backport "Prevent Infinite Loop in OverlappingFieldsCanBeMergedRule" to v15

- src/error/GraphQLError.ts
Using symbol keys is a useful approach when composing error handlers as symbol keys are omitted when the error is finally stringified.
It allows middlewares to read extensions without having to assign them to `undefined` afterwards or using the `delete` keyword.
> feat: allow defining symbol error extensions

- src/utilities/__tests__/buildClientSchema-test.ts
- src/utilities/__tests__/getIntrospectionQuery-test.ts
- src/utilities/buildClientSchema.ts
- src/utilities/getIntrospectionQuery.ts
- src/utilities/introspectionFromSchema.ts
> Add `@oneOf` support to introspection query

- src/__testUtils__/kitchenSinkSDL.ts
- src/execution/__tests__/oneof-test.ts
- src/index.ts
- src/language/__tests__/schema-printer-test.ts
- src/type/__tests__/introspection-test.ts
- src/type/__tests__/validation-test.ts
- src/type/definition.ts
- src/type/directives.ts
- src/type/index.ts
- src/type/introspection.ts
- src/type/validate.ts
- src/utilities/__tests__/buildASTSchema-test.ts
- src/utilities/__tests__/buildClientSchema-test.ts
- src/utilities/__tests__/coerceInputValue-test.ts
- src/utilities/__tests__/findBreakingChanges-test.ts
- src/utilities/__tests__/getIntrospectionQuery-test.ts
- src/utilities/__tests__/printSchema-test.ts
- src/utilities/__tests__/valueFromAST-test.ts
- src/utilities/buildClientSchema.ts
- src/utilities/coerceInputValue.ts
- src/utilities/extendSchema.ts
- src/utilities/getIntrospectionQuery.ts
- src/utilities/introspectionFromSchema.ts
- src/utilities/printSchema.ts
- src/utilities/valueFromAST.ts
- src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
- src/validation/__tests__/harness.ts
- src/validation/rules/ValuesOfCorrectTypeRule.ts
See:
- #3513
- #3937 
- #3969
- #4078
Relates to the oneOf RFC: https://github.com/graphql/graphql-spec/pull/825
> backport[v16]: Implement OneOf Input Objects via `@oneOf` directive

- src/type/__tests__/enumType-test.ts
- src/type/definition.ts
> backport[v16]: Enable passing values configuration to GraphQLEnumType as a thunk

- src/utilities/__tests__/getIntrospectionQuery-test.ts
- src/utilities/getIntrospectionQuery.ts
- src/utilities/introspectionFromSchema.ts
The setting controls whether or not `isOneOf` is added to a selection on `__Type`; if we were to extend oneOf to output object too, the same setting could control it. Therefore, a simpler configuration variable makes sense.
> Rename `inputObjectOneOf` to `oneOf` in `getIntrospectionQuery()`

- src/execution/IncrementalGraph.ts
- src/execution/IncrementalPublisher.ts
return newPending alongside incremental results when completing a fragment
= removes need to track `newPending` and `newIncrementalDataRecords` as part of the class
= unifies handling of retrieving new pending for initial result, completed fragments, and stream items incremental entries
> polish(incremental): refactor getNewPending functionality

- src/execution/IncrementalGraph.ts
- src/execution/execute.ts
- src/execution/types.ts
> refactor(incremental): simplify incremental graph by allowing mutations

- .github/workflows/ci.yml
- .github/workflows/pull_request.yml
- .github/workflows/push.yml
Merged #4138 too early; this actually fixes codecov.
> Fix codecov workflow

- src/execution/__tests__/lists-test.ts
- src/execution/execute.ts
> return async iterables in the non incremental delivery case

- src/execution/IncrementalGraph.ts
- src/execution/__tests__/defer-test.ts
- src/execution/execute.ts
- src/execution/types.ts
Currently, when early execution is disabled, we still use the early execution logic to initiate execution groups, which may cause early initiation of non-pending execution groups.
alternative to #4109, causes potentially stacking delays when combinations of shared and non-shared keys between sibling defers cause separate deferred grouped field sets for the same deferred fragment.
> fix(incremental): do not initiate non-pending execution groups

- src/execution/IncrementalGraph.ts
- src/execution/IncrementalPublisher.ts
- src/execution/buildExecutionPlan.ts
- src/execution/execute.ts
- src/execution/types.ts
DeferredGroupedFieldSet => ExecutionGroup
SubsequentResultRecord => DeliveryGroup
ExecuteExecutionGroups => CollectExecutionGroups
> polish(incremental): rename terms to match spec

- src/execution/__tests__/union-interface-test.ts
- src/execution/execute.ts
Currently it is possible to have unhandled promise rejections that arise from a mix of sync and async isTypeOf checks.
This should fix that issue.
> fix: improve handling of promises in defaultTypeResolver

- src/execution/IncrementalGraph.ts
- src/execution/types.ts
-- remove unnecessary helpers
-- use more object destructuring
-- fix one obsolete reference
> incremental: minor polishes around readability

- src/execution/execute.ts
Previously, this was inlined into both executeOperation and collectAndExecuteSubfields, now it is a separate function.
executeExecutionPlan calls "getNewDeferMap" instead of "addNewDeferredFragments" to also conform to the spec functional/immutable style.
> polish: introduce executeExecutionPlan to conform to spec algo

- src/execution/__tests__/variables-test.ts
- src/execution/execute.ts
- src/execution/values.ts
- src/type/__tests__/introspection-test.ts
- src/type/__tests__/validation-test.ts
- src/type/validate.ts
- src/utilities/__tests__/coerceInputValue-test.ts
- src/utilities/__tests__/findBreakingChanges-test.ts
- src/utilities/coerceInputValue.ts
- src/utilities/findBreakingChanges.ts
- src/utilities/printSchema.ts
- src/validation/__tests__/DeferStreamDirectiveLabelRule-test.ts
- src/validation/__tests__/NoDeprecatedCustomRule-test.ts
- src/validation/__tests__/ProvidedRequiredArgumentsRule-test.ts
- src/validation/__tests__/StreamDirectiveOnListFieldRule-test.ts
- src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
- src/validation/rules/DeferStreamDirectiveLabelRule.ts
- src/validation/rules/DeferStreamDirectiveOnRootFieldRule.ts
- src/validation/rules/FieldsOnCorrectTypeRule.ts
- src/validation/rules/KnownArgumentNamesRule.ts
- src/validation/rules/ProvidedRequiredArgumentsRule.ts
- src/validation/rules/StreamDirectiveOnListFieldRule.ts
- src/validation/rules/ValuesOfCorrectTypeRule.ts
- src/validation/rules/custom/NoDeprecatedCustomRule.ts
extracted from #3808
PR #3808 uses schema coordinates to improve GraphQL-JS error messages. To reduce the size of the PR, this commit standardizes error messages according to the general pattern that will be introduced with schema coordinates without introducing the coordinates themselves, in the hopes of aiding review of the later PR.
EDITED 8/26/2024:
I was able to reproduce all of the standardized error messages from #3808 except for the ones in getArgumentValues when it is passed a Field Definition, because the parent type is not passed. Everything else can be calculated for the error messages we are currently printing, although schema coordinates simplifies things.
Extracting these changes out of #3808 and rebasing #3808 on main will therefore will better demonstrate how schema …
> standardize error messages prior to introducing schema coordinates

- README.md
- cspell.yml
- src/jsutils/instanceOf.ts
- src/language/ast.ts
- src/language/directiveLocation.ts
- src/language/kinds.ts
- src/language/tokenKind.ts
- src/type/introspection.ts
- src/utilities/findBreakingChanges.ts
- website/docs/tutorials/going-to-production.md
- website/sidebars.cjs
@JoviDeCroock @robrichard @benjie 
In this PR, the outstanding v16.x.x changes highlighted by the work in #4165 have been cherry-picked and include the following PRs:
#3686 [Workaround for codesandbox having bug with TS enums](https://github.com/graphql/graphql-js/pull/3686)
#3923 [instanceOf: workaround bundler issue with process.env #3923](https://github.com/graphql/graphql-js/pull/3923)
#4157 [Add GraphQLConf 2024 banner #4157](https://github.com/graphql/graphql-js/pull/4157)
Why were these 3 PRs not developed on main like all the authors? Well, for the first two, it was thought at the time of the original work that a different strategy would be pursued in v17. See the individual links for more information, but, in short, for #3686 it was thought that in v17 TS enums would be entirely …
> chore: update main with outstanding fixes on v16.x.x branch

- src/execution/__tests__/variables-test.ts
- src/execution/collectFields.ts
fixes up just merged #4015
this was actually intended to be in #4015, but due to branch confusion not originally included
now we also have a test!
> fix(fragmentArguments): arguments on directives for nested fields

- .github/workflows/ci.yml
- .github/workflows/cmd-publish-pr-on-npm.yml
- .github/workflows/cmd-run-benchmark.yml
- .github/workflows/deploy-artifact-as-branch.yml
- .github/workflows/github-actions-bot.yml
- .github/workflows/pull_request.yml
- .github/workflows/pull_request_opened.yml
In response to some of our actions starting to fail deprecate all of the actions that don't work anymore due to using Node 10/12
- [Looks like upload artefact is safe to upgrade](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) we don't seem to overwrite files
- [Same for download](https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md)
> Upgrade deprecated actions

- src/execution/getVariableSignature.ts
- src/execution/values.ts
- src/index.ts
- src/language/parser.ts
- src/utilities/__tests__/coerceInputValue-test.ts
- src/utilities/__tests__/valueFromAST-test.ts
- src/utilities/buildClientSchema.ts
- src/utilities/coerceInputValue.ts
- src/utilities/extendSchema.ts
- src/utilities/index.ts
- src/utilities/valueFromAST.ts
- src/utilities/valueFromASTUntyped.ts
[#3092 rebased on main](https://github.com/graphql/graphql-js/pull/3092).
~~Depends on #3808~~
@leebyron comments from original PR:
> Removes `valueFromAST()` and adds `coerceInputLiteral()` as an additional export from `coerceInputValue`.
> 
> The implementation is almost exactly the same as `valueFromAST()` with a slightly more strict type signature and refactored tests to improve coverage (the file unit test has 100% coverage)
> 
> While this does not change any behavior, it could be breaking if you rely directly on the `valueFromAST()` method. Use `coerceInputLiteral()` as a direct replacement.
Changes from the original:
1. Deprecation rather than removal of `valueFromAST()`.
2. `coerceInputLiteral()` and only `coerceInputLiteral()` supports fragment variables in addition to operation …
> Add coerceInputLiteral()

- src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.ts
- src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
In trying to prevent infinite loops, https://github.com/graphql/graphql-js/pull/3442 introduced a bug that causes certain violations of the [Field Selection Merging](https://spec.graphql.org/draft/#sec-Field-Selection-Merging) validation to not be caught (released in `16.3.0`, and backported to `15.9.0`). This PR fixes this bug, while continuing to prevent infinite loops.
Specifically, the code introduced in that PR misuses `comparedFragmentPairs` in the `collectConflictsBetweenFieldsAndFragment()` function. That function takes in fields/a selection set and checks whether it conflicts with the given fragment, while recursively checking those fields against nested fragments in the given fragment. The `comparedFragmentPairs` data structure is meant to store whether fragments have been …
> fix(validation): catch OverlappingFieldsCanBeMergedRule violations with nested fragments

- src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.ts
- src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
Port of #4168 by @sachindshinde to v17
> fix(validation): catch OverlappingFieldsCanBeMergedRule violations with nested fragments (#4168)

- src/execution/getVariableSignature.ts
- src/execution/values.ts
- src/index.ts
- src/type/__tests__/definition-test.ts
- src/type/__tests__/predicate-test.ts
- src/type/definition.ts
- src/type/index.ts
- src/type/introspection.ts
- src/utilities/TypeInfo.ts
- src/utilities/__tests__/buildClientSchema-test.ts
- src/utilities/__tests__/coerceInputValue-test.ts
- src/utilities/buildClientSchema.ts
- src/utilities/coerceInputValue.ts
- src/utilities/extendSchema.ts
- src/utilities/findBreakingChanges.ts
- src/utilities/printSchema.ts
- src/utilities/valueFromAST.ts
- src/validation/ValidationContext.ts
- src/validation/rules/VariablesInAllowedPositionRule.ts
[#3074 rebased on main](https://github.com/graphql/graphql-js/pull/3074).
Depends on #3809
@leebyron comments from original PR (edited, hopefully correctly):
> Fixes #3051
> 
> This change solves the problem of default values defined via SDL not always resolving correctly through introspection by preserving the original GraphQL literal in the schema definition. This changes argument and input field definitions `defaultValue` field from just the "value" to a new `GraphQLDefaultValueUsage` type which contains either (EDIT: but not both!) "value" and "literal" fields.
> 
> Here is the flow for how a default value defined in an SDL would be converted into a functional schema and back to an SDL:
> 
> **Before this change:**
> 
> ```
> (SDL) --parse-> (AST) --coerceInputLiteral--> (defaultValue …
```
> Preserve defaultValue literals

- src/validation/__tests__/KnownDirectivesRule-test.ts
Improving directive tests by adding a new example for directives used on other directive arguments:
```graphql
directive @myDirective(arg:String) on ARGUMENT_DEFINITION 
directive @myDirective2(arg:String @myDirective) on FIELD 
```
As far as I could see that was not clearly documented through tests before.
> Improve directive tests

- src/validation/__tests__/KnownDirectivesRule-test.ts
This was my mistake, git can help GitHub merge even old PRs automatically when there are no conflicts, but it does not rerun checks/actions if they have changed.
Not sure if there is a separate flow to ensure that the checks are up to date, worth investigating.
> fix: lint errors from PR prior to latest checks

- src/execution/__tests__/executor-test.ts
- src/execution/collectFields.ts
- src/execution/execute.ts
- src/execution/values.ts
- src/type/definition.ts
- src/utilities/__tests__/coerceInputValue-test.ts
- src/utilities/coerceInputValue.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
[#3077 rebased on main](https://github.com/graphql/graphql-js/pull/3077).
Depends on #3810
@leebyron comments from original PR:
> By way of introducing type `VariableValues`, allows `getVariableValues` to return both the coerced values as well as the original sources, which are then made available in `ExecutionContext`.
> 
> While variable sources are not used directly here, they're used directly in #3065. This PR is pulled out as a pre-req to aid review
> Preserve sources of variable values

- integrationTests/ts/kitchenSink-test.ts
- src/execution/__tests__/variables-test.ts
- src/index.ts
- src/type/__tests__/definition-test.ts
- src/type/__tests__/scalars-test.ts
- src/type/definition.ts
- src/type/scalars.ts
- src/utilities/__tests__/coerceInputValue-test.ts
- src/utilities/__tests__/replaceVariables-test.ts
- src/utilities/__tests__/valueToLiteral-test.ts
- src/utilities/coerceInputValue.ts
- src/utilities/index.ts
- src/utilities/replaceVariables.ts
- src/utilities/valueToLiteral.ts
- src/validation/rules/ValuesOfCorrectTypeRule.ts
[#3065 rebased on main](https://github.com/graphql/graphql-js/pull/3065).
Depends on #3811
@leebyron comments from original PR:
> **Provides the "Value to Literal" methods in this [data flow chart](https://user-images.githubusercontent.com/50130/118379946-51ac5300-b593-11eb-839f-c483ecfbc875.png).**
> 
> * Adds `valueToLiteral()` which takes an external input value and translates it to a literal, allowing for custom scalars to define this behavior.
> 
> **This also adds important changes to Input Coercion, especially for custom scalars:**
> 
> * The value provided to `parseLiteral` is now `ConstValueNode` and the second `variables` argument has been removed. For all built-in scalars this has no effect, but any custom scalars which use complex literals no longer need to do variable …
> Add valueToLiteral()

- src/type/__tests__/definition-test.ts
- src/type/__tests__/scalars-test.ts
- src/type/definition.ts
- src/utilities/coerceInputValue.ts
- src/validation/rules/ValuesOfCorrectTypeRule.ts
`parseLiteral()` has been marked as deprecated, prompting but not forcing our users to convert to `parseConstLiteral()`.
With this additional change:
- in v17, if not supplied, the new `parseConstLiteral()` method will be left as undefined, and during execution, we will fall back to`parseLiteral()`.
- in v18, we will remove `parseLiteral()` and set up a default function for `parseConstLiteral()` when not supplied.
Prior to this change, users of custom scalars with custom `parseLiteral()` functions who did not provide a custom `parseConstLiteral()` function would just get the default `parseConstLiteral()` function during execution, which might not work as expected.
This scheme will work except for users of custom scalars who want to embed experimental fragment variables in their custom …
> improve upgrade path for new custom scalar `parseConstLiteral()` method

- src/execution/execute.ts
- src/execution/index.ts
- src/index.ts
to safely export buildExecutionContext() as validateExecutionArgs()
motivation: this will allow us to:
1. export `executeOperation()` and `executeSubscription()` for those who would like to use directly.
2. add a `perEventExecutor` option to `ExecutionArgs` that allows one to pass a custom context for execution of each execution event, with the opportunity to clean up the context on return, a la #2485 and #3071, addressing #894, which would not require re-coercion of variables.
The signature of the `perEventExecutor` option would be:
```ts
type SubscriptionEventExecutor = ( validatedExecutionArgs: ValidatedExecutionArgs): PromiseOrValue<ExecutionResult>
```
rather than:
```ts
type SubscriptionEventExecutor = ( executionArgs: ExecutionArgs): PromiseOrValue<ExecutionResult>
```
This might …
> introduce ValidatedExecutionArgs

- src/execution/__tests__/subscribe-test.ts
- src/execution/execute.ts
- src/execution/index.ts
- src/index.ts
by exporting executeSubscriptionEvent()
and adding option for to provide a custom fn
addresses #894
cf. #2485 , #3071
> add ability to use perEventExecutor

- src/execution/execute.ts
- src/utilities/replaceVariables.ts
These can be merged separately with the "Rebase" strategy to get separate commits for use with `git bisect`.
`buildResolveInfo()` was deoptimized within https://github.com/graphql/graphql-js/pull/4015.
`replaceVariables()` was never optimized, uses less memory with simple function rather than visitor.
> perf: optimizations for buildResolveInfo() and replaceVariables()

- src/execution/buildExecutionPlan.ts
- src/execution/collectFields.ts
- src/execution/execute.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
to match proposed spec edits for defer/stream
https://github.com/graphql/graphql-spec/pull/1110
> rename FieldGroup type to FieldDetailsList

- src/execution/execute.ts
- src/execution/index.ts
- src/index.ts
operating on `ValidatedExecutionArguments`:
`executeQueryOrMutationOrSubscriptionEvent()` and
`experimentalExecuteQueryOrMutationOrSubscriptionEvent()`
motivation: allows library users/servers to make sure that documents contain necessary operation and that variables coerce, and then allow them to call an executor on those already validated arguments
motivation: missing piece necessary for really closing #3679
> introduce new execute exports

- .husky/pre-commit
- .lintstagedrc.json
- package-lock.json
- package.json
Personally have been really annoyed with the lack of pre-commit in this repository, I have to commit twice every time as I'm not used to manually calling `npm run lint && npm run format`
> chore(workspace): lint and format on commit

- src/type/__tests__/introspection-test.ts
- src/utilities/__tests__/buildClientSchema-test.ts
- src/utilities/getIntrospectionQuery.ts
Supersedes https://github.com/graphql/graphql-js/pull/3910
Fixes https://github.com/graphql/graphql-js/issues/3909
Fixes https://github.com/graphql/graphql-js/issues/3409
This puts the Selection-set in line with the expected type
> Include kind in the types

- src/type/__tests__/definition-test.ts
would address #1679 
I think a simpler version than #1683
> add toConfig tests

- src/execution/collectFields.ts
- src/execution/execute.ts
- src/execution/values.ts
- src/graphql.ts
- src/type/__tests__/enumType-test.ts
- src/type/definition.ts
- src/utilities/__tests__/coerceInputValue-test.ts
- src/utilities/coerceInputValue.ts
- src/utilities/valueFromAST.ts
- src/validation/ValidationContext.ts
- src/validation/__tests__/FieldsOnCorrectTypeRule-test.ts
- src/validation/__tests__/KnownArgumentNamesRule-test.ts
- src/validation/__tests__/KnownTypeNamesRule-test.ts
- src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
- src/validation/__tests__/harness.ts
- src/validation/rules/FieldsOnCorrectTypeRule.ts
- src/validation/rules/KnownArgumentNamesRule.ts
- src/validation/rules/KnownTypeNamesRule.ts
- src/validation/rules/PossibleTypeExtensionsRule.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
- src/validation/rules/ValuesOfCorrectTypeRule.ts
- src/validation/validate.ts
Resolves https://github.com/graphql/graphql-js/issues/4190
Resolves https://github.com/graphql/graphql-js/issues/2247
Supersedes https://github.com/graphql/graphql-js/pull/3467
This is a best practice already in production however GraphQL JS does not provide an out of the box solution. In the community we have solutions like https://escape.tech/graphql-armor/docs/plugins/block-field-suggestions/ however in v17 it would be worth considering providing a built-in.
The recommendation here would be to do `validate(schema, doc, rules, { hideSuggestions: process.env.NODE_ENV === 'production' })`
> feat: Allow skipping suggestions

- integrationTests/ts/kitchenSink-test.ts
- src/execution/__tests__/variables-test.ts
- src/index.ts
- src/type/__tests__/definition-test.ts
- src/type/__tests__/scalars-test.ts
- src/type/definition.ts
- src/type/index.ts
- src/type/scalars.ts
- src/utilities/__tests__/coerceInputValue-test.ts
- src/utilities/coerceInputValue.ts
- src/validation/rules/ValuesOfCorrectTypeRule.ts
the new method was introduced in #3812 with upgrade path improved in #4209.
This PR completes polishes this work a bit:
1. The method is renamed to `coerceInputLiteral()` following the naming convention suggested in #2357, with the other methods to be renamed in later PRs.
2. The type of the method `GraphQLScalarInputLiteralCoercer` is exported, which was not done in the initial work. The old `GraphQLScalarLiteralParser` type is deprecated.
> improve new leaf type `parseConstLiteral()` method

- src/type/definition.ts
Closes https://github.com/graphql/graphql-js/issues/3853
There's only one normalizedConfig we export and these are just the type config with a few extras. I would rather than exporting all of them just stop exporting them for the time being as we don't accept them as inputs and it can still be derived by doing `ReturnType<GraphQLInterfaceType['toConfig']>` if it's really needed
> Remove the normalized config export

- src/type/__tests__/introspection-test.ts
- src/utilities/__tests__/buildClientSchema-test.ts
- src/utilities/getIntrospectionQuery.ts
Backports #4222
Supersedes https://github.com/graphql/graphql-js/pull/3910
Fixes https://github.com/graphql/graphql-js/issues/3909
Fixes https://github.com/graphql/graphql-js/issues/3409
> Backport introspection type fix

- src/validation/__tests__/ScalarLeafsRule-test.ts
- src/validation/rules/ScalarLeafsRule.ts
Closes https://github.com/graphql/graphql-js/issues/3790
This follows the spec closer to the letter as we consider empty selection-sets invalid as well. This however does not cover empty operation-definitions, which should also be considered invalid.
The parser itself considers empty-selections invalid as it requires you to specify a name before a closing curly, hence why testing happens a bit more manual here. Despite our parser not considering this valid, I think this is good to validate when folks use a separate parser or construct documents manually as this is valid in our type-system.
> Cover empty field-selections

- resources/build-npm.ts
- tsconfig.json
Fixes https://github.com/graphql/graphql-js/issues/2470
> Add sourcemaps to our published bundles

- src/jsutils/ObjMap.ts
- src/jsutils/toObjMap.ts
- src/type/__tests__/definition-test.ts
- src/type/definition.ts
- src/type/directives.ts
- src/type/schema.ts
Supersedes https://github.com/graphql/graphql-js/pull/3511
This adds support for `Symbol` property keys on the extension property of AST nodes. Had to tweak `toObjMap` here to support symbol keys by adding `getOwnPropertySymbols` which is the only way to enumerate over them.
> Support symbol properties on extension objects

- src/validation/ValidationContext.ts
- src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
- src/validation/__tests__/VariablesInAllowedPositionRule-test.ts
- src/validation/rules/ValuesOfCorrectTypeRule.ts
- src/validation/rules/VariablesInAllowedPositionRule.ts
<hr>
This work was pulled out of the work rebasing the Default Value Coercion/Validation PR stack at #3814 on the OneOf and Experimental Fragment Variables changes.
In that PR stack (work originally done by @leebyron within #3049), Lee extracts the validation done by the `ValuesOfCorrectTypeRule` into a `validateInputLiteral()` utility that can be called at validation-time or at run-time. At validation time, `validateInputLiteral()` validates statically, is not supplied variables **or their types**, and does not validate variables, while at run-time it is supplied variables and does validate them.
<hr>
With OneOf Input Objects, we have a situation in which Input Objects will define technically nullable/optional input fields, but the addition of the `@oneOf` directive tells the …
> move variable position validation for OneOf to `VariablesInAllowedPositionRule`

- integrationTests/ts/kitchenSink-test.ts
- src/execution/__tests__/executor-test.ts
- src/execution/__tests__/variables-test.ts
- src/execution/execute.ts
- src/index.ts
- src/type/__tests__/definition-test.ts
- src/type/__tests__/scalars-test.ts
- src/type/definition.ts
- src/type/index.ts
- src/type/scalars.ts
- src/utilities/__tests__/astFromValue-test.ts
- src/utilities/__tests__/coerceInputValue-test.ts
- src/utilities/astFromValue.ts
- src/utilities/buildClientSchema.ts
- src/utilities/coerceInputValue.ts
- src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
finish addressing #2357, started in #4218
> rename serialize and parseValue methods

- src/type/__tests__/schema-test.ts
- src/type/schema.ts
closes https://github.com/graphql/graphql-js/issues/3448
> add permanent flag for schema configuration property assumeValid

- src/execution/__tests__/nonnull-test.ts
- src/execution/__tests__/oneof-test.ts
- src/execution/__tests__/subscribe-test.ts
- src/execution/__tests__/variables-test.ts
- src/execution/values.ts
- src/index.ts
- src/jsutils/printPathArray.ts
- src/type/__tests__/enumType-test.ts
- src/type/definition.ts
- src/utilities/__tests__/coerceInputValue-test.ts
- src/utilities/__tests__/validateInputValue-test.ts
- src/utilities/coerceInputValue.ts
- src/utilities/index.ts
- src/utilities/validateInputValue.ts
- src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
- src/validation/rules/ValuesOfCorrectTypeRule.ts
[#3086 rebased on main](https://github.com/graphql/graphql-js/pull/3086).
Depends on #3812 
@leebyron comments from original PR:
> Factors out input validation to reusable functions:
> 
> * Introduces `validateInputLiteral` by extracting this behavior from `ValuesOfCorrectTypeRule`.
> * Introduces `validateInputValue` by extracting this behavior from `coerceInputValue`
> * Simplifies `coerceInputValue` to return early on validation error
> * Unifies error reporting between `validateInputValue` and `validateInputLiteral`, causing some error message strings to change, but error data (eg locations) are preserved.
> 
> These two parallel functions will be used to validate default values
> 
> Potentially breaking if you rely on the existing behavior of `coerceInputValue` to call a callback …
> Input Value Validation

- src/index.ts
- src/utilities/__tests__/findBreakingChanges-test.ts
- src/utilities/__tests__/findSchemaChanges-test.ts
- src/utilities/findSchemaChanges.ts
- src/utilities/index.ts
Alternative to https://github.com/graphql/graphql-js/pull/2181
This adds a new `findSchemaChanges` export and deprecates the breaking and dangerous alternative to be removed in v18. While adding safe-schema-changes I noticed that we lack directive arg validation here, we should probably add these to breaking/dangerous changes in the future.
> Alternative approach for findSchemaChanges

- integrationTests/ts/tsconfig.json
- package-lock.json
- package.json
- src/execution/__tests__/abort-signal-test.ts
- src/execution/execute.ts
- src/graphql.ts
This adds support for aborting execution from the outside or resolvers, this adds a few tests and tries to make the support as easy as possible.
Do we want to support having abort support on subscriptions, I guess it makes sense for server-sent events.
I've chosen 2 places to place these interrupts
- `executeFieldsSerially` - every time we start a new mutation we check whether the runtime has interrupted
- `executeFields` - every time we start executing a new field we check whether the runtime has interrupted
- inside of the catch block as well so we return a singular error, all though this doesn't really matter as the consumer would not receive anything 
- this here should also take care of deferred fields
When comparing this to `graphql-tools/execute` I am not sure whether we want to …
> AbortController support

- src/language/__tests__/parser-test.ts
- src/language/ast.ts
- src/language/parser.ts
This way people can add this to metrics and inform themselves about sane values to use with the `maxTokens` option on `parse`. This was added as a non-enumerable property to increase backwards compatability.
Currently there is now way to know the tokens and by extension set sane defaults.
> Expose `tokenCount` on the `DocumentNode`

- src/execution/__tests__/abort-signal-test.ts
- src/execution/execute.ts
incremental completion errors are indicated if and only if null bubbling has caused a previously sent response to be null
we must instead just give a partial response with errors within the incremental array
The GraphQL Tools implementation of this feature has different behavior where the next call will throw if the operation is aborted, but we have opted to give partial responses, and so we must adjust.
> fix: abortion should not cause incremental completion error

- cspell.yml
- src/execution/__tests__/variables-test.ts
- src/index.ts
- src/type/__tests__/enumType-test.ts
- src/type/__tests__/validation-test.ts
- src/type/introspection.ts
- src/type/validate.ts
- src/utilities/__tests__/astFromValue-test.ts
- src/utilities/astFromValue.ts
- src/utilities/coerceInputValue.ts
- src/utilities/findSchemaChanges.ts
- src/utilities/index.ts
- src/utilities/printSchema.ts
[#3049 rebased on main](https://github.com/graphql/graphql-js/pull/3049).
This is the last rebased PR from the original PR stack concluding with #3049.
* Rebased: #3809 [Original: #3092]
* Rebased: #3810 [Original: #3074]
* Rebased: #3811 [Original: #3077]
* Rebased: #3812 [Original: #3065]
* Rebased: #3813 [Original: #3086]
* Rebased: #3814 (this PR) [Original: #3049]
Update: #3044 and #3145 have been separated from this stack.
Changes from original PR:
1. `astFromValue()` is deprecated instead of being removed.
@leebyron comments from #3049, the original PR:
> Implements [graphql/graphql-spec#793](https://github.com/graphql/graphql-spec/pull/793)
> 
> * BREAKING: Changes default values from being represented as an assumed-coerced "internal input value" to a pre-coerced "external input …
> RFC: Default value validation & coercion

- src/execution/execute.ts
for readability. benchmarks suggest similar or even better performance
> use object for GraphQLWrappedResult instead of tuple

- src/execution/execute.ts
moves simplest case inside the execute[Root|Sub]ExecutionPlan() functions to better match proposed spec edits
orders function in call order, moving executeSubExecutionPlan down closer to where it is used
no significant change in performance
> polish: refactor execution plan functions to match spec

- src/execution/__tests__/nonnull-test.ts
- src/execution/execute.ts
depends on #4267
addresses: #3792
> stop resolvers after execution ends

- src/utilities/__tests__/findSchemaChanges-test.ts
- src/utilities/findSchemaChanges.ts
This adds a new safe schema-change when a description changes of any schema-member. Do note that there are some drive-by fixes in here as I noticed a bug in safe-argument changes where we'd just always report the changes rather than actually see whether something changed 😅 
Resolves https://github.com/graphql/graphql-js/issues/4245
> Add safe schema change for descriptions changing

- website/pages/execution.mdx
- website/pages/graphql.mdx
- website/pages/type.mdx
Ultimately I was trying this out to see whether we can tweak the docs easily, it made me realize that our docs are tailored to general GraphQL rather than how do we use this library. It made me come up with a few suggestions
- We should have a toggle on code examples to switch between `buildSchema` and programatically creating the schema with i.e. `GraphQLObjectType`
- Our documentation starts with a tutorial, this ultimately feels like a mistake, we should lead with an explanation of what GraphQL.JS is and what it aims to do, clearly outlining the goals of this project
- We should line out use-cases for building on this library and best practices of how to go to production
Resolves #2941 
Resolves #2567
> Solve some low hanging fruit in the documentation

- src/utilities/__tests__/findSchemaChanges-test.ts
- src/utilities/findSchemaChanges.ts
Resolves https://github.com/graphql/graphql-js/issues/4237
This mirrors the fields/input-object argument logic but specifically for directives.
> Detect directive argument changes

- website/css/globals.css
- website/pages/_document.tsx
- website/pages/_meta.ts
- website/pages/getting-started.mdx
- website/pages/index.mdx
Not quite sure yet about contents of the overview page, also the header is pretty odd, feels like a nextra bug or I goofed the CSS up 😅 generally though it looks like the extra-button and search/... aren't in their own container preventing a good space-between. The absence of links seems to cause thsi.
> Add overview page and add stackblitz to tutorial

- src/execution/PromiseCanceller.ts
- src/execution/__tests__/PromiseCanceller-test.ts
- src/execution/__tests__/abort-signal-test.ts
- src/execution/__tests__/mapAsyncIterable-test.ts
- src/execution/execute.ts
- src/execution/mapAsyncIterable.ts
When the abort signal is triggered, any pending `.next()` calls should return immediately, ~~and the underlying async iterables `.return()` method should be called~~
> add cancellation support to async iterable iteration

- website/pages/defer-stream.mdx
This is currently not available in the latest release of GraphQL.JS and I wanted to add an explicit call-out for that.
> Add note about defer/stream being v17

- src/error/GraphQLError.ts
- src/error/index.ts
- src/index.ts
Following typescript documentation, it's not possible override interface property, we can only add new props.
Since it's declared as unknown dict, even if we merge `GraphQLErrorExtensions`, we can't access to our extensions without workaround and verbose typescript in source-code.
It's annoying since apollo expose `GraphQLFormattedError` instead `GraphQLError`
Refs: https://www.typescriptlang.org/docs/handbook/declaration-merging.html
Refs: https://github.com/apollographql/apollo-client/pull/11789
> fix: properly type `extensions` in GraphQLFormattedError

- src/language/__tests__/parser-test.ts
- src/language/ast.ts
- src/language/parser.ts
Backports https://github.com/graphql/graphql-js/pull/4251 from v17
Backporting this so we can document the `maxTokens` for production use cases. The performance of this change looks to be neutral
> Expose tokenCount on the DocumentNode

- src/validation/__tests__/ScalarLeafsRule-test.ts
- src/validation/rules/ScalarLeafsRule.ts
Backports https://github.com/graphql/graphql-js/pull/4228 from v17
> Address empty selection-set

- src/language/lexer.ts
we must update the lexer line number and the line start position, because lookahead saves the token within the linked list, and so will never be called again on this token
we do not change the current token, however, until the lexer is advanced
closes #2764
> polish: fix lexer state comment

- .github/CONTRIBUTING.md
- to separate between this repo and the spec
- suggest adding PRs with failing tests when reporting bugs
- add more flexibility to review/merge process
- suggest using discord to communicate
> internal: update CONTRIBUTING guide

- src/type/definition.ts
I was just trying to understand the new flows for how scalar values are represented/parsed/serialized, and noticed that the comments for a couple of these methods looked backwards.
Really hoping I am not just confused about the terminology, and that these aren't actually correct 😅
> polish: fix switched comments in GraphQLScalarTypeConfig

- src/type/__tests__/introspection-test.ts
- src/type/directives.ts
- src/utilities/__tests__/printSchema-test.ts
See https://github.com/graphql/graphql-spec/pull/1040
> Make deprecated.reason non-nullable

- src/index.ts
- src/validation/__tests__/KnownOperationTypesRules-test.ts
- src/validation/index.ts
- src/validation/rules/KnownOperationTypesRule.ts
- src/validation/specifiedRules.ts
New Spec PR: https://github.com/graphql/graphql-spec/pull/1098
Old Spec PR: https://github.com/graphql/graphql-spec/pull/947
Original issue raised by @benjaminjkraft : #3592
> Add KnownOperationTypes rule

- src/execution/collectFields.ts
- src/execution/execute.ts
this way, if (when?) we re-enable incemental delivery support with subscriptions, the signature of collect fields will not need to change
> move subscription `@defer` check out of collectFields

- src/execution/collectFields.ts
- src/execution/execute.ts
- src/validation/rules/SingleFieldSubscriptionsRule.ts
this is the 16.x.x behavior, unlocked by #4308, further reducing the set of breaking changes to this utility
> use `operation.selectionSet` as argument to `collectFields()` instead of `operation`

- src/execution/collectFields.ts
In the "old" duplicating version of incremental delivery, `collectFields()` was responsible for branching, and it therefore allowed processing a deferred named fragment even if that named fragment had already been visited as a regular non-deferred named fragment.
One could have argued against that, as the old version had the concept of inlining, and so we could have just skipped the named fragment and considered it inlined, but chose not to do that.
Now that we have an algorithm without duplication of fields, revisiting a named fragment will have no effect, as within the `buildExecutionPlan()` step, all the duplicated fields will be removed. So we can just remove the exception and go back to the version pre-incremental delivery where we always skip a visited named fragment.
Note that we …
> polish: skip recollecting a named fragment's selections even when deferred

- src/type/directives.ts
Updated to reflect spec draft https://github.com/graphql/graphql-spec/pull/1132
Also changed the argument order to match the spec draft
> Make @stream initialCount NonNull

- benchmark/fixtures.js
- benchmark/kitchen-sink.graphql
- benchmark/printer-benchmark.js
- src/language/visitor.ts
This replaces our expensive method that changes the underlying V8 shape multiple times with a loop that preserves the identity as much as possible.
```
⏱   Print kitchen sink document
1 tests completed.
2 tests completed.
HEAD x 9,290 ops/sec ±0.21% x 1.51 KB/op (24 runs sampled)
BASE x 2,645 ops/sec ±0.18% x 2.18 KB/op (11 runs sampled)
```
> Increase print/visit performance

- src/execution/__tests__/semantic-nullability-test.ts
- src/execution/execute.ts
- src/language/__tests__/parser-test.ts
- src/language/__tests__/predicates-test.ts
- src/language/__tests__/schema-printer-test.ts
- src/language/ast.ts
- src/language/kinds.ts
- src/language/parser.ts
- src/language/predicates.ts
- src/language/printer.ts
- src/type/definition.ts
- src/utilities/extendSchema.ts
- src/utilities/typeFromAST.ts
This reduces the new AST-nodes to only be for the newly introduced type, this does make it so that when we invoke `print` we have to rely on the user to either specify that we're in semantic nullability mode _or_ we could do a pre-traverse and when we enter a node with semantic-non-null we toggle it on ourselves.
The main reasoning behind removing the new name for our existing null type is that I would prefer to be backwards compatible in terms of schema structure. This because it might become complex for people to reason about composed schemas, i.e. a lot of individually parsed schemas that later on compose into a larger one.
I know that _technically_ this is covered because in the classic ones we'll have the non wrapped null type and in the modern ones we'll have the semantic nullable …
> Propose single wrapping type

- website/pages/docs/running-an-express-graphql-server.mdx
See graphql/graphql.github.io#1951
For someone following the tutorial they may well get as far as running the server (`node server.js`) and then attempt to visit their new API and get confused because they're met with an error such as `{"errors":[{"message":"Missing query"}]}`.
This PR adds some joining text to make it clear this is the expected outcome, and they must read on to get the GraphiQL IDE set up so that they can write queries.
> Improve flow of documentation around GraphiQL

- src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.ts
- src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
See discussion https://github.com/graphql/defer-stream-wg/discussions/100
> Validate against `@stream` on different instances of the same field

- website/pages/docs/getting-started.mdx
See: [Archived repo](https://github.com/html5rocks/www.html5rocks.com/blob/master/content/tutorials/es6/promises/en/index.html#L6) redirected the links.
> docs(getting-started): promises current links

- website/pages/docs/running-an-express-graphql-server.mdx
Issue
The server throws an error because the root variable is not defined. The correct variable name should be rootValue, which was previously declared in the code.
Fix
Updated rootValue in the createHandler function to use the correct variable name.
Changes
Replaced root with rootValue in the GraphQL handler configuration.
> fixed wrong variable name

- src/validation/ValidationContext.ts
- src/validation/__tests__/VariablesInAllowedPositionRule-test.ts
- src/validation/rules/VariablesInAllowedPositionRule.ts
In the spec we explicitly disallow `nullable` variables to be passed to the fields of a oneOf input object. This is present in v17 but seems missing from v16.
> Ensure we validate for using nullable variables in oneOf input fields

- src/type/__tests__/introspection-test.ts
- src/type/introspection.ts
- src/utilities/__tests__/printSchema-test.ts
See https://github.com/graphql/graphql-spec/pull/1142
> Make `includeDeprecated` non-null

- src/execution/__tests__/executor-test.ts
- src/utilities/__tests__/coerceInputValue-test.ts
- src/utilities/coerceInputValue.ts
This PR closes #4365 
Rejects arrays when input type is an object. Works for top level arrays and deep ones.
> fix(coerce-input-value): input object coercion rejects arrays

- src/execution/__tests__/executor-test.ts
- src/execution/execute.ts
- website/pages/api-v16/execution.mdx
This PR add `executionOptions` property to the `ExecutionArgs`. Currently only one option can be configured, as is the one I need, but I have built an object so it can easily be extended in the future.
The property allows the configuration of the maximum number of errors (`maxErrors`) for coercion. This allows the current hardcoded limit (`50`) to be reduced to a small number to avoid possible DoS attacks.
> Also, it updates the execution docs to reflect this new change. I think the documentation was outdated since functions were using positional arguments and now they only accept an object.
No longer updates the docs.
> feat(execution): add max coercion errors option to execution context

- website/pages/api-v16/error.mdx
- website/pages/api-v16/execution.mdx
Updates docs after #4366 CC @cristunaranjo
This highlights the deprecated aspect of positional arguments with execute and surfaces the new option. In the v16 docs we will still surface the deprecated variant, we will however prioritise the new way.
> Update docs for execution options

- website/pages/docs/authentication-and-express-middleware.mdx
- website/pages/docs/basic-types.mdx
- website/pages/docs/constructing-types.mdx
- website/pages/docs/getting-started.mdx
- website/pages/docs/mutations-and-input-types.mdx
- website/pages/docs/object-types.mdx
- website/pages/docs/passing-arguments.mdx
- website/pages/docs/running-an-express-graphql-server.mdx
This refactors the code-first examples to use inline-resolvers rather than the root-value to show a difference between SDL and code-first.
> Refactor every code-first example to leverage resolve
