README.md
package.json

To conform with SPDX in order to eliminate NPM warning.

Update license identifier and Fix Typos

---

src/__tests__/starWarsSchema.js

The `resolve` function for `friends` on the `droid` type has `human` as a variable name. This is somewhat confusing, since it will be called on a droid.

Change variable names to reduce confusion

---

CONTRIBUTING.md
README.md

Due to GraphQL is also written in ES2015.

Proposition to change README examples to ES2015 style 

---

src/graphql.js

You are calling `execute` and double resolving even when document validation has failed.

Don't resolve when invalid

---

package.json

Using `&` looks like a typo. It causes `rm` to run in background, which introduces race condition

build: use && instead of &

---

src/executor/__tests__/executor.js

`DataType` is unknown type, so `...Frag` fragment spread was ignored and recursion was not tested correctly.
Additional question: is it intended to just ignore a fragment on the unknown type?

Test recursion avoidance correctly

---

src/type/__tests__/introspection.js
src/type/introspection.js

According to the spec, directive name should be not-null in the introspection API:
http://facebook.github.io/graphql/#sec-Schema-Introspection

Directive name is not-null

---

src/utils/TypeInfo.js

The class is named TypeInfo and not FieldInfo.

Fix typo in comment

---

.gitignore
src/executor/values.js
src/type/definition.js
src/type/directives.js
src/utils/TypeInfo.js
src/validator/index.js

This PR renames GraphQLFieldArgument to GraphQLArgument to make it more clear, that it's not only an argument type for Fields, but a more generic type (currently also used in directives)

Rename GraphQLFieldArgument to GraphQLArgument

---

src/__tests__/starWarsIntrospectionTests.js
src/__tests__/starWarsSchema.js
src/type/definition.js

As the schema sais [__InputValue](http://facebook.github.io/graphql/#sec-Schema-Introspection) can have a `description`. When I tried to set a description inline (Not using an `INPUT_OBJECT `) it did not work. It seems the code in `definition.js` was missing the `description` in a map functions return object.
I've have fixed this an added a Star Wars spec to go with it.
Also a side note: `starWarsSchema.js` was setting [`name`](https://github.com/graphql/graphql-js/blob/master/src/__tests__/starWarsSchema.js#L246) values on the args but it serves no purpose because the name of the arg is set to the value of the key [here](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L302). So I removed the two `name` declarations in the `#human` and `#droid` field args section …

Add missing `description` to field args

---

src/language/__tests__/printer.js
src/language/printer.js

A couple issues have opened up about inconsistency in rendering graphql queries in the spec and in the ref impl - especially with respect to whitespace and commas.
Here I'm proposing that it's easier to read queries where every field is always on it's own line (eg, no `image { width, height }` one-liners) and that lines are split only by line-terminators and not also commas.
If there's agreement around this proposal, the second step will be to apply the printer to all graphql examples in the spec.

[RFC] standard printer uses no comma between fields

---

src/validator/rules/FragmentsOnCompositeTypes.js

Make it more DRY: Use the appropriate helper function instead of repeating all composite types

use isCompositeType function instead of manual checking

---

.eslintrc
package.json
scripts/mocha-bootload.js
src/__tests__/starWarsIntrospectionTests.js
src/__tests__/starWarsQueryTests.js

This PR adds the async/await babel polyfill and then changes src/__tests__ (the Star Wars tests) to use them. Using this transform makes life a lot easier.
1) The syntax is nicer
2) No need to use the promise-friendly chai from the chai-as-promised module. I dislike these directives because it makes it awkward to add console logging in a test in between the executed test code and then test of the result. I also think its often desirable to do multiple expects with more granular error messaging.
3) No more forgetting to return the promise and then have false-passes because the code just doesn't execute.
4) From brief testing the errors messages appear more reasonable. 
I think we should just get rid of chai-as-promised and switch to this.

Babel async await

---

src/utils/TypeInfo.js

VariableDefinition needs to cleanup the inputTypeStack and not argument
Argument needs to cleanup inputTypeStack too

Bugfix TypeInfo: Missing/Wrong cleanup in leave

---

package.json

Removes `npm run cover` in favor of the one `npm run coveralls` integration.
Also simplifies that script, removing the need for babel-node.
Finally, ensures the root is at "src" which removes the transient error parsing _mocha, speeds up the script, and does not count "scripts" as part of coverage score.

Simplify coveralls script

---

package.json

reverts part of #62 that removed babel-node, apparently that's a critical part of ensuring coveralls gets accurate line reporting.

coveralls sanity

---

README.md

To avoid confusion for developers new to the project that haven't heard of Flow.

Mention that Flow is used.

---

src/type/__tests__/introspection.js
src/type/introspection.js
src/type/introspectionQuery.js

This PR makes the introspection query more complete. We simply did not
query everything we needed to for a complete type system.
I also removed the __typename field everywhere. We should have a
different query for an introspection acceptance test. This query
is for tool-building.

Introspection query changes

---

src/type/__tests__/printer.js
src/type/printer.js

This adds a printer to translate the result of an introspection query
to the grammar that is currently used as shorthand in the specification.
This should be treated as the de facto specification until a formalized
grammar is produced.
The next step is to do the transformation in the other
direction.
A tool that should be built on top of this is one that executes
the introspection query against an arbitrary GraphQL HTTP endpoint
(specified per the upcoming graphql-http spec) and then performs
acceptable tests with that tool.
In the interim we hope that this will be useful for implementors
building and debugging their own type systems.

Add Schema Printer

---

src/__tests__/starWarsData.js
src/__tests__/starWarsIntrospectionTests.js
src/__tests__/starWarsQueryTests.js
src/__tests__/starWarsSchema.js

It was odd in our demo that `hero` returned a `Character`, but it always returned R2-D2, who is a `Droid`. Change it so this takes an optional `episode`, and returns Luke as the hero for Episode V, demonstrating more clearly why this field returns an Interface, and the value of querying for `__typename` to find the concrete type.

Allow an episode to be passed to hero

---

src/language/parser.js
src/language/parserCore.js
src/language/schema/__tests__/parser.js
src/language/schema/ast.js
src/language/schema/kinds.js
src/language/schema/parser.js

This is a parser for the ad-hoc type definition language included in the
spec. This should also serve as a de-facto spec for the language.
Clearly once this is stable we should include it in the actual spec as
well.
This should end up being useful in a few contexts, including
client-side types and also a DSL for producing the JS type definitions
which can be tedious to write, and a way to specify acceptance tests.
(This would be a clear next step for this project)

Schema Definition Language Parser

---

src/language/parser.js
src/language/schema/__tests__/parser.js
src/language/schema/ast.js
src/language/schema/parser.js

This PR tackles a few things:
1. Adds doc block illustrating grammar for every parse rule.
2. Changes Union syntax to match what we use in GraphQL spec.
3. Add default value to field arguments, along with test.
4. Edit tests to be of form "expect test-value to be expected-value"
5. Consistency through rules w.r.t `loc` vs `location` and short-hand object definitions.

Docs and Alterations to Schema Grammar

---

src/type/__tests__/introspection.js
src/type/__tests__/printer.js
src/type/introspection.js

The spec states that
```
type __Directive {
onOperation: Boolean!
onFragment: Boolean!
onField: Boolean!
}
```
but the implementation defines it as
```
type __Directive {
onOperation: Boolean
onFragment: Boolean
onField: Boolean
}
```

fix directive inspection according to spec

---

src/executor/values.js
src/language/schema/__tests__/materializer.js
src/language/schema/ast.js
src/language/schema/materializer.js
src/type/definition.js

Adds the schema materializer. This components takes a schema definition
AST and produces a set of type definition objects corresponding to the
schema definitions. This allows a user to specify schema in a far
more literate fashion
The next tool that I'm going to write is one that takes the
schema definition DSL and outputs the result of the introspection
query against that schema. This will be really useful for tests, etc.

Schema Materializer

---

src/language/schema/__tests__/materializer.js
src/language/schema/materializer.js
src/language/schema/printer.js
src/tools/print-schema/print-schema.js
src/tools/print-schema/src/index.js

This tool accepts an input graphql schema definition file and
outputs the corresponding introspection query result for that file

Print Schema Tool

---

package.json
src/tools/print-schema/src/index.js

Fixes the relative path used in `print-schema` output and adds missing npm dependencies.

Fix paths and dependencies in print-schema tool

---

src/tools/print-schema/src/index.js

Update print-schema tool to set the file encoding when reading the schema definition.

Set encoding when reading schema file

---

src/index.js
src/language/schema/__tests__/materializer.js
src/language/schema/index.js
src/type/__tests__/schemaPrinter.js
src/type/index.js
src/type/schemaPrinter.js

I'm making some room here for a "printer" in language/schema/printer which mirrors the behavior of language/printer: it takes the AST in, and prints out the DSL.
The printer as written makes sense to live in type/schemaPrinter IMO, since it's within the family of tools that operate upon GraphQLSchema instances.

Minor follow-on re-org.

---

src/language/printer.js
src/language/schema/__tests__/printer.js
src/language/schema/__tests__/schema-kitchen-sink.graphql
src/language/schema/index.js
src/language/schema/printer.js
src/language/schema/visitor.js

This adds a "visitor" and "printer" utilities for the schema language in the same form as those used for the document language.

Add visitor and printer utils to schema language

---

src/language/__tests__/parser.js

Resolves issue #58. There is one special case because fragments named `on` may be defined according to the current specification (`fragment on on SomeType { someField }`), but may not be referenced.
(If you try to reference your fragment named `on`, it's at best a syntax error, as in `{ ...on }`, which is the start of an inline fragment definition that doesn't have a type.)

Add parser tests for accepting non-keywords

---

src/type/__tests__/introspection.js
src/type/introspectionQuery.js
src/type/schemaPrinter.js

Flow was not checking introspectionQuery.js, so I added @flow header. In order to fix flow errors I flushed out a more specific Flow type that takes advantage of tagged unions.

Ensure flow checks introspection result

---

src/type/__tests__/buildClientSchema.js
src/type/buildClientSchema.js
src/type/definition.js
src/type/introspection.js
src/utils/keyValMap.js

Given a full introspection result, this builds a GraphQLSchema instance that can be used for everything except execution, allowing clients to use it throughout tools, establishing GraphQLSchema as the common in-mem representation of the type system for use across both server and client.
This differs from the DSL materializer in a few important ways:
1. Input. This accepts introspection result, which is trivial for a client to produce given any server. This avoids requiring client tools to leverage the whole GraphQL executor locally to derive this information, which lets it be a sync operation.
2. Scope. This preserves everything that introspection represents including descriptions (and in a follow-up, deprecations).

Client Schema Builder

---

src/language/schema/__tests__/materializer.js
src/type/__tests__/schemaPrinter.js
src/type/schemaPrinter.js
src/utils/__tests__/astFromValue.js
src/utils/astFromValue.js

This allows schemaPrinter to be a sync rather than async function.
Also introduces the (meaty) "astFromValue" utility which accepts arbitrary JS values and outputs GraphQL AST.

Print the schema directly, rather than the introspection result.

---

src/index.js
src/language/schema/index.js
src/tools/__tests__/buildASTSchema.js
src/tools/__tests__/buildClientSchema.js
src/tools/__tests__/schemaPrinter.js
src/tools/buildASTSchema.js
src/tools/buildClientSchema.js
src/tools/index.js
src/tools/schemaPrinter.js
src/type/index.js
src/type/schema.js

These are all utilities that will be useful for building custom client tools.
This moves the client-side schema builders (from introspection and from DSL) along with the schema printer into the `graphql/tools` sub-module, and sets up an index export for these tools.
This also clarifies the `graphql/language/schema` sub-module's exports as only dealing with the language.
Finally, this makes some small improvements to leverage existing utility functions and remove async where it's not necessary.

Leverage 'graphql/tools' for common utilities

---

src/utilities/__tests__/buildASTSchema.js
src/utilities/buildASTSchema.js

Fixes issue #104 and allows buildASTSchema to materialize a type with a Float field. Adds tests for Float and ID to 'Simple type' test and for Float, ID, Int and Boolean to 'Single argument field' test.

Fixes issue #104 with buildASTSchema and Float fields

---

src/utilities/__tests__/buildASTSchema.js
src/utilities/buildASTSchema.js

Ensures that if a type isn't referenced directly, but implements an interface that is references, that type is included in the schema, with a unit test to verify.

Ensure unreferenced types that implement reference interfaces are detected

---

src/utilities/__tests__/buildASTSchema.js
src/utilities/buildASTSchema.js

We weren't checking unknown mutation types (and we were double checking unknown query types).

Add check for unknown mutation type

---

src/type/__tests__/definition.js
src/type/__tests__/validator.js
src/type/schema.js

Input object types were not included in the type map when they were used as a field type in other input objects, because `typeMapReducer` did not recurse into those fields.
Modify `typeMapReducer` to also handle GraphQLInputObjectType and add a test case that checks also nested input object types are handled.

Fix some input objects missing from the type map

---

src/graphql.js
src/type/__tests__/introspection.js
src/utilities/__tests__/buildClientSchema.js

This changes the implementation of `graphql()` to not format any returned errors. Most importantly, this allows access to the `stack` property of each error, along with richer information contained in GraphQLError like the affected AST nodes and source document.
This means that the responsibility for formatting errors must be handled elsewhere, likely by an HTTP service like `express-graphql`.

[RFC] Do not format errors from graphql()

---

src/execution/execute.js
src/execution/values.js
src/type/definition.js
src/type/introspection.js

This exposes more info to field resolvers, but reduces the arity of these functions to a fixed 3 arguments: source, arguments, execution info.
This along with ES6 argument destructuring makes accessing this information more natural.

[RFC] Expose more information to field resolver functions.

---

src/type/__tests__/validation.js
src/type/schema.js
src/validation/__tests__/KnownArgumentNames.js
src/validation/__tests__/harness.js

This adds an invariant step in the Schema ctor for enforcing that all Object types in the Schema properly adhere to the Interface types they claim to implement.
This effectively implements http://facebook.github.io/graphql/#sec-Object-type-validation

[RFC] schema enforced interface adherance.

---

src/execution/__tests__/lists.js
src/execution/__tests__/nonnull.js
src/execution/execute.js

I was implementing a GraphQL schema today and encountered this error: `Cannot return null for non-nullable type.`
I thought it left something to be desired in terms of figuring out which field/type was causing this issue. This PR adds a more descriptive error message, including the field name and parent type name to make this easier to track down.
Let me know if this needs any changes.

Improve error message on null-values for non-nullable fields

---

src/type/__tests__/definition.js
src/type/definition.js

Types used to mutate the fields passed to it, which can be very confusing and prevents reuse (parts) of field definitions between multiple types. Changed it so that fields is first shallow copied and new object is returned as a field map.

Do not mutate passed field map in ObjectType and ObjectInput

---

src/language/ast.js
src/language/kinds.js
src/language/parser.js
src/language/printer.js
src/language/visitor.js

This proposal introduces a syntactic addition for client-side tools that perform code generation. It allows those tools to describe "extensions" to the server-supplied GraphQL schema. Tools may then use this information to generate types/classes/objects in the client language which include these client-side-only extensions.
The syntax I'm proposing is:
```
TypeExtensionDefinition : `extend` ObjectDefinition
```
An example of this might look like:
```
type User {
name: String
birthday: Int
}
extend type User {
age: Int
}
```
While I could have proposed simply `extend User { ... }`, I chose to fully reuse the ObjectDefinition rule to preserve the future ability to expand this syntax to include extending interfaces, enums, and other types.

[RFC] Type extension syntax

---

src/type/__tests__/validation.js
src/type/schema.js

If I've understood the intent of https://facebook.github.io/graphql/#sec-Names, field arg names are restricted to `/^[_a-zA-Z][_a-zA-Z0-9]*$/`.
Currently the js implementation allows the creation of non-conformant field arg names, which means you can create a field arg that a client can't actually reference in a query.
This PR adds a test for field arg name validity.

Check for valid field arg names

---

src/language/__tests__/schema-parser.js

Didn't seem to be tested, so here's a test.

Add test for parsing extend type definitions

---

src/validation/rules/KnownArgumentNames.js
src/validation/rules/LoneAnonymousOperation.js

There were a few places in the validation rules that were not using the
constants found in `src/language/kinds.js`. This commit replaces those strings
with their respective constants.
This can be considered a cleanup.

Replaced validator kind strings with constants

---

src/execution/__tests__/executor.js
src/execution/execute.js

This adds another way resolver functions can signify a failure: returning an Error object.
The primary reason this is useful is returning a list of values where index contains an error but another does not. A test casehas been added to illustrate this behavior. Previously sync resolvers could only throw an error, killing the whole list, or return nulls and fail to present error messaging.
I then used this as a simplifying factor to the executor core where it removed one of three instances of locating and logging an error.

Resolvers can return `Error` to signify failure

---

src/language/__tests__/parser.js
src/language/parser.js
src/validation/__tests__/UniqueInputFieldNames.js
src/validation/rules/UniqueInputFieldNames.js
src/validation/specifiedRules.js

This proposes moving input field uniqueness assertion from the parser to the validator. This simplifies the parser and allows these errors to be reported as part of the collection of validation errors which is actually more valuable.
Spec: https://github.com/facebook/graphql/pull/95

[RFC] Move input field uniqueness validator

---

src/language/__tests__/lexer.js
src/language/lexer.js

This proposal alters the parser grammar to be more specific about what unicode characters are allowed as source, restricts those characters interpretted as white space or line breaks, and clarifies line break behavior relative to error reporting with a non-normative note.
Implements https://github.com/facebook/graphql/pull/96

[RFC] Clarify and restrict unicode support

---

src/execution/execute.js
src/language/__tests__/parser.js
src/language/parser.js
src/utilities/getOperationAST.js

Implements https://github.com/facebook/graphql/pull/99

[RFC] Make operation name optional.

---

src/execution/execute.js
src/jsutils/README.md
src/language/printer.js
src/language/visitor.js
src/type/definition.js

Also fixed one use of "descendents" that happened to be on one of the
touched lines.

Declare total war on misuse of "it's"

---

src/type/__tests__/validation.js
src/type/schema.js

Implements https://github.com/facebook/graphql/pull/110

[RFC] Additional optional arguments

---

src/type/__tests__/validation.js
src/type/definition.js
src/type/directives.js
src/type/schema.js
src/utilities/__tests__/buildClientSchema.js
src/utilities/buildClientSchema.js
src/validation/__tests__/KnownDirectives.js
src/validation/__tests__/harness.js

This allows GraphQLSchema to represent different sets of directives than those graphql-js is able to use
during execution. Critically, this allows GraphQLSchema to be used against servers which support different sets of directives and still use validation utilities.

Allow providing directives to GraphQLSchema

---

src/type/definition.js
src/utilities/__tests__/buildClientSchema.js
src/utilities/buildClientSchema.js
src/utilities/introspectionQuery.js

This ensures deprecation information flows throughout introspection back through building client-side schema.

Support deprecation via introspection

---

src/utilities/__tests__/extendSchema.js
src/utilities/extendSchema.js
src/utilities/index.js

This new utility function produces a new Schema, provided an existing one and a document containing schema type definitions and extensions.

extendSchema()

---

src/validation/__tests__/OverlappingFieldsCanBeMerged.js
src/validation/rules/OverlappingFieldsCanBeMerged.js

As pointed out in #53, our validation is more conservative than it needs to be in some cases. Particularly, two fields which could not overlap are still treated as a potential conflict.
This change loosens this rule, allowing fields which can never both apply in a frame of execution to diverge.

[validation] Allow safe divergence

---

src/validation/__tests__/OverlappingFieldsCanBeMerged.js
src/validation/rules/OverlappingFieldsCanBeMerged.js

The currently supported directives: @skip and @include do not create an ambiguous or erroneous query when used on conflicting fields in a divergent fashion. In fact, this may be intended when many different conditions should result in the same outcome. For example:
```graphql
{
field @include(if: $firstCondition)
field @include(if: $secondCondition)
}
```
This example could be considered as the intent of fetching `field` given `$firstCondition || $secondCondition`. While this example is contrived, there are more complex examples where such fields are nested within fragments that this condition is reasonable.

[validation] Allow differing directives.

---

src/validation/__tests__/NoFragmentCycles.js
src/validation/rules/NoFragmentCycles.js

This converts the O(N^2) cycle detector to an O(N) detector and optimizes the visit to short-circuit where parts of the validation visitor were unnecessary.
On an internal very large stress test query this was previously ~30s and after this diff runs in 15ms.

[Validation] perf improvements for fragment cycle detection

---

src/validation/rules/NoUnusedFragments.js
src/validation/validate.js

This adds a new method to the validation context which when given an Operation definition, returns a list of all Fragment definitions recursively referenced via fragment spreads.
This new method is then used to ensure no fragments are unused.
The implementation of this method is the same in principle as the one which used to be inline in the validation rule, but has been unfolded from recursion to use a while loop.

[Validation] Factor out and memoize recursively referenced fragments.

---

src/validation/__tests__/NoUndefinedVariables.js
src/validation/rules/NoUndefinedVariables.js
src/validation/rules/NoUnusedVariables.js
src/validation/rules/VariablesInAllowedPosition.js
src/validation/validate.js

During multiple validation passes we need to know about variable usage within a de-fragmented operation. Memoizing this ensures each pass is O(N) - each fragment is no longer visited per operation, but once total.
In doing so, `visitSpreadFragments` is no longer used, which will be cleaned up in a later PR

[Validation] Memoize collecting variable usage.

---

src/validation/__tests__/FieldsOnCorrectType.js
src/validation/__tests__/validation.js
src/validation/rules/ArgumentsOfCorrectType.js
src/validation/rules/DefaultValuesOfCorrectType.js
src/validation/rules/FieldsOnCorrectType.js
src/validation/rules/FragmentsOnCompositeTypes.js
src/validation/rules/KnownArgumentNames.js
src/validation/rules/KnownDirectives.js
src/validation/rules/KnownFragmentNames.js
src/validation/rules/KnownTypeNames.js
src/validation/rules/LoneAnonymousOperation.js
src/validation/rules/NoFragmentCycles.js
src/validation/rules/NoUndefinedVariables.js
src/validation/rules/NoUnusedFragments.js
src/validation/rules/NoUnusedVariables.js
src/validation/rules/OverlappingFieldsCanBeMerged.js
src/validation/rules/PossibleFragmentSpreads.js
src/validation/rules/ProvidedNonNullArguments.js
src/validation/rules/ScalarLeafs.js
src/validation/rules/UniqueArgumentNames.js
src/validation/rules/UniqueFragmentNames.js
src/validation/rules/UniqueInputFieldNames.js
src/validation/rules/UniqueOperationNames.js
src/validation/rules/VariablesAreInputTypes.js
src/validation/rules/VariablesInAllowedPosition.js
src/validation/validate.js

This replaces the mechanism of returning errors or lists of errors from a validator step to instead report those errors via calling a function on the context.
This simplifies the implementation of the visitor mechanism, but also opens the doors for future rules being specified as warnings instead of errors.

[Validation] Report errors rather than return them

---

src/language/visitor.js
src/validation/validate.js

This provides a performance improvement and simplification to the validator by providing two new generic visitor utilities. One for tracking a TypeInfo instance alongside a visitor instance, and another for stepping through multiple visitors in parallel. The two can be composed together.
Rather than 23 passes of AST visitation with one rule each, this now performs one pass of AST visitation with 23 rules. Since visitation is costly but rules are inexpensive, this nets out to a much faster overall validation, especially noticeable for very large queries.
On an internal very large query validation stress-test saw ~ 4-5x performance improvement.
This fixes #211

[Validation] Parallelize validation rules.

---

src/type/__tests__/validation.js
src/type/schema.js
src/utilities/typeComparators.js
src/validation/rules/OverlappingFieldsCanBeMerged.js
src/validation/rules/VariablesInAllowedPosition.js

This proposes loosening the definition of implementing an interface by allowing an implementing field to return a subtype of the interface field's return type.
This example would previously be an illegal schema, but becomes legal after this diff:
```graphql
interface Friendly {
bestFriend: Friendly
}
type Person implements Friendly {
bestFriend: Person
}
```

[Schema] Implementing interfaces with covariant return types.

---

src/execution/__tests__/variables.js
src/execution/values.js
src/type/__tests__/enumType.js
src/utilities/isValidJSValue.js
src/utilities/isValidLiteralValue.js
src/validation/__tests__/ArgumentsOfCorrectType.js
src/validation/__tests__/DefaultValuesOfCorrectType.js
src/validation/rules/ArgumentsOfCorrectType.js
src/validation/rules/DefaultValuesOfCorrectType.js

Add index of invalid element or field of invalid field and make it recurse
into children until faulty place is found.

Make input objects and lists return better errors

---

src/README.md

`graphql/language/schema` was merged with `graphql/language` in v0.4.3.

Docs: remove outdated language/schema from readme.

---

resources/prepublish.sh

Followup commit to c61ccac where babel plugin options were inlined to command line. Brings npm published version and built version in sync.

Use the same babel options in npm published package

---

package.json

Tests started failing a few days ago, when escope (eslint dependency) updated v3.2.0 to v3.2.1, with updated dependencies. There may still be fixes coming in babel-eslint, escope, and their dependencies, but pumping babel-eslint for now seems to fix the tests.

Fix tests by updating babel-eslint

---

package.json

Adding main to package.json tells consumers what is the main eatery point (as im sure you all know) [https://docs.npmjs.com/files/package.json#main](https://docs.npmjs.com/files/package.json#main). I know consumers should fallback to index.js, but its is still nice to have. I should probably add this case on the thing I am building as well.

add main to package.json

---

src/execution/execute.js

In my Object about 8 list fields, and it is not possible to determine which exactly produces an error.
--- 
Error message now contains field name 
`User Error: expected iterable, but did not find one for field Resume.experience.`

Better error for GraphQLList

---

src/execution/__tests__/variables.js
src/utilities/isValidJSValue.js

The error message for unknown field was literal:
"In field "${providedField}": Unknown field."
Add necessary back ticks to the template literal so the message
includes the actual field name. Also change the test that claims to
test this case to actually test it.

Fix the error message for unknown field

---

src/validation/__tests__/FieldsOnCorrectType.js
src/validation/__tests__/harness.js
src/validation/__tests__/validation.js
src/validation/rules/FieldsOnCorrectType.js

Update the error message for `undefinedField` to take in a list of suggested type names.

[validator] Add suggested types to incorrect field message

---

src/utilities/__tests__/extendSchema.js

The test was run against the function instead of the schema, a simple typo omission.

Test schema instead of function

---

src/utilities/__tests__/extendSchema.js

Looks like there were plenty of these typos. I was in a rush to catch the train and didn't see them all.

Test schema instead of function 2

---

src/language/__tests__/printer.js
src/language/printer.js

Addresses #288. Simply inserts another check to see OperationType is `query` and only omit the keyword in that case. For `mutation` (and `subscription`) the query string should still contain OperationType.

Provides a correct OperationType without name in GraphQLPrinter

---

src/language/__tests__/visitor.js
src/language/visitor.js

Opening an issue to discuss this apparent problem.

Visitor does not support `enter` and `leave` for the root node

---

src/execution/__tests__/variables.js

I was looking through to get a sense for how `parseLiteral` was used and realized there wasn't a test for its use here, so I added one.

Add test for parseLiteral on ComplexScalar

---

src/__tests__/starWarsIntrospectionTests.js
src/index.js
src/type/__tests__/introspection.js
src/type/definition.js
src/type/directives.js
src/type/introspection.js
src/utilities/__tests__/buildClientSchema.js
src/utilities/__tests__/schemaPrinter.js
src/utilities/assertValidName.js
src/utilities/buildClientSchema.js
src/utilities/index.js
src/utilities/introspectionQuery.js
src/validation/__tests__/KnownDirectives.js
src/validation/__tests__/harness.js
src/validation/rules/KnownDirectives.js

This implements https://github.com/facebook/graphql/pull/152
This proposes a change to how we represent the ability to validate the locations of directives via introspection.
Specifically, this deprecates `onField`, `onFragment`, and `onOperation` in favor of `locations` which is a list of `__DirectiveLocation`.
**Rationale:**
This allows for a more fine-grained validation of directive placement, now you can assert that a directive is allowed on queries but not mutations, or allowed on fragment definitions but not on fragment spreads.
Also, this makes expanding the locations a directive is allowed to be placed easier to do, as future expansions will not affect the introspection API. This should be considered a prereq to #265.
Finally, this is a prereq to a forthcoming RFC to add …

[RFC] Proposed change to directive location introspection

---

README.md

In response to https://github.com/graphql/graphql-js/issues/27 and SO questions. I don't believe there is "official" documentation (besides in issues and tests) of Promise support in the resolve function. Totally willing to be wrong :)

Reference promises for resolve func

---

src/language/__tests__/schema-kitchen-sink.graphql
src/language/__tests__/schema-printer.js
src/language/ast.js
src/language/kinds.js
src/language/parser.js
src/language/printer.js
src/language/visitor.js
src/type/directives.js
src/utilities/__tests__/buildASTSchema.js
src/utilities/__tests__/schemaPrinter.js
src/utilities/buildASTSchema.js
src/utilities/buildClientSchema.js
src/utilities/schemaPrinter.js

This adds directives to schema language and to the utilities that use it (schema parser, and buildASTSchema). Directives are one of the few missing pieces from representing a full schema in the schema language.
Note: the schema language is still experimental, so there is no corresponding change to the spec yet.
DirectiveDefinition :
- `directive` `@` Name ArgumentsDefinition? `on` DirectiveLocations
DirectiveLocations :
- Name
- DirectiveLocations `|` Name
Example:
```
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
directive @include(if: Boolean!)
on FIELD
| FRAGMENT_SPREAD
| INLINE_FRAGMENT
```
Note: this depends on #317

[RFC] Directives in schema language

---

src/type/definition.js

The definition file uses a named type GraphQLFieldResolveFn to describe the user provided field resolving function, but uses inline types to describe the resolveType and isTypeOf functions.
This change brings symmetry by defining a named types for the other two resolving functions: resolveType and isTypeOf.  This adds named types for those, too: GraphQLTypeResolveFn and GraphQLIsTypeOfFn.
This is in the #304 PR, but stands on its own.  In that PR, each function of the three functions is changed to have a different type for the info parameter.  Having symmetrical definitions makes that change easier to follow. 
This was not done for serialize, parseValue and parseLiteral because they are not exposed on their object and the named type would have only been referenced in one place.

Add named type for user defined resolveType and isTypeOf functions

---

src/language/ast.js
src/language/kinds.js
src/language/parser.js
src/language/printer.js

https://github.com/facebook/graphql/pull/90

Updating schema parser to more closely match current state of RFC

---

src/execution/execute.js

The completeValue function is fairly large and took me a while to understand.  This PR extracts out the logic that is different based on the type of the value being completed.  Four new functions are added:
- completeListValue
- completeLeafValue
- completeObjectValue
- completeAbstractValue
The code in each function is identical except i inlined one isAbstractType call to avoid having to add an invariant.
I did add an invariant for an unreachable condition that also exists in the current logic in master, but ends on a return null.
This is a change that I did as part of #304.  I'm submitting it as a separate PR. I think its a good change regardless of whether #304 is accepted.
Note that the names in this PR do not match #304.  I tried to match the spec more closely with the names here and …

Split up the completeValue function

---

src/type/definition.js

What does it mean that the GraphQLResolveInfo parameter is optional for GraphQLTypeResolveFn and GraphQLIsTypeOfFn?  Does that mean when I'm implementing an execution engine I don't have to pass it?  Does that mean if I'm implementing a resolve function I might receive null?
info is not optional for GraphQLFieldResolveFn, so lets make the function signatures symmetric by making it required for GraphQLTypeResolveFn and GraphQLIsTypeOfFn.  The value can be ignored, but will clearly always be sent.

Remove unnecessary optionality in type resolve parameters

---

src/execution/execute.js

Somehow it appears that `call` is becoming unbound, resulting in errors being thrown by `defaultResolveFn`.
Why not just call the function directly?
Affects mattkrick/meatier#123 and [trace can be seen on ci](https://circleci.com/gh/wenzowski/meatier/15)

unnecessary call throwing errors

---

src/execution/__tests__/resolve.js
src/execution/execute.js

Add tests and refine default resolve function.

---

src/execution/execute.js
src/type/definition.js

Default behavior for resolving fields is located in execute.js, while default behavior for resolving types is located in definition.js.  These two functions should be located in the same place.
Since type resolving is an execution phase activity, it more closely belongs in execute.js than in definition.js.  In #304, I ended up having to change this algorithm, also indicating that it changes when execution algorithms change and thus should be co-located with execution.
This also results in a cleaner definition.js for cases when execution is not needed.
getObjectType was removed, as field resolve has no such accessor. 
In more aggressive optimization experiments it turns out that knowing when the the default was to be used was valuable information.  The accessor for type resolving obscures …

Move getTypeOf to execute.js and rename to defaultResolveTypeFn

---

src/__tests__/starWarsIntrospectionTests.js
src/__tests__/starWarsSchema.js
src/execution/__tests__/abstract.js
src/execution/__tests__/union-interface.js
src/execution/execute.js
src/type/__tests__/definition.js
src/type/__tests__/validation.js
src/type/definition.js
src/type/introspection.js
src/type/schema.js
src/utilities/__tests__/buildClientSchema.js
src/utilities/__tests__/extendSchema.js
src/utilities/__tests__/schemaPrinter.js
src/utilities/buildASTSchema.js
src/utilities/buildClientSchema.js
src/utilities/extendSchema.js
src/utilities/schemaPrinter.js
src/utilities/typeComparators.js
src/validation/__tests__/OverlappingFieldsCanBeMerged.js
src/validation/__tests__/harness.js
src/validation/rules/FieldsOnCorrectType.js
src/validation/rules/PossibleFragmentSpreads.js
src/validation/rules/VariablesInAllowedPosition.js

This is a rebased and updated version of @tgriesser's #199. I further extended it to completely remove the side-effectful mutation of Interface types rather than just deferring that mutation to schema creation time.
This introduces a *breaking* change to the Type System API. Now, any individual Interface type does not have the required information to answer `getPossibleTypes` or `isPossibleType` without knowing the other types in the Schema. These methods were moved to the Schema API, accepting the abstract type as the first parameter.
This also introduces a *breaking* change to the type comparator functions: `isTypeSubTypeOf` and `doTypesOverlap` which now require a Schema as a first argument.

Add GraphQLSchema types field

---

src/__tests__/starWarsQueryTests.js
src/execution/__tests__/executor.js
src/execution/__tests__/union-interface.js
src/execution/__tests__/variables.js
src/execution/execute.js
src/graphql.js
src/type/__tests__/enumType.js
src/type/definition.js
src/type/introspection.js
src/utilities/__tests__/buildClientSchema.js

This *BREAKING* change introduces a new argument to the GraphQL execution API which is presented to resolution functions: `context`.
This solves a long-standing point of confusion about the correct way to represent authentication or a "viewer context" in which a query is executed.
Previously, we suggested that the `rootValue` contain any authentication tokens, however this led to awkward code:
```
resolve: (val, args, { rootValue: { authToken } }) { ... }
```
Which can now be written as:
```
resolve: (val, args, authToken) { ... }
```
The `info` object is still created and provided to resolution functions, and the `rootValue` is still provided within it, however it is now the *fourth* argument rather than the *third*.

[RFC] Add explicit context arg to graphql execution

---

src/language/__tests__/schema-kitchen-sink.graphql
src/language/__tests__/schema-printer.js
src/language/ast.js
src/language/kinds.js
src/language/parser.js
src/language/printer.js
src/language/visitor.js
src/utilities/__tests__/buildASTSchema.js
src/utilities/__tests__/extendSchema.js
src/utilities/__tests__/schemaPrinter.js
src/utilities/buildASTSchema.js
src/utilities/schemaPrinter.js

This implements the schema definition in the spec proposal in https://github.com/facebook/graphql/pull/90
Adjusts AST, parser, printer, visitor, but also changes the API of buildASTSchema to require a schema definition instead of passing the type names into the function.

[RFC] Add Schema Definition to IDL.

---

src/execution/execute.js

I had an error in my resolveType function which took me a long time to track down.  If resolveType returns null, even accidentally, completeAbstractValue just returns null and no error is noted.
It is reasonable for resolveType to return null if a type cannot be determined.  But, is it reasonable for execute to ignore when this happens?
This PR introduces an invariant to trigger an error message when the runtime type cannot be determined, or something weird is returned from resolveType.

Improve coercion error messages

---

src/execution/__tests__/directives-test.js
src/execution/execute.js

The GraphQL spec has the following paragraph in the [`@include` section](http://facebook.github.io/graphql/#sec--include):
> In the case that both the `@skip` and `@include` directives are provided in the same context, the field or fragment must be queried only if the `@skip` condition is false *and* the `@include` condition is true. Stated conversely, the field/fragment must *not* be queried if either the `@skip` condition is true or the `@include` condition is false.
However, a field or fragment with `@skip(if: false) @include(if: false)` would be queried even though `@include(if: false)` should cause it to not be queried.
Only do an early return when checking the skip directive if its argument is `true`.

Fix bug where @include directive is ignored if @skip is present.

---

src/utilities/__tests__/buildASTSchema-test.js
src/utilities/buildASTSchema.js

Adds checks to make sure the AST contains exactly one query, and at most one mutation and subscription operation.
Here's the original pull-request: https://github.com/graphql/graphql-js/pull/340

Add sanity checks for schema in buildASTschema

---

src/utilities/__tests__/buildClientSchema-test.js
src/utilities/introspectionQuery.js

Certain use cases require deeply nested types, perhaps non-null lists inside non-null lists etc..
GraphQL (quite reasonably) doesn't support infinitely recursive queries, which would enable introspecting on arbitrarily nested structures like this. This limits introspection on deeply nested types.
This GraphQL implementation provides an introspection query that supports up to a finite depth, currently 3, e.g. `[Int!]!`. This is not enough for all use cases: imagine a fully non-null 3D matrix: `[[[Int!]!]!]!`.
In practice, I encountered this problem almost immediately with a modest type akin to `[[Int!]!]`.
Deepen the introspection depth for nested types from 3 to 7. This is enough to support the examples above, and is likely to be enough for most reasonable cases, even with fairly heavy …

Deepen introspection query from 3 levels to 7

---

package.json
src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js
src/validation/rules/OverlappingFieldsCanBeMerged.js

When I submit a query with overlapping field names like so:
_node {
echo(val: "test"),
echo(val: "foo")
}_
I get the following validation error: 
**"Fields \"echo\" conflict because they have differing arguments."**
This PR modifies the error message to suggest using aliases when this occurs: 
**"Fields \"echo\" conflict because they have differing arguments. Use aliases on the fields to fetch both if this was intentional."**

Improve validation error message when field names conflict

---

src/type/__tests__/schema-test.js
src/type/schema.js

If you don't implement `schema.types`, the current error message is very unhelpful (`reduce is not a function on undefined`). this should help others in the future

Error logging for new interface type semantics

---

src/execution/execute.js
src/utilities/extendSchema.js
src/validation/validate.js

This change removes the instanceof GraphQLSchema checks in validate and execute. This makes graphql-js play more nicely with schemas generated by other libraries, or even schemas created by other versions of graphql-js as long as they are compatible (a common issue with npm v2).
@leebyron Right now I just removed the checks and didn't replace them with anything, because it turned out that no tests were affected by the change. Let me know if you think we should have some duck typing checks in there, such as checking that getTypeMap, get Type, getQueryType, getDirectives etc. are functions.

Remove all 'instanceof GraphQLSchema' checks

---

src/execution/execute.js
src/utilities/extendSchema.js
src/validation/validate.js

Reverts graphql/graphql-js#371
Now have a better understanding of why those invariants were there - because `instanceof` is used in many other places, removing these doesn't allow the use of GraphQLSchema defined by other versions of graphql-js because eventually checks like `instanceof GraphQLList` or `instanceof GraphQLObjectType` will fail for the same reasons - but at that point the produced errors may be far more mysterious. These invariants were added to at least give a clear error message early on.
If we want to enable this, we'll have to completely remove `instanceof`.

Revert "Remove all 'instanceof GraphQLSchema' checks"

---

src/utilities/__tests__/buildASTSchema-test.js
src/utilities/buildASTSchema.js

`buildASTSchema` used to not regard directives in 0.4.x, just always including only `@skip` and `@include`. Since 0.5.0 included the ability to use directives in the experimental schema language, existing use of this tool found no defined directives and therefore excluded these two built-ins.
This fixes the issue by implicitly adding these built-in directives if they were not explicitly defined.

BUG: Ensure building AST schema does not exclude @skip and @include

---

src/index.js
src/type/index.js

This exports the ability to define new directives as well as access the built-in @skip and @include definitions.

Export directive definitions.

---

src/execution/values.js
src/index.js
src/type/directives.js
src/type/index.js
src/type/schema.js
src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/schemaPrinter-test.js
src/utilities/buildASTSchema.js
src/utilities/schemaPrinter.js

This adds a new directive as part of the experimental schema language:
```
directive @deprecated(reason: String = "No longer supported") on FIELD_DEFINITION | ENUM_VALUE
```
It also adds support for this directive in the schemaPrinter and buildASTSchema.
Additionally exports a new helper `specifiedDirectives` which is encoured to be used when addressing the collection of all directives defined by the spec. The `@deprecated` directive is optimistically added to this collection. While it's currently experimental, it will become part of the schema definition language RFC.

Deprecated directive

---

src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js
src/validation/rules/OverlappingFieldsCanBeMerged.js

This improves the overlapping fields validation performance and improves error reporting quality by separating the concepts of checking fields "within" a single collection of fields from checking fields "between" two different collections of fields. This ensures for deeply overlapping fields that nested fields are not checked against each other repeatedly. Extending this concept further, fragment spreads are no longer expanded inline before looking for conflicts, instead the fields within a fragment are compared to the fields with the selection set which contained the referencing fragment spread.
e.g.
```graphql
{
same: a
same: b
...X
}
fragment X on T {
same: c
same: d
}
```
In the above example, the initial query body is checked "within" so `a` is compared to `b`. Also, the fragment `X` …

Validation: improving overlapping fields quality

---

package.json

We currently get a bunch of graceful-fs deprecated warnings when running "npm install". This change fixes two such warnings by updating babel-cli and flow-bin.

Update babel-cli and flow-bin package references

---

.babelrc
.npmignore
package.json

This moves babel config to the babelrc and unincludes it from the npm module.
For most use cases, this shouldn't make any difference. But, some build tools will look through node_modules and barf if there is a package.json with a babel config in there. In particular, jest has a  react-native-specific hack that does this. In particular, any project using jest, react-native, and the graphql module doesn't work at the moment. E.g. we had to do a similar thing to fix enzyme. https://github.com/airbnb/enzyme/pull/311

move babel config to the babelrc

---

package.json

Reverts graphql/graphql-js#388
Upgrading flow-cli introduces new errors (possibly real) and breaks test runs.

Revert "Update babel-cli and flow-bin package references"

---

src/validation/__tests__/validation-test.js

- Changes in #355, which improved validation messages, should had broken the test.
- But `expect().to.deep.equal()` checks for the right number of errors  but does not check for equality of error messages.
Notes:
- `npm run check` complained that the error messages were too long; broke each error into 2 lines.
PS: Can someone with travis access re-run the build? It failed for only one of the environment `nodejs 4`, seems like `flow` didn't get installed properly (`ENOENT` error)

Fix test assertions for validation test when using custom TypeInfo

---

README.md
src/execution/execute.js
src/type/introspection.js

In some environments it's preferable to only use ASCII characters. This changes
all non-ASCII characters to ASCII alternatives.

Use only ASCII characters

---

src/error/GraphQLError.js

Some libraries use a brand-checking to determine if something is an Error which specifically looks to see if `stack` is a writable property.
Fixes #439

Make GraphQLError#stack a writable property.

---

src/type/__tests__/enumType-test.js
src/type/definition.js
src/type/introspection.js
src/utilities/__tests__/astFromValue-test.js
src/utilities/astFromValue.js
src/utilities/schemaPrinter.js
src/utilities/valueFromAST.js

A bug was reported in #435 and reproduced in #438 which illustrates an issue where defaultValue would serialize incorrectly or even throw an invariant violation when working with input objects or enums backed by values other than their names.
The root of the issue is that astFromValue accepts an *internal* value, but then produces an AST directly from that value without serializing it to an *external* value first via calling `type.serialize(value)`. This critical missing step is responsible for the reported issue.
In order to fix correctly, this refactored this method to be a closer dual to [`valueFromAST`](https://github.com/graphql/graphql-js/blob/master/src/utilities/valueFromAST.js), relying on the GraphQL type rather than the JavaScript type to guide coercion. As a consequence, …

[FIX] astFromValue uses `serialize()` and requires type.

---

package.json
resources/mocha-bootload.js
src/error/GraphQLError.js
src/execution/__tests__/abstract-test.js
src/execution/__tests__/executor-test.js
src/execution/execute.js
src/type/__tests__/enumType-test.js

As brought up in #426, it can be confusing to return instances of `Error` from the `graphql` function since the expectation is that you will call `JSON.stringify` and submit the result to a client. Calling `JSON.stringify` on an instance of `Error` results in `{}` since it has no enumerable properties.
In order to have behavior that matches the GraphQL spec easier to achieve, this makes these two properties enumerable. I think this will be the best of both worlds - anyone who wishes the operate directly on the Error instances will still have the ability to do so (for example, to access the `stack` property), but it can still be converted to JSON directly and get a spec-compliant result.

Add `message` and `locations` as enumerable properties on GraphQLError.

---

src/type/__tests__/serialization-test.js
src/type/scalars.js
src/utilities/__tests__/astFromValue-test.js

As illustrated by #391, when a value is provided for a field of type Int which cannot be represented by Int (e.g. a 64bit value is provided to the 32bit Int type), then the spec claims a field-error should be raised however currently `null` is returned directly instead.
Spec: https://facebook.github.io/graphql/#sec-Int
This updates to throw meaningful error messages when invalid Int and Float values cannot be coerced without losing information.

[FIX] Throw field errors when failing to coerce Int/Float.

---

src/error/GraphQLError.js
src/error/locatedError.js
src/execution/__tests__/executor-test.js
src/execution/execute.js
src/type/__tests__/enumType-test.js

Error locations were previously only being added due to async value resolution and not during value completion. This meant if an error was raised due to an incorrect response from a resolver function that it would not have gotten wrapped in a location-aware GraphQLError object.
This includes a new intermediate phase which catches and assigns these locations before further propogating the error.
This also assigns non-enumable property for `originalError` so it is not included during JSON.stringify.

[FIX] Include locations for errors related to failed value completion.

---

.flowconfig
package.json
src/execution/__tests__/lists-test.js
src/execution/execute.js
src/execution/values.js
src/utilities/astFromValue.js
src/utilities/isValidJSValue.js

This adds support for returning any Iterable from a resolver function expecting a List type, rather than only Arrays, by using the `iterall` library.
This also adds support for accepting any Iterable as input for arguments or variable values which expect a List type.
Fixes #300

[RFC] Support iterable values as inputs and outputs

---

src/error/GraphQLError.js

Many libraries (such as https://github.com/PolymerLabs/stacky) expect an error's stack to be of a certain format. Currently this code sets it to the message, which causes exceptions in formatters. 
It also obscures the actual location of where the error is thrown, since it overwrites the stack property of the inherited Error.

Use the Error base class stack property

---

src/utilities/__tests__/extendSchema-test.js
src/utilities/extendSchema.js

https://github.com/graphql/graphql-js/issues/450
This changes the extendSchema utility to accept and process new
Directive definitions. Existing directives cannot be extended or
replaced (should throw an error in such cases).
See extendSchema-test for examples.

Update extendSchema to support new Directives

---

src/index.js
src/language/__tests__/lexer-test.js
src/language/__tests__/parser-test.js
src/language/__tests__/printer-test.js
src/language/__tests__/schema-parser-test.js
src/language/__tests__/schema-printer-test.js
src/language/ast.js
src/language/index.js
src/language/lexer.js
src/language/parser.js

This refactors the tokenizer, simplifying both tokenizer and parser code slightly (fewer utility functions) and returns tokens as part of the AST's `loc` information. 
Location info is now created as an Object with non-writable defined properties, only `start` and `end` are enumerable. That removes the need for the `noSource` option, which was really only added to not choke JSON.stringify/util.inspect on the full source. Location info now also includes the `startToken` and `endToken` associated with every node in the AST, providing easy access to the token stream from any point.
Tokens also have gained a few new properties: `line` for the 1-indexed line they appear on and `prev`/`next` to navigate the dll of Tokens.
Finally, this introduces three new Token types: `<SOF>` for the empty …

Refactors tokenizer to emit a Token double-linked-list

---

src/validation/__tests__/NoUnusedVariables-test.js

There is already a `it('multiple variables not used'` earlier in the test for a plain graph. Clarifying that this test is about a graph with fragments.

[test] [minor] Make test name unique

---

src/execution/__tests__/resolve-test.js
src/execution/execute.js

Right now the default resolver is really handy in some cases. If you have a field that uses args and/or context, though, you can't use a default resolver because the default resolver just throws them away, even if there's a function hanging off the source object. There's no real benefit to that behavior, so this PR passes args and context along to the function hanging off the source object if there is one. This makes it easier to use es6 classes in conjunction with graphql.js.
This is backward compatible unless you happened to use a default resolver method which relied on not receiving any arguments despite the schema allowing arguments, which seems perverse enough that we can ignore that case.

Make the default resolver use args and context

---

src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/__tests__/schemaPrinter-test.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js
src/utilities/schemaPrinter.js

Adds descriptions to the schema language via docblocks
This adds descriptions to the `buildASTSchema` (string->schema) and `schemaPrinter` (schema->string) via walking the previous full-line contiguous comment block. This is dependent on #463.
> NOTE: This is a stacked diff - only changes to src/utilities belong to this PR

Schema lang descriptions

---

src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/buildASTSchema.js
src/utilities/schemaPrinter.js

This is a result of a conversation I had with @lacker that we should provide a stronger opinion on what to name the root types, and then advantage that opinion. Here's the result of that:
If you use the type names `Query` and `Mutation` for your root types, then printing the schema or parsing a schema IDL can omit the `schema { query: Query, mutation: Mutation }` boilerplate. If your root type names are anything other than these, then you have to include it.
There doesn't seem to be a significant downside to this except for the relative complication of understanding why sometimes a `schema {}` description is included and sometimes it isn't.
**Note: It's okay to make these changes now since the IDL is still technically experimental (It's not in the spec) but we want to nail down the spec'd …

Advantage common convention for naming root types.

---

src/type/definition.js
src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/buildClientSchema-test.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/buildASTSchema.js
src/utilities/buildClientSchema.js
src/utilities/extendSchema.js

Right now our generated schemas (built from introspection, built from AST) explicitly do not allow their use in execution. They throw as soon as any resolver function is called. This conservative behavior was appropriate for early versions where we wanted to limit the surface area under use. Today it's becoming more clear that there are immediately valuable use cases for using generated schema in execution.
The ability to execute will still be somewhat limited: generated schema do not contain enough information to resolve Interface and Union types, and coerce values for custom Scalars.
Case 1: Resolvers live in your domain models, AST schema is useful:
```js
const schema = buildASTSchema(parse(`type MyTypeSystem { ... }`));
class MyObject { ... }
class MyQueryRoot { ... }
const response = …
```

[RFC] Allows use of generated schemas for execution.

---

src/index.js
src/utilities/__tests__/buildASTSchema-test.js
src/utilities/buildASTSchema.js
src/utilities/index.js

Pretty simple - this just adds a `buildSchema` function that composes `buildASTSchema` and `parse`, as mentioned in the discussion on https://github.com/graphql/graphql-js/pull/469 . This makes a "hello world" experience one notch simpler; product developers can use this mechanism to build their schemas while ignoring the intermediate ast format altogether.

buildSchema helper function

---

src/index.js
src/utilities/__tests__/separateOperations-test.js
src/utilities/index.js
src/utilities/separateOperations.js

A typical task using GraphQL at Facebook looks something like:
1. Load and parse all .graphql files which may contain operations or fragments.
2. Use `concatAST` to produce one AST that contains all operations and fragments.
3. Separate this all-encompasing AST into individual ASTs that represent each operation which could be sent to the server in isolation.
`separateOperations` fulfills this third step.

separateOperations - a utility function for splitting an AST

---

package.json
src/error/GraphQLError.js
src/execution/execute.js
src/language/index.js
src/language/kinds.js
src/type/scalars.js
src/type/schema.js
src/utilities/isValidJSValue.js
src/utilities/isValidLiteralValue.js
src/validation/rules/OverlappingFieldsCanBeMerged.js

Update to Flow 0.32, and update some type definitions with 0.32.(Basically most of those errors in 0.29 are caused by missing `@flow` in ` src/language/kinds.js `).

Update to Flow 0.32

---

src/error/GraphQLError.js

Bluebird will throw an error if an error used to reject a promise has `writable: true` but not `configurable: true`
See: 
https://github.com/graphql/graphql-js/issues/439
https://github.com/petkaantonov/bluebird/pull/1238
Fixes #488

Add 'configurable: true' to GraphQLError stack property

---

src/error/GraphQLError.js
src/error/__tests__/GraphQLError-test.js

Because the GraphQLError constructor filtered out falsy values for
node.loc.start, that would also filter out 0.

Fix GraphQLError missing positions/locations when node.loc.start === 0

---

src/index.js
src/language/__tests__/parser-test.js
src/language/index.js
src/language/parser.js

The parser already exported a convenience function `parseValue()` which allows you to parse GraphQL value literals independently of parsing entire documents. This adds similar functionality for `parseType()` - which parses type references like `[Int!]`.
This also adds a few tests and slightly improved documentation.

Adds parseType()

---

src/index.js
src/type/definition.js
src/type/schema.js
src/utilities/__tests__/schemaComparisons-test.js
src/utilities/index.js
src/utilities/schemaComparisons.js

This PR introduces some checks that can be used to help verify if changes to a schema are "safe". The idea is that you generate a `GraphQLSchema` object that represents the schema before and after a schema change (for example by using `buildClientSchema`). You can then pass the `oldSchema` and `newSchema` into these utility functions. The functions each check for different types of breaking changes, i.e. changes in the `newSchema` that are not backwards compatible with `oldSchema`. They can be used to help prevent regressions caused by unsafe schema changes that would break older versions of clients.

Add utility functions to compare schemas

---

src/execution/__tests__/abstract-test.js
src/execution/execute.js
src/type/definition.js

This change permits `resolveType` functions to return the "name" string of a type definition rather than the concrete `GraphQLObjectType` instance. 
This is particularly useful when the `resolveType` function doesn't have access to the type instances in the immediate closure scope. While it's possible to accomplish the same with `info.schema.getType` in the resolve function, being able to return a string and have the executor figure it out felt a bit nicer.
Example:
```js
const PetType = new GraphQLInterfaceType({
name: 'Pet',
resolveType(obj) {
return obj instanceof Dog ? 'Dog' :
obj instanceof Cat ? 'Cat' :
null;
},
fields: {
name: { type: GraphQLString }
}
});
```

Allow resolveType to return a type name string

---

.travis.yml

This removes the `join` / `part` steps of this:
See https://docs.travis-ci.com/user/notifications#IRC-notification for more information.
Note that this requires removing the `n` flag on the IRC channel.
See https://freenode.net/kb/answer/channelmodes
> n (prevent external send): Users outside the channel may not send messages to it. Keep in mind that bans and quiets will not apply to external users.
Apologies if this was already suggested and declined in the past, I did not find this on the closed PRs or issues.

Allow Travis CI's IRC bot to post without joining

---

src/type/definition.js

Types with names like `InputObjectConfig` are inconsistent with all other type names. This makes the types awkward to import and use. This may be considered a breaking change (although I’d venture to believe very few people if any are importing this specific file to get at the types). If you’d like to mitigate breakage we could re-export aliases like so:
```js
export type InputObjectConfig = GraphQLInputObjectTypeConfig
```

add ‘GraphQL’ prefix to input object types

---

src/validation/__tests__/UniqueDirectivesPerLocation-test.js
src/validation/rules/UniqueDirectivesPerLocation.js
src/validation/specifiedRules.js

This implements https://github.com/facebook/graphql/pull/229, in order to adhere with the October2016 edition of the spec.

Adds Unique Directives Validation Rule.

---

src/error/locatedError.js
src/execution/__tests__/abstract-test.js
src/execution/__tests__/variables-test.js
src/execution/execute.js
src/execution/values.js
src/utilities/__tests__/valueFromAST-test.js
src/utilities/buildASTSchema.js
src/utilities/isValidJSValue.js
src/utilities/isValidLiteralValue.js
src/utilities/valueFromAST.js

Before this diff, bad input to arguments and variables was often ignored and replaced with `null` rather than rejected. Now that `null` has a semantic meaning, and thanks to some recent changes to the spec (https://github.com/facebook/graphql/pull/221) - changes are necessary in order to enforce the stricter coercion rules.
This diff does the following:
* Implements the CoerceArgumentValues as described in the spec.
* Implements the CoerceVariablesValues as described in the spec.
* Alters valueFromAST and coerceValue (dual functions) to strictly enforce coercion, returning `undefined` implicitly when they fail to do so. It also fixes issues where undefined returns were being ignored as items in a list or fields in an input object.

Enforces input coercion rules.

---

src/index.js
src/utilities/index.js
src/utilities/schemaPrinter.js

Users may generate graphql types from some models (eg. from [mongoose](https://github.com/nodkz/graphql-compose-mongoose)). And want to have ability to see what they got in human view.
My several related issues:
https://github.com/nodkz/graphql-compose/issues/27#issuecomment-258618998
https://github.com/nodkz/graphql-compose/issues/17

Expose `printType` for test/debug purposes.

---

src/execution/__tests__/executor-test.js
src/execution/execute.js
src/execution/index.js
src/index.js
src/type/definition.js
src/type/index.js

This is a performance improvement to the execution path that removes the need for creating a new array to represent the response path for each resolved field in the response. Instead this creates a single-linked-list which is naturally persistently immutable.
This exposes a breaking change: if you relied on `resolve(_, _, _, { path }) {` then you'll find `path` in this linked list format instead of an array.

Use linked-list to represent response path.

---

src/type/__tests__/introspection-test.js
src/type/introspection.js
src/utilities/__tests__/buildClientSchema-test.js
src/utilities/buildClientSchema.js

- introspection should return null if there is no default value and the string "null" if there is a default value that is null
- buildClientSchema should translate defaultValue "null" to null (as it already does) and null to undefined (fixed here)

differentiate between input values with no default and with default = null

---

src/index.js
src/type/definition.js
src/type/index.js

Adds helper functions for asserting that a type instance conforms to the various categories of types, e.g. `assertXXXType(type: ?GraphQLType): GraphQLXXXType`.

Add assertXXXType helpers

---

src/execution/__tests__/mutations-test.js
src/execution/execute.js
src/execution/values.js
src/type/definition.js
src/type/introspection.js
src/utilities/TypeInfo.js
src/validation/rules/OverlappingFieldsCanBeMerged.js
src/validation/validate.js

This adds additional type information to field resolvers, such that source and context get slightly more appropriate types.
This partially improves one of the issues raised in #574

Add TContext to field resolvers

---

src/type/definition.js

Add TContext to type resolvers

---

src/type/definition.js
src/type/introspection.js

This changes the flow types from an object of mixed values to an object of any values. This is explicitly less type safe, however is way more ergonomic and better matches the previous behavior before flow types were exported.
This was suggested in #554 and partially implements #574

Type field arg values as "any"

---

src/type/definition.js

This adds toJSON() and inspect() methods on all types which shares the same function as toString(). This means that converting a GraphQL type to JSON or inspecting it with console.log (in Node) will produce something more meaningful than the implementation details of the type.
Closes #568

Implement toJSON and inspect on all types.

---

src/__tests__/starWarsData.js
src/__tests__/starWarsIntrospection-test.js
src/__tests__/starWarsQuery-test.js
src/__tests__/starWarsSchema.js
src/__tests__/starWarsValidation-test.js
src/execution/__tests__/executor-test.js

This cleans up the top level tests and flow-types them. It also moved one unrelated test into a more appropriate location.
Inspired by #425

Flow type tests & reorganize

---

src/index.js
src/type/definition.js
src/type/index.js

Completes the set of isXxxType/assertXxxType helpers. Useful for building type repositories and the like.

Add isNamedType and assertNamedType helpers

---

src/type/__tests__/validation-test.js
src/type/definition.js
src/type/introspection.js
src/utilities/assertValidName.js

The spec describing introspection (http://facebook.github.io/graphql/#sec-Naming-conventions) restricts naming non-introspection related artifacts starting with __. This enforces that specification.

FIX: Uphold spec for non-validation names not beginning with __

---

src/execution/__tests__/executor-test.js
src/execution/execute.js

Currently, `buildExecutionContext` throws a null reference error
`Cannot read property 'definitions' of null`
when `document` is undefined. Instead, we should throw a friendlier error message.
Also fixes apollostack/graphql-server#112
🍺

Make executor throw if no document is provided

---

src/execution/execute.js

When using `buildSchema` and then passing a `root` object to `graphql` you don't get access to the `GraphQLResolveInfo` object which seems to be the only way to perform introspection on the query.

Pass GraphQLResolveInfo object to resolve functions in defaultFieldResolver

---

src/error/GraphQLError.js

Fix circular dependency that fails the code after compiling the library with Rollup (because of https://github.com/rollup/rollup-plugin-commonjs/issues/105)

chore(circ-dep): fixed circular dependancies

---

src/type/__tests__/enumType-test.js
src/type/definition.js
src/utilities/TypeInfo.js

This adds two new APIs to the schema utilities. One is for `TypeInfo` which is typically used alongside an AST visitor - now you can call `getEnumValue()` to get the GraphQLEnumValue instance referred to by the EnumValue ast node under visit.
Also, `EnumType.getValue(name)` accepts the name of an enum value and returns the GraphQLEnumValue instance associated with it. Beats running a `getValues().find(...)`.

TypeInfo.getEnumValue() and EnumType.getValue(name)

---

.eslintrc
src/type/__tests__/validation-test.js
src/type/definition.js

If a field's resolver is set to a constant value like "{}" we get a runtime error, "resolveFn is not a function". We can easily detect this case when we validate fields during schema creation. This PR adds a new validation rule to check that the resolve definition is a function.

Add resolver validation, check if value is a function

---

src/index.js
src/utilities/__tests__/findDeprecatedUsages-test.js
src/utilities/findDeprecatedUsages.js
src/utilities/index.js

This adds a utility for finding field and enum deprecation usages. The function signature is very similar to validation which should make using it easy where validation is already being used in a reporting flow.
Closes #389

findDeprecatedUsages()

---

src/type/__tests__/validation-test.js
src/type/definition.js

GraphQLInputObjectTypes are confusing to new users of GraphQL. One general distinction between GraphQLObjectType and GraphQLInputObjectType is the use of resolvers: I can't think of a valid case for them to be present on GraphQLInputObjectType. Let's validate this during schema construction and throw a helpful error.

Validate Input Types do not define resolvers

---

src/execution/__tests__/abstract-promise-test.js
src/execution/execute.js
src/type/definition.js

Hello, 
The idea behind this PR is to allow `GraphQLObjectType#isTypeOf`, `GraphQLInterfaceType#resolveType` and `GraphQLUnionType#resolveType` to return a Promise.
The PR consists of:
- Changes to `execute.js` to support the new promise feature.
- New tests: Promise.resolve duplicates of the existing ones about `isTypeOf` and `resolveType` + new ones to test the cases where the promise is rejected.
This relates to issue #398. Use case is the following: 
For some projects fetching data can be expensive. To prevent that, the 'source' passed to resolveFns can be thought as an ID string referencing remote data, so the fields resolve only what is needed based on that ID. It works fine, except when abstract types require a sync resolving of the type behind an ID string.
The use case at my …

Allow `isTypeOf` and `resolveType` to return a Promise

---

.babelrc
package.json
yarn.lock

This is primarily getting hit when using graphql-js in weird or old environments where ES6 exports end up using `default` a bunch. Better safe.

Quotes reserved literals when used in properties.

---

src/type/__tests__/validation-test.js
src/utilities/assertValidName.js

This unbreaks various uses of graphql-js which were defining fields with __ while retaining some form of reporting warning for non-compliant use.
Fixes #690

Convert error to warning for non-compliant use of __

---

src/utilities/TypeInfo.js
src/validation/rules/FragmentsOnCompositeTypes.js

Previously we just coerce these values to the expected types, record them and carry on. However that is not safe and results in TypeInfo potentially returning invalid types when traversing an invalid query.
This instead checks the type before inserting it, upholding type safety.
There was one validator which was taking advantage of the unsafe behavior, so I re-wrote it slightly to be type safe.

Fix: Type safety for TypeInfo.

---

src/type/definition.js
src/validation/rules/ScalarLeafs.js

This was ambiguous before. Other isCompositeType / isAbstractType checks below do not include named type unwrapping, and it did not match the type definition above. Only one callsite actually relied on named type unwrapping, so moved this check there.

Fix: isLeafType matches type definition.

---

src/execution/execute.js

This replaces the isThenable boolean check with a "getIfPromise" function. It's essentially the same, but rather than returning boolean, it's the identify function when it would have returned true, and returns void otherwise. That lets us give it a better type signature that Flow can do more with.
Open to feedback on this one, and open to bikeshedding on the name of this new function.

RFC: More flow-friendly thenable checking.

---

src/type/__tests__/validation-test.js
src/type/definition.js

Context: a circular dependency problem while using graphql-relay caused `nodeField` to be undefined.
Unfortunately, when a field config is undefined you don't get a useful stack trace:
```sh
/Users/cesarandreu/Developer/graphql-project/node_modules/graphql/type/definition.js:330
(0, _invariant2.default)(!fieldConfig.hasOwnProperty('isDeprecated'), type.name + '.' + fieldName + ' should provide "deprecationReason" instead ' + 'of "isDeprecated".');
^
TypeError: Cannot read property 'hasOwnProperty' of undefined
at /Users/cesarandreu/Developer/graphql-project/node_modules/graphql/type/definition.js:330:42
at Array.forEach (native)
at defineFieldMap (/Users/cesarandreu/Developer/graphql-project/node_modules/graphql/type/definition.js:327:14)
at GraphQLObjectType.getFields …
```

Improved error message for undefined field config

---

src/utilities/separateOperations.js

The separateOperations function does a pass over all definitions of a document for each operation in the document. This is painful for big documents. Since the function already visits each definition node, we can cache the visited nodes. Then instead of passing over all top-level definitions in the document and removing those not in an operation's depgraph, we can pass over the (often much smaller) list of definition names in the depgraph and retrieve the definitions by name from the cache.
Ran flow check and separateOperations-test.js

Improve perf of separateOperations

---

src/type/__tests__/validation-test.js
src/utilities/__tests__/assertValidName-test.js
src/utilities/assertValidName.js

A few things here:
- Downgrade `console.error` to `console.warn`.
- Strip "Error: " prefix from messages that can trip up CIs.
- Note in warning message that it will eventually become a hard error.

Soften name validation warnings to avoid CI issues

---

src/utilities/__tests__/extendSchema-test.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js

There isn't a way to extend a schema with types that contains deprecated fields/enum values as `extendSchema` util function ignores the `@deprecated` directive. This fixes it.

allow deprecated fields/values to be extended

---

src/validation/rules/UniqueFragmentNames.js
src/validation/rules/UniqueOperationNames.js

Before this change there was:
- There can be only one argument named ...
- There can be only one input field named ...
- There can be only one variable named ...
- There can only be one fragment named ...
- There can only be one operation named ...
Now the last two match the others.

Unify wording in error messages.

---

src/utilities/__tests__/findBreakingChanges-test.js
src/utilities/findBreakingChanges.js

Addresses https://github.com/graphql/graphql-js/issues/783. When I initially wrote the `findBreakingArgChanges`, doing comparison checks on the arg instances themselves was the state-of-the-art. It looks like the `findFieldsThatChangedType` now references the `name` property of the types to check if changes happened in a breaking way, which is what I've done in this PR.
Not sure how I can assert this correction in unit-tests... would be happy for feedback

Moving from raw instance check to name checks in `findBreakingArgChanges`

---

.eslintrc

Silences:
The babel/no-await-in-loop rule is deprecated. Please use the built
in no-await-in-loop rule instead.

Silence eslint deprecation warning

---

src/index.js
src/validation/index.js
src/validation/specifiedRules.js

It's become relatively standard to create a whitelist or blacklist of validation rules, and reaching into the package per rule can get messy. This exports all the rules at the higher levels of submodule and module as well to make this easier.
For explaination of whitelist of blacklist:
```js
// Whitelist
import { specifiedRules, ScalarLeafsRule } from 'graphql';
// A ruleset which only runs one rule.
const whitelistRules = [ ScalarLeafsRule ];
```
```js
// Blacklist
import { specifiedRules, ScalarLeafsRule } from 'graphql';
// A ruleset which only runs all but one rule.
const blacklistRules = specifiedRules.filter(rule => rule !== ScalarLeafsRule);
// Note: the wrong way to do a blacklist would be to import and specify all
// but one rule. That's a whitelist and would fail to pick up any …
```

[RFC] Export all validation rules directly

---

src/type/__tests__/validation-test.js
src/type/definition.js

From [spec](https://github.com/facebook/graphql/blob/master/spec/Section%202%20--%20Language.md#enum-value):
```
EnumValue : Name but not true, false or null
```
\+ Move one of test cases into proper location

Forbid 'true', 'false' and 'null' as names for Enum value

---

package.json
src/error/GraphQLError.js
yarn.lock

Since GraphQLError is declared then defined separately, Flow might infer that the constructor is not being used correctly via wrong arity, or might not detect improper use if an incorrect type is provided. This fixes that by adding a contructor to the declared type.
Also bumped the version of flow to ensure this change passes both the existing and most recent flow version

Add constructor to GraphQLError class flow type

---

src/type/__tests__/validation-test.js
src/type/definition.js

For details please see this PR: https://github.com/facebook/graphql/pull/262

Forbid object to declare that it implements same interface twice.

---

src/validation/__tests__/validation-test.js
src/validation/validate.js

This is motivated by cases where you want to supply a custom TypeInfo instance when validating a document.

Allow passing custom TypeInfo to validate()

---

src/execution/execute.js
src/execution/values.js
src/type/definition.js
src/type/introspection.js
src/utilities/TypeInfo.js
src/utilities/buildASTSchema.js
src/utilities/buildClientSchema.js
src/utilities/extendSchema.js
src/utilities/findBreakingChanges.js
src/utilities/typeComparators.js
src/utilities/typeFromAST.js
src/validation/rules/FieldsOnCorrectType.js
src/validation/rules/OverlappingFieldsCanBeMerged.js

This uses a pre-release flow feature to provide predicate functions with more type checking power. It also breaks apart some functions into multiple declare function statements for cases where more specific input types result in more specific output types.

Use flow %checks to reduce occurance of :any

---

src/type/__tests__/definition-test.js
src/type/definition.js

Allow for nullish values when defining enums

---

src/utilities/__tests__/buildASTSchema-test.js
src/utilities/buildASTSchema.js

A GraphQL schema can't have more than one definition of the same type.
Facebook runs an integration test to prevent this:
https://github.com/graphql/graphql-js/issues/223#issuecomment-265366200
With this PR the `buildASTSchema` step throws, causing any tests that load the schema to fail.

Forbid duplicate type definitions

---

src/execution/execute.js

It’s hard to notice `errors` property if it is hidden under multiple screens of JSON.
For example, if you run [this query](http://graphql.org/swapi-graphql/?query=%7B%0A%20%20allPeople%20%7B%0A%20%20%20%20people%20%7B%0A%20%20%20%20%20%20height%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) you will see the following:
And only if you scroll a couple pages down you will see an error what is bad DX.
To fix this I just changed the order of `errors` and `data` fields so result of the same query look like this:

Make 'errors' top property in the response object.

---

src/index.js
src/subscription/index.js
src/subscription/subscribe.js

Follow up PR for https://github.com/graphql/graphql-js/pull/846 solving last comments

feat(subscriptions): added code comments

---

src/type/__tests__/serialization-test.js
src/type/scalars.js
src/utilities/__tests__/astFromValue-test.js
src/utilities/__tests__/isValidJSValue-test.js

This fixes an issue with coercing Int values when provided a floating point value which disagrees with the spec definition.
Updates test cases which were along the same incorrect line.
Note: this is technically a breaking change
Fixes #827

Spec compliance: coercion of Int values

---

src/subscription/subscribe.js

There was a secondary function in subscribe.js which doesn't correspond to a spec function or provide much value. It was an artifact of an earlier implementation. Collapsing it into the defined createSourceEventStream makes the alignment to spec more clear. It also moves this function below `subscribe` in the file, making its purpose more clear.

Simplify subscriptions.

---

src/type/definition.js
src/utilities/isValidJSValue.js
src/utilities/isValidLiteralValue.js
src/utilities/valueFromAST.js

Used for more semantically correct validity checking after #848

Adds `isValidValue` and `isValidLiteral` to Scalar and Enum types.

---

src/language/source.js
src/type/definition.js
src/type/directives.js
src/type/schema.js
src/utilities/TypeInfo.js
src/utilities/extendSchema.js
src/validation/rules/OverlappingFieldsCanBeMerged.js
src/validation/validate.js

Fixes #857
This fixes an issue where flow implicitly types new Class as `any` if the constructor is not typed to return `void` (https://github.com/facebook/flow/issues/2748).

Add void returns to constructors

---

src/jsutils/keyMap.js
src/jsutils/keyValMap.js
src/type/definition.js
src/utilities/extendSchema.js
src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js
src/validation/rules/OverlappingFieldsCanBeMerged.js
src/validation/validate.js

Replaces all places where `{}` is used as an empty string map with `Object.create(null)`.

Fix: OverlappingFieldsCanBeMerged on js keyword named fields

---

src/execution/__tests__/executor-test.js
src/execution/execute.js
src/graphql.js
src/subscription/subscribe.js

This adds an argument to `execute()`, `createSourceEventStream()` and `subscribe()` which allows for providing a custom field resolver. For subscriptions, this allows for externalizing the resolving of event streams to a separate function (mentioned in #846) or to provide a custom function for externalizing the resolving of values (mentioned in #733)
cc @stubailo @helfer

Allow providing custom default field resolver.

---

src/graphql.js
src/language/__tests__/lexer-test.js
src/language/__tests__/parser-test.js
src/language/source.js

This fixes a use case when using named graphql files as a source of truth when calling the graphql() function, using those names in reporting.
Potentially unit-test breaking: may change the error message content from using parse() directly.

Allow graphql() to accept a Source instance.

---

.eslintrc
src/__tests__/starWarsQuery-test.js
src/execution/__tests__/executor-test.js
src/execution/execute.js
src/graphql.js
src/subscription/__tests__/subscribe-test.js
src/subscription/subscribe.js
yarn.lock

As well as execute() and subscribe()
Closes #356

Allow providing an object of arguments to graphql().

---

src/utilities/typeFromAST.js

Flow v0.47.0 finds 3 errors in master. This is important to fix, because the graphql npm 
module ships with types, so anyone who uses the graphql npm module will get errors 
when upgrading to Flow v0.47.0. The new errors [look like this](https://gist.github.com/85d7f03510760dd223e968d2e92e7712).
When investigating, I found that `typeFromAST()` was doing something a little
odd. I believe it was trying to declare itself as an overloaded function, but
instead it was declaring an overloaded function and then shadowing it with the
exported function.
When it's properly fixed, it exposes 26 errors, which is a little much for me
to fix right now. So instead, I'm sabotaging its type completely, which will avoid errors in 
either v0.46.0 or v0.47.0

Avoid new Flow errors with v0.47.0

---

src/index.js
src/subscription/__tests__/subscribe-test.js
src/subscription/subscribe.js
src/validation/__tests__/SingleFieldSubscriptions-test.js
src/validation/index.js
src/validation/rules/SingleFieldSubscriptions.js
src/validation/specifiedRules.js

As per the spec, a subscription should simply use the first field defined, and not make any other assertions during the Subscribe operation. Instead, a validation rule should detect this and report it.

Spec compliance: Validation error on multi-field subscription

---

src/execution/__tests__/executor-test.js
src/execution/__tests__/variables-test.js
src/execution/execute.js
src/graphql.js
src/language/__tests__/parser-test.js
src/language/parser.js

This ensures failures related to buildExecutionContext() yield a GraphQL Result with errors rather than a thrown error from execute(), and handles top level error catching and nulling within executeOperation() instead of execute() for better alignment to spec text.
This helps align to the idea that internal errors throw and GraphQL user errors are returned within the GraphQL Result.

Refactor executeOperation

---

.flowconfig
src/execution/execute.js
src/graphql.js
src/subscription/subscribe.js

Fixed a bunch of flow errors observed after turning on `const_params` experimental flag, by delegating the correct arguments to another function (`Impl` functions).

fix flow errors from turning on const_params experimental flag

---

src/subscription/__tests__/subscribe-test.js
src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/__tests__/schemaPrinter-test.js
src/utilities/schemaPrinter.js

Sort the fields of an object similar to how types are being sorted.

Sort fields before printing to get a more stable diff

---

src/validation/__tests__/ArgumentsOfCorrectType-test.js

This tests are used to generate json with test cases for alternative realization of graphql (https://github.com/neelance/graphql-go). 
As for this repo pull request will add test case for addional variants of int and float values (such cases was not supported by alternative one).

add test cases to check support of negative floats and ints

---

src/index.js
src/utilities/__tests__/findBreakingChanges-test.js
src/utilities/findBreakingChanges.js
src/utilities/index.js

This PR shores up more of the holes in findBreakingChanges that were pointed out by @OlegIlyenko in https://github.com/graphql/graphql-js/issues/519.
Here's a list of things that were fixed or added:
- breaking changes to to a field or field arg were not properly detected if the change involved a type modifer like List or NonNull (for example, changing a field from String to [String])
- certain changes are still considered safe, such as moving from NonNull to nullable of the same type for input fields and field args as well as moving from nullable to NonNull for fields on Object and Interface types
- adding a NonNull field arg is now detected as a breaking change
- adding a NonNull field to an input type is now detected as a breaking change
- breaking changes to field args on Interface …

Add more functionality to findBreakingChanges

---

src/language/__tests__/schema-kitchen-sink.graphql
src/language/__tests__/schema-parser-test.js
src/language/__tests__/schema-printer-test.js
src/language/parser.js

Implementation of the leading vertical bar in the language parser.
Issue #897

Add support for leading vertical bar in union types

---

src/language/__tests__/schema-kitchen-sink.graphql
src/language/__tests__/schema-parser-test.js
src/language/__tests__/schema-printer-test.js
src/language/parser.js

This adds a bit of cleanup after #907 for post-commit review:
* Removes unnecessary `peek()`
* Adds leading pipe support to directive locations
* Removes some redundant tests
* Orders tests so similar tests remain together

Second pass after #907

---

src/index.js

Docs at http://graphql.org/graphql-js/utilities/ say "You can import either from the graphql/utilities module, or from the root graphql module" and lists printIntrospectionSchema, yet it is not exported via the root module.

Added printIntrospectionSchema to exports

---

src/type/definition.js
src/utilities/astFromValue.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js
src/utilities/isValidLiteralValue.js
src/utilities/typeFromAST.js
src/validation/rules/KnownArgumentNames.js
src/validation/rules/KnownDirectives.js
src/validation/rules/OverlappingFieldsCanBeMerged.js

At the moment there are two ways 'kinds' are imported:
```js
import * as Kind from '../language/kinds';
```
and
```js
import {
NULL,
ENUM,
// ...
} from '../language/kinds';
```
This PR unifies this by using the first approach. IMHO this PR not only shaves a few lines of code but also improves readability. For example `NULL` as the name is confusing (especially for someone who used C language) and `Kind.NULL` solves this problem.

Unify how 'kinds' are imported

---

src/jsutils/dedent.js
src/language/__tests__/parser-test.js
src/language/__tests__/printer-test.js
src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/concatAST-test.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/__tests__/schemaPrinter-test.js
src/utilities/__tests__/separateOperations-test.js

Multiple places in tests use ES6 multiline strings. Becuase of that indentation is broken:
It's really hard to read this code. When I first time had to read this file it melted my brain. I think this can discourage people from writing tests.
To fix that I added a simple deindentation ES6 string tag `dedent` which I used across the tests. Resulting code looks much better:
The one place where I left strings ident intact is parse tests where the number of character matters and changing indentation there can make it harder to reason about.

Fix identation

---

src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/__tests__/schemaPrinter-test.js
src/utilities/schemaPrinter.js

Fixes issues with field definition order in printed schema not matching source which breaks `s = parse(print(s))`.
Test case: Revert "cycleOutput" test cases from back to correct form, see that they fail. Revert change and see that tests pass.

Fix rearranged schema printing

---

.babelrc
resources/inline-invariant.js

This makes the format string of `invariant` lazily evaluated similar to what the
React transforms do. This makes loading a large schema noticeably faster.
Internal benchmark: https://phabricator.intern.facebook.com/P57579506

Inline invariant transform

---

.babelrc
package.json

This PR removes the babel plugin [transform-es3-property-literals](https://babeljs.io/docs/plugins/transform-es3-property-literals/). It is extraneous compilation since the [quote-props](http://eslint.org/docs/rules/quote-props) ESLint rule defined [here](https://github.com/graphql/graphql-js/blob/master/.eslintrc#L202) already takes care of this.

Remove extraneous transformation

---

src/error/syntaxError.js
src/language/__tests__/lexer-test.js
src/language/source.js

Adds support for providing the location in a file that the graphQL source was located. If the location is provided as part of the source, the line numbers in the formatted errors will be updated to account for the offset.
For example, in file Foo.js:
```
1  const x = 1
2 
3  graphql`
4  query {
5   ?
6  }
7  `
```
The lexer will throw an error with message:
```
Parse error: GraphQLError: Syntax Error Foo.js (5:2) Cannot parse the unexpected character "?".
4: query {
5:  ?
^
6: }
```
It's up to the caller to provide the correct offset in the source.
Not sure if `location` is the best name for the field in the `Source` object. Very open to suggestions!

Account for query's offset in file for errors

---

src/error/syntaxError.js
src/language/__tests__/lexer-test.js
src/language/location.js

I forgot to check that we were on the first line before applying the column offset to the caret. It causes the indicator and reported column number for the error to be off if a locationOffset.column is larger than 1.

Fix incorrect column number in errors

---

src/utilities/__tests__/extendSchema-test.js
src/utilities/extendSchema.js

[`getDirective`](https://github.com/graphql/graphql-js/blob/master/src/utilities/extendSchema.js#L537) from `extendSchema` misses `description` field which is present in `buildASTSchema` ([here](https://github.com/graphql/graphql-js/blob/master/src/utilities/buildASTSchema.js#L274))
Added it + created test to cover this

Fix directive description lost in extendSchema

---

src/utilities/__tests__/findBreakingChanges-test.js
src/utilities/findBreakingChanges.js

Following the discussion in issue #968, adding a new value to an enum is now considered a dangerous change.

Adding a value to an enum is now a dangerous change.

---

src/execution/execute.js
src/index.js

I need this type to apply some transformation on args before passing it to `execute`.
This PR just expose type without changing any run-time behavior.

Export "ExecutionArgs" type

---

src/execution/__tests__/variables-test.js
src/execution/values.js
src/type/scalars.js

Previously, we were using the default JS logic to coerce arrays to strings. This PR detects and disallows conversion of arrays into strings. 
https://github.com/graphql/graphql-js/issues/771

Throw TypeError when coercing an array into a GraphQLString

---

src/utilities/__tests__/findBreakingChanges-test.js

I noticed the findBreakingChanges did not perform a check for the breaking change `INTERFACE_REMOVED_FROM_OBJECT` so I added it:)

Expanded findBreakingChanges test with missing case.

---

.eslintrc
package.json
resources/lint/no-async.js

We want to keep the runtime dependency footprint small, so that means avoiding use of `async` at runtime (which creates a dependency on the Regenerator runtime).
There is no built-in eslint rule for this, so we make a custom one.
Test plan:
Add an `async` function to a file, run `yarn run lint` and see:
graphql-js/src/subscription/subscribe.js
288:1  error  async functions are not allowed outside of the test suite  no-async
✖ 1 problem (1 error, 0 warnings)
Note that no errors are issued for the `async` functions in the test suite.
Closes: https://github.com/graphql/graphql-js/issues/1008

Add linter error preventing use of `async` outside the test suite

---

src/subscription/mapAsyncIterator.js

https://github.com/graphql/graphql-js/issues/1011
This fix attempts to address the flow errors found in libraries that depend on GraphQL-js but do not have `experimental.const_params=true` in their .flowconfig. 
With this explicit null check, I removed the `experimental.const_params=true` option from .flowconfig and saw all tests still pass.

Fix flow error in mapAsyncIterator

---

src/execution/execute.js
src/graphql.js

Simplify code to make it more readable. No changes beyound simple refactoring.

Simplify args processing in "graphql" and "execute" functions

---

.flowconfig
package.json
src/subscription/__tests__/eventEmitterAsyncIterator.js
src/subscription/asyncIteratorReject.js
src/subscription/mapAsyncIterator.js
src/type/definition.js
yarn.lock

Update to flow 0.54

---

src/execution/index.js
src/language/lexer.js
src/subscription/asyncIteratorReject.js
src/subscription/index.js
src/subscription/mapAsyncIterator.js
src/subscription/subscribe.js
src/validation/index.js
src/validation/rules/KnownArgumentNames.js
src/validation/rules/PossibleFragmentSpreads.js

In #988 I forget to export `ExecutionArgs` in all necessary places 🤦‍♂️ 
This one-line PR fix that. 

Add missing ExecutionArgs export

---

.flowconfig
package.json
src/execution/execute.js
src/execution/values.js
src/jsutils/ObjMap.js
src/jsutils/keyMap.js
src/jsutils/keyValMap.js
src/type/definition.js
src/type/schema.js
src/utilities/buildASTSchema.js
src/utilities/separateOperations.js
src/utilities/valueFromAST.js
src/validation/rules/OverlappingFieldsCanBeMerged.js
src/validation/validate.js
yarn.lock

From `flow@0.55.0`, flow started doing a more strict `null` prototype check. Fix them by annotating them with:
```
__proto__: null
```

fix flow errors by annotating null prototypes

---

package.json
yarn.lock

Pulls in necessary fix for breakage in 1.1.2:
https://github.com/leebyron/iterall/commit/325e8ff9e7cd966156688d2012b16f3a588b886a

Upgrade iterall dependency

---

src/execution/execute.js
src/execution/values.js
src/graphql.js
src/subscription/subscribe.js
src/type/definition.js
src/type/schema.js
src/utilities/separateOperations.js

This is a follow up to #1048 which addresses an issue where flow typed resolver functions would need to be aware of the fact that arguments were prototype-less. That's something we maintain for internal usage, but is more burdensome for external use. Instead, this is just more cautious when using these values internally, using hasOwnProperty, but now returns prototypefull objects to user code.
Also follows up with a few additional conversions to ObjMap, such that the only remaining uses of `{[string]: mixed}` are for variables and arguments.

Return normal objects for args and vars.

---

src/type/definition.js

The argument to the GraphQLList class should be of type `GraphQLType`, but
the docs of `GraphQLList` does not reflect this. In this case, `Person` is
`undefined`, when it *probably* should have been `PersonType`.
I wasn't quite sure if this was a typo or not, but I didn't think it would hurt to
send this PR anyway.

docs: Fix possible typo

---

src/utilities/assertValidName.js

When running this library in the browser, Node.js's `process` global is not necessarily defined. Usage in the browser is great for [certain use cases](https://medium.com/taller-team/graphql-today-using-apollo-for-applications-that-still-depend-on-rest-apis-839895ce20d0). This adds a simple check that `process` is defined before using it in `assertValidName.js`

Check if `process` is defined (for usage in the browser)

---

src/utilities/__tests__/buildClientSchema-test.js
src/utilities/buildClientSchema.js

I've seen a few examples of passing bad introspection data to buildClientSchema() result in a hard to understand internal error. This instead prints a more understandable error which includes a print out of the bad value in question. Hopefully this aids debugging.
This also adds a comment to the description of this function recommending that the "errors" field of a server response be checked before continuing to avoid partial results.

Improve errors when receiving bad introspection data

---

src/error/__tests__/locatedError-test.js
src/error/locatedError.js

Elasticsearch [records its index path](https://github.com/elastic/elasticsearch-js/blob/6c4882681fe91c0c90901aa47f68b02dc9ed58f8/src/lib/transport.js#L298) and [attaches it to errors](https://github.com/elastic/elasticsearch-js/blob/14.x/src/lib/errors.js#L23). Its useful, but sadly that `path` property means that graphql-js assumes that an elasticsearch error is a GraphQLError, and so the index path gets leaked instead of the useful graphql query path.
The fix is to be a little bit stricter.
There is probably a better fix to recognise a GraphQLError across contexts, but this will at least improve the situation. Plus, the added tests should make any better solution easier to test.

fix elasticsearch errors being mistaken for graphql errors

---

src/language/__tests__/visitor-test.js
src/utilities/TypeInfo.js

[Try it](http://graphql.org/swapi-graphql/?query=%7B%0A%20%20allFilms%20%7B%0A%20%20%20%20films%20%7B%0A%20%20%20%20%20%20...%20%7B%0A%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=null)
This issue caused because `TypeInfo` incorrectly handles inline fragments without type condition.
#1027 masked this issue by introducing [additional type check](https://github.com/graphql/graphql-js/pull/1027/files#diff-7fee6c60aa31bc90e45e7a2fd844026dR48) but underlying bug in `TypeInfo` still exists.

Fix how TypeInfo handles inline fragments without type

---

src/language/__tests__/parser-test.js
src/language/parser.js

To date, parsing queries with short-hand syntax returns different results from parsing regular queries.
`parse('query{a{b}}')` returns
```
...
name: undefined,
variableDefinitions: [],
...
```
However, `parse('{a{b}}')` returns
```
...
name: null,
variableDefinitions: null,
...
```
This shouldn't be the case. This PR made queries with short-hand syntax to be parsed as regular.
This inconsistency indirectly causes [this bug](https://github.com/graphql/graphiql/issues/234) to happen in GraphiQL. Despite that issue being closed, using GraphiQL without `express-graphql` still makes that bug to happen (with `null` value, actually, but this doesn't change much).
Closes #729.

Uniform parsing of queries with short-hand syntax with regular queries

---

src/language/__tests__/schema-kitchen-sink.graphql
src/language/__tests__/schema-parser-test.js
src/language/__tests__/schema-printer-test.js
src/language/ast.js
src/language/lexer.js
src/language/parser.js
src/language/printer.js
src/language/visitor.js
src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/__tests__/schemaPrinter-test.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js
src/utilities/schemaPrinter.js

**Breaking Change - those using comment descriptions will need to provide `{commentDescriptions: true}` to the relevant functions**
As discussed in https://github.com/facebook/graphql/pull/90
This proposes replacing leading comment blocks as descriptions in the schema definition language with leading strings.
While I think there is some reduced ergonomics of using a string literal instead of a comment to write descriptions (unless perhaps you are accustomed to Python or Clojure), there are some compelling advantages:
* Descriptions are first-class in the AST of the schema definition language.
* Comments can remain "ignored" characters.
* No ambiguity between commented out regions and descriptions.
Specific to this reference implementation, since this is a breaking change and comment …

RFC: Descriptions as strings.

---

src/execution/execute.js
src/type/definition.js

In this PR I corrected types for `path` and `parentType` fields of `GraphQLResolveInfo`.
Without this info, I forced to add additional checks to my resolvers:
```ts
if (info.parentType instanceof GraphQLObjectType) {
// ...
}
if (info.path) {
// ...
}
```
Both checks always true and this is obvious from  code of [buildResolveInfo](https://github.com/APIs-guru/graphql-js/blob/2d43dd65a1b784ac790e66d0cc64a4c7b0a5a901/src/execution/execute.js#L701-L702) function.
But I forced to add above checks in all my resolvers 😞 
@wincent This PR affects only typings and doesn't change any runtime behaviour. Can you please review it?

Correct types for 'path' & 'parentType' of GraphQLResolveInfo

---

src/utilities/schemaPrinter.js

`isDeprecated` is to determine deprecation instead of `deprecatedReason`.
currently `"isDeprecated"` is totally ignored, for example, if the input is like `{"isDeprecated": false, "deprecationReason": "-"}` it will be treated as deprecated, it is wrong.

Check isDeprecated instead of deprecationReason in printDeprecated

---

src/utilities/__tests__/buildClientSchema-test.js

The introspection schema says `__Type.interfaces` is nullable. This protects the function from throwing an exception when it is in fact `null`.

make buildObjectDef more robust

---

src/utilities/__tests__/findBreakingChanges-test.js
src/utilities/findBreakingChanges.js

T23304543
findBreakingChanges now includes checks for adding a nullable field to an existing input, and adding a nullable argument. These changes won't necessarily break a schema, but they can potentially cause issues. I also added unit tests for these new detections.

Detect added nullable input field or added nullable argument

---

src/utilities/buildASTSchema.js

Simplify code and more importantly unify some of the exceptions.

Simplify operationTypes validation

---

src/execution/execute.js
src/type/definition.js

This changes the check for null/undefined to a check for undefined to determine if scalar serialization was successful or not, allowing `null` to be returned from serialize() without indicating error.
This is potentially breaking for any existing custom scalar which returned `null` from `serialize()` to indicate failure. To account for this change, it should either throw an error or return `undefined`.
Fixes #1057
Closes #1066

(Potentially Breaking) Allow serializing scalars as null.

---

src/utilities/buildASTSchema.js
src/utilities/extendSchema.js

Duplicated code caused issues in the past, for example, #961.
Also, it makes PRs that I working right now significantly bigger.
I tried to leave code intact as much as possible to simplify review.

Remove duplicated code from buildASTSchema and extendSchema

---

src/error/GraphQLError.js
src/error/__tests__/GraphQLError-test.js
src/error/formatError.js
src/error/locatedError.js

Implementing suggestion from #912 
In some cases, it's required to provide additional details inside errors.
At the same time, we don't want to force users to override `formatError` method.
This PR adds `extensions` property to `GraphQLError` and extend error object in the response with fields from it.

Allow to extend GraphQL errors with additional properties

---

src/language/__tests__/lexer-test.js

While looking over https://github.com/graphql/graphql-js/pull/926, I noticed what I believe is a bad copy/paste in the block string lexer tests.
cc @leebyron

Fix typo in block string lexer tests

---

src/execution/__tests__/executor-test.js
src/execution/execute.js
src/index.js
src/language/__tests__/schema-kitchen-sink.graphql
src/language/__tests__/schema-parser-test.js
src/language/__tests__/schema-printer-test.js
src/language/ast.js
src/language/directiveLocation.js
src/language/index.js
src/language/kinds.js
src/language/parser.js
src/language/printer.js
src/language/visitor.js
src/type/definition.js
src/type/directives.js
src/type/index.js
src/type/introspection.js
src/utilities/__tests__/buildASTSchema-test.js
src/utilities/buildASTSchema.js
src/utilities/buildClientSchema.js
src/utilities/extendSchema.js
src/utilities/introspectionQuery.js
src/validation/__tests__/ExecutableDefinitions-test.js
src/validation/__tests__/KnownDirectives-test.js
src/validation/rules/ExecutableDefinitions.js
src/validation/rules/KnownDirectives.js
src/validation/specifiedRules.js

This changes the parsing grammar and validation rules to more correctly implement the current state of the GraphQL SDL proposal (https://github.com/facebook/graphql/pull/90)

Update to match SDL changes

---

src/index.js
src/type/builtins.js
src/type/directives.js
src/type/index.js
src/type/introspection.js
src/type/scalars.js
src/utilities/buildASTSchema.js
src/utilities/buildClientSchema.js
src/utilities/schemaPrinter.js

I find myself copy-pasting the same list of built-in scalar names in every new project we start.
In many cases, built-in types/directives should be handled differently so having such simple predicates save a lot of code lines.
Because of circular dependencies, I couldn't figure out file suitable for `builtInTypes` and `isBuiltInType`. That's why I created a new one: `src/type/builtins.js`.
Is it an appropriate filename or should I put somewhere else?

Add predicates to for built-in types.

---

src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js
src/validation/rules/OverlappingFieldsCanBeMerged.js

`OverlappingFieldsCanBeMerged` would infinite loop when passed something like
```graphql
fragment A on User {
name
...A
}
```
It's not `OverlappingFieldsCanBeMerged`'s responsibility to detect that validation error, but we still would ideally avoid infinite looping.
This detects that case, and pretends that the infinite spread wasn't there for the purposes of this validation step.
Also, by memoizing and checking for self-references this removes duplicate reports.
Closes #780

Fix infinite loop on invalid queries in OverlappingFields

---

src/index.js
src/type/__tests__/enumType-test.js
src/type/__tests__/introspection-test.js
src/utilities/__tests__/buildClientSchema-test.js
src/utilities/index.js
src/utilities/introspectionQuery.js

This adds a new function `getIntrospectionQuery()` which allows for some minor configuration over the resulting query text: to exclude descriptions if your use case does not require them.
It also updates the flow types to remove exact types for the kinds of `__Type` since they will have other fields that would be `null`.

Improve introspection types + new getIntrospectionQuery()

---

src/execution/__tests__/sync-test.js
src/execution/execute.js
src/graphql.js
src/index.js

**This is a breaking change. Existing uses of execute() outside of async functions which assume a promise response will need to wrap in Promise.resolve()**
This allows `execute()` to return synchronously if all fields it encounters have synchronous resolvers. Notable this is the case for client-side introspection, querying from a cache, and other useful cases.
Also introduces `graphqlSync()` as a top level function which asserts sync behavior and includes validation.
Note that the top level `graphql()` function remains a Promise to minimize the breaking change, and that `validate()` has always been synchronous.

RFC: Synchronous execution

---

src/error/GraphQLError.js
src/error/formatError.js
src/error/index.js
src/error/locatedError.js
src/execution/execute.js
src/type/definition.js
src/validation/rules/ScalarLeafs.js

This uses $ReadOnlyArray and `+` properties to ensure Errors are read-only, removing some use of `*`.

Flow: Readonly errors

---

src/error/formatError.js
src/error/locatedError.js
src/execution/execute.js
src/subscription/__tests__/subscribe-test.js
src/subscription/subscribe.js

Expanding on the tests to cover all forms of subscription resolver errors.

Subscriptions: report resolver errors during initialization

---

src/type/__tests__/introspection-test.js

Since being able to execute introspection queries synchronously was the primary motivation for #1115 I think it worth to test it 😃

Test that introspection results are always sync.

---

src/index.js

It's useful for building wrappers around `graphql` since you can reuse `GraphQLArgs` type. 
BTW, [ExecutionArgs](https://github.com/graphql/graphql-js/blob/master/src/index.js#L225) is also exported.

Export GraphQLArgs

---

src/subscription/__tests__/subscribe-test.js
src/subscription/subscribe.js

A remaining issue with subscriptions is attempting to subscribe to a missing field. The existing implementation creates an internal error which is an improper blame since there is no possibility to fix it internally - it is an issue with the query.
For consistency with the same scenario for query/mutation operations, this simply returns nothing. I interpret the equivalent of "undefined" for a subscribe operation as an empty iteration.
Note: this will require spec changes, however spec changes are necessary either way to resolve the ambiguity of this exact scenario.

Test: Missing subscription field should not be an "internal error"

---

src/execution/values.js
src/jsutils/find.js
src/jsutils/quotedOrList.js
src/jsutils/suggestionList.js
src/language/__tests__/parser-test.js
src/language/__tests__/schema-parser-test.js
src/language/ast.js
src/language/lexer.js
src/language/parser.js
src/utilities/buildASTSchema.js

**Potential breaking change: Where previously AST would produce `null`, it now produces `undefined`**
This tightens up the AST types to produce readonly covariant fields, $ReadOnlyArray in a couple places (not AST yet, perhaps in a future PR), and replaces `field?: ?Rule` with `field?: Rule` to exclude the possibility of `null` from `undefined` for optional rules, reducing complexity.

Read-only AST types

---

src/language/__tests__/schema-kitchen-sink.graphql
src/language/__tests__/schema-printer-test.js
src/language/ast.js
src/language/kinds.js
src/language/parser.js
src/language/printer.js
src/language/visitor.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js
src/validation/__tests__/KnownDirectives-test.js
src/validation/rules/KnownDirectives.js

This adds the recent changes to the SDL proposal.

SDL Spec changes

---

src/language/ast.js
src/type/directives.js
src/type/introspection.js
src/type/scalars.js
src/type/schema.js
src/utilities/concatAST.js
src/validation/rules/OverlappingFieldsCanBeMerged.js
src/validation/validate.js

This is the second step of #1121 to ensure AST are readonly, marking all arrays as $ReadOnlyArray.

Readonly AST: Use $ReadOnlyArray

---

src/execution/execute.js
src/type/schema.js
src/validation/validateSchema.js

First super rough draft to how #1080 could look. Please share feedback.
`assertIsValid()` is only called from one place for now, but would obviously be called form a bunch of places.

Prototype of validate step

---

src/error/GraphQLError.js
src/error/__tests__/GraphQLError-test.js

A common case is encountering an error which blames to a single AST node. Ensure the GraphQLError constructor can handle this case.

Allow constructing GraphQLError with single node.

---

src/execution/__tests__/variables-test.js
src/subscription/__tests__/subscribe-test.js
src/type/definition.js
src/utilities/isValidJSValue.js
src/utilities/isValidLiteralValue.js
src/utilities/valueFromAST.js
src/validation/__tests__/harness.js
src/validation/__tests__/validation-test.js

Fixes #910
This factors out the enum value validation from scalar value validation and ensures the same try/catch is used in isValidLiteralValue as isValidJSValue and protecting from errors in valueFromAST.

Fix unhandled error when parsing custom scalar literals.

---

src/type/definition.js

Mirrors the structure of OutputType flow type, reduces the use of `*`.

Improve aggreate NullableType and InputType flow types

---

src/error/GraphQLError.js
src/error/formatError.js
src/error/index.js
src/error/printError.js
src/error/syntaxError.js
src/execution/__tests__/sync-test.js
src/index.js
src/language/__tests__/lexer-test.js
src/language/__tests__/parser-test.js
src/language/__tests__/schema-parser-test.js
src/language/index.js
src/language/location.js

Lifted from / inspired by a similar change in #722, this creates a new function `printError()` (and uses it as the implementation for `GraphQLError#toString()`) which prints location information in the context of an error.
This is moved from the syntax error where it used to be hard-coded, so it may now be used to format validation errors, value coercion errors, or any other error which may be associated with a location.

New: printError()

---

src/execution/execute.js
src/type/__tests__/validation-test.js
src/type/definition.js
src/type/schema.js
src/type/validate.js
src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/buildASTSchema.js
src/utilities/buildClientSchema.js
src/utilities/extendSchema.js

This moves validation out of GraphQLSchema's constructor (but not yet from other type constructors), which is responsible for root type validation and interface implementation checking.
Reduces time to construct GraphQLSchema significantly, shifting the time to validation.
This also allows for much looser rules within the schema builders, which implicitly validate while trying to adhere to flow types. Instead we use any casts to loosen the rules to defer that to validation where errors can be richer.
This also loosens the rule that a schema can only be constructed if it has a query type, moving that to validation as well. That makes flow typing slightly less nice, but allows for incremental schema building which is valuable
Improves #1079 
Partial #1080 
Closes #722

Validate schema root types and directives

---

src/error/GraphQLError.js
src/error/__tests__/printError-test.js
src/error/printError.js

If a GraphQLError represents multiple nodes across files (could happen for validation across multiple parsed files) then the reported locations and printError output can be incorrect for the second node. This ensures locations are derived from nodes whenever possible to get correct location and amends comment documentation.

Fix printError/locations for multiple nodes.

---

src/language/ast.js
src/language/parser.js

This should be the last set of spec changes for a standardized SDL

Address recent SDL spec changes

---

src/type/__tests__/definition-test.js
src/type/__tests__/validation-test.js
src/type/definition.js
src/type/directives.js
src/type/validate.js
src/utilities/__tests__/assertValidName-test.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/assertValidName.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js

This is the second step of moving work from type constructors to the schema validation function.
Currently the implementation should be nearly complete, however there are a lot of tests to migration from expecting throwing exceptions to instead creating validation errors.
Closes #546 
Closes #1080 
Improves #1079 
Improves #719

Move schema validation into separate step (type constructors)

---

src/language/__tests__/parser-test.js
src/language/__tests__/printer-test.js
src/language/__tests__/visitor-test.js
src/language/ast.js
src/language/parser.js
src/language/printer.js
src/language/visitor.js

This PR adds experimental support for parsing variable definitions within a fragment declaration. If the `fragmentVariablesExperimental` flag is passed into the options for `parse` then the parser will accept `VariableDefinitions` placed after the `TypeCondition` and before any `Directives`. The syntax is identical to the usual query-defined variable definitions, and the parser will parse these into the optional `variableDefinitions` field on `FragmentDefinitionNode`.
Context:
There's been ongoing discussion on exploring this concept: https://github.com/facebook/graphql/issues/204. Note that this PR only supports parsing fragment variable definitions into the AST. It does not allow for passing variable values into a fragment spread. It at least gets a foot in the door for starting to …

Add experimental support for parsing variable definitions in fragments

---

src/validation/__tests__/KnownArgumentNames-test.js
src/validation/rules/KnownArgumentNames.js

TypeInfo has a utility this should be using.

Simplify Unknown Args Validation

---

resources/watch.js

Without this update, using `npm run watch` always gives this error:
```
execution/execute.js ...
/home/osboxes/graphql-js/src/execution/execute.js
1:1  error  Definition for rule 'no-async' was not found  no-async
✖ 1 problem (1 error, 0 warnings)
✘ execution/execute.js
```

Make `npm run watch` linting work right

---

src/language/__tests__/visitor-test.js
src/language/visitor.js

As discussed in #1145 I started to work on tests for `visit` function.

Fix 'path' argument. Add more visitor tests

---

src/execution/__tests__/variables-test.js
src/jsutils/suggestionList.js
src/type/__tests__/enumType-test.js
src/utilities/__tests__/coerceValue-test.js
src/utilities/coerceValue.js
src/validation/__tests__/ValuesOfCorrectType-test.js
src/validation/rules/ValuesOfCorrectType.js

For misspelled enums or field names, these suggestions can be helpful.
This also changes the suggestions algorithm to better detect case-sensitivity mistakes, which are common

Add suggestions for invalid values

---

src/language/visitor.js

Changing this from the (untyped) any to mixed is too severe a breaking change. Changing back to any ensures the visitor functions themselves remain checked but does not cause downstream usage to fail.

visit return any instead of mixed.

---

.flowconfig
src/error/GraphQLError.js
src/type/introspection.js
src/type/scalars.js

Merges and closes #1157
Codebases which don't enable this experiment show flow errors, so removing it from the project to avoid regression

Remove flow option experimental.const_params

---

src/utilities/__tests__/assertValidName-test.js
src/utilities/assertValidName.js

Much older versions of GraphQL use `__configs__` as part of a pseudo-introspection meta programming layer. While this is technically against the spec, this adds temporary support.

Add special case for legacy servers.

---

src/execution/execute.js
src/graphql.js
src/jsutils/MaybePromise.js
src/subscription/mapAsyncIterator.js
src/type/definition.js

`MaybePromise<T>` type, to avoid constantly declaring `Promise<some stuff> | some stuff`. Most visible in `execute.js` but also in a few other places.

DRY with MaybePromise

---

src/index.js
src/utilities/buildASTSchema.js
src/utilities/index.js

We were using this in graphql-tools with graphql@0.11, would be nice to get it exported again!

Bring back `getDescription` export

---

package.json
yarn.lock

See: https://github.com/babel/babel/commit/0230dc50670771416406f9375eb57bf5adad17cc

Update "babel-cli" package to enable '--inspect-brk' option

---

src/language/__tests__/schema-parser-test.js
src/language/parser.js

This offers a slightly smoother adoption path for existing code that uses the legacy empty field sets.

Parse option: allowLegacySDLEmptyFields

---

src/language/__tests__/schema-parser-test.js

Extend without fields followed by extend makes second extend to be parsed as types to implement. Note that locations are faulty in test (cause it's hard to deduce them).

Add test case for failing parsing

---

src/jsutils/instanceOf.js

This ensures the additional checking for multiple graphql instances only occurs in non-production builds. Not only does this improve the performance for production builds, it also solves a spurious error case for minified builds:
Since this additional check compares the `.name` of the constructors as a proxy for determining if two classes are representationally equal, minified builds may result in spurious false-positives if class names are minified to single-character names and those characters are likely to conflict.
This doesn't require `process` to exist (defaulting to the non-production mode), but bundlers like Webpack should consider using a stripping transform (see: https://webpack.js.org/guides/production/#specify-the-environment) in production builds if they also use a minifier.

Only trigger "one instance of graphql" error in DEV environments.

---

src/execution/__tests__/nonnull-test.js

Similar to #1178 - zaps all the repeated code and data, rendering it more comprehensible (at least to me).

DRY with NonNull of Object tests

---

src/type/__tests__/introspection-test.js
src/utilities/__tests__/astFromValue-test.js
src/utilities/__tests__/schemaPrinter-test.js
src/utilities/astFromValue.js

Currently `astFromValue` converts `-1` to float, `0000` to integer and also escapes strings when it shouldn't.

Fix 'astFromValue' to correctly handle integers and strings

---

src/utilities/__tests__/extendSchema-test.js
src/utilities/__tests__/schemaPrinter-test.js
src/utilities/schemaPrinter.js

Added test to prevent future regressions. Updated existing also.

Update printSchema for recent SDL change to `implements`.

---

src/index.js
src/utilities/__tests__/introspectionFromSchema-test.js
src/utilities/index.js
src/utilities/introspectionFromSchema.js

Based on #1114 by @mjmahone
>>(await graphql(schema, introspectionQuery)).data is a pretty strange API that doesn't, IMO, match.
> That is the specified definition of introspection. If we'd like a nominally easier to understand API, we can certainly add that, but it should be a one-liner implemented using exactly that line of code. I think #1115 could help make that easier by guaranteeing a sync result and at least avoiding async when it's not necessary
I think it's better to use `execute` instead of `graphql` since you are not spending time validation introspection query. But `execute` required parsed query so it's not an one-liner anymore.
Checking for `errors` is also a good practice even those introspection query should produce them.
And finally, you should manually cast the result to …

Add 'introspectionFromSchema' utility function

---

src/type/__tests__/schema-test.js
src/type/schema.js

The result of `getTypeMap()` recursively includes all types referenced by root types, so I would expect it to include types referenced by directives, too.
If this is not intended, I think a test asserting the opposite would be a good idea.

getTypeMap() does not include input types used in directives

---

src/index.js
src/type/directives.js
src/type/index.js
src/type/schema.js

I need them to do schema transformations.
All other `*Config` types already exported.

Export 'GraphQLSchemaConfig' & 'GraphQLDirectiveConfig' types

---

src/type/__tests__/validation-test.js
src/type/schema.js
src/type/validate.js

This offers an escape hatch for schema that are defined with legacy field names that were valid in older versions of the spec and no longer are via an explicit white-list.
Fixes #1184

Allow use of legacy names for schema validation

---

src/language/__tests__/printer-test.js
src/language/__tests__/schema-printer-test.js
src/language/printer.js

When I looked at #1188 I noticed that current implementation doesn't handle strings like that:
```
"""    space-led value "quoted string"
"""
```
Currently it's printed as:
```
"""    space-led value "quoted string""""
^ breaks parser
```

Fix print of block string with leading space and quotation

---

src/type/definition.js

Helpful for better type coverage when using tools like [apollo-codegen](https://github.com/apollographql/apollo-codegen) or [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator) to create field level input argument type definitions.

Allow optionally specifying Args on GraphQLFieldResolver

---

src/execution/execute.js
src/jsutils/memoize3.js

Collecting subfields occurs after resolving a field's value and before resolving subfield values. This step collects fragment spreads and checks inline fragment conditions. When fetching a list of things, this step is computed with the same inputs and expecting the same outputs for each item in the list. Memoizing ensures the work is done at most once per type returned from a list.
I tested this against the introspection query (which is both synchronous and complex) against a large schema and saw a ~15%-25% reduction in runtime. In practice I don't expect most queries to see this level of speedup as most queries are limited by backend communication and not execution overhead.

Perf: memoize collectSubfields

---

src/execution/__tests__/sync-test.js
src/execution/execute.js
src/jsutils/getPromise.js
src/jsutils/promiseForObject.js
src/jsutils/promiseReduce.js

Refactors executeFieldsSerially to return MaybePromise
Fixes #1195

Execute serially supporting sync execution.

---

src/jsutils/__tests__/dedent-test.js
src/jsutils/dedent.js
src/language/__tests__/printer-test.js
src/utilities/__tests__/schemaPrinter-test.js

As discussed in #1202, this changes the behavior of the dedent function that is used in unit tests to not return raw strings any more. Also added tests for the function itself.

Improve dedent (fixes #1202)

---

src/execution/execute.js
src/execution/values.js
src/index.js
src/language/__tests__/parser-test.js
src/language/__tests__/visitor-test.js
src/language/ast.js
src/language/directiveLocation.js
src/language/index.js
src/language/kinds.js
src/language/lexer.js
src/language/parser.js
src/type/definition.js
src/type/scalars.js
src/utilities/TypeInfo.js
src/utilities/astFromValue.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js
src/utilities/getOperationAST.js
src/utilities/isValidLiteralValue.js
src/utilities/typeFromAST.js
src/utilities/valueFromAST.js
src/utilities/valueFromASTUntyped.js
src/validation/rules/ExecutableDefinitions.js
src/validation/rules/KnownArgumentNames.js
src/validation/rules/KnownDirectives.js
src/validation/rules/LoneAnonymousOperation.js
src/validation/rules/OverlappingFieldsCanBeMerged.js
src/validation/validate.js

I converted `Kind` into an object and created `KindEnum` and `TokenKindEnum` types.
To do this I wrapped enums into `Object.freeze` as [required by Flow](https://github.com/facebook/flow/blame/master/Changelog.md#L107-L116).
It's safe to use `Object.freeze` since it supported by [all browsers](https://github.com/graphql/graphql-js/blob/master/.babelrc#L6-L12) supported by this lib:
If for some reason `Object.freeze` can't be used in this lib I can wrap it into code comment as suggested here: https://github.com/facebook/flow/issues/5465#issuecomment-350422478

Cleanup Enums

---

src/jsutils/memoize3.js

`WeakMap.get` returns `undefined` on cache miss. Checking for false instead of `undefined` could give a false cache-miss and recalculate when a false value is returned by the memoised function with those params.

More accurate check for cache-hit in memoize3

---

src/jsutils/objectValues.js
src/type/introspection.js
src/type/schema.js
src/type/validate.js
src/utilities/astFromValue.js
src/utilities/schemaPrinter.js
src/utilities/valueFromAST.js

Following pattern are frequently used in this lib: 
``` js
const objMap = ...
Object.keys(objMap).map(name => {
const item = objMap[name];
// ...
})
```
It can be greatly simplify with `Object.values` however [Flow can't hadle it well](https://github.com/facebook/flow/issues/2221) and IE doesn't implement it.
This PR adds `objectValues` substitution to use until we could switch to `Object.values`.
Plus it should give small performance boost from using native `Object.values` when possible.

Add 'objectValues' JS util function

---

src/index.js
src/utilities/__tests__/lexographicSortSchema-test.js
src/utilities/index.js
src/utilities/lexographicSortSchema.js

@leebyron Following your suggestion in #1199 I reimplemented `lexographicSortSchema` without changing any existing functionality or adding new API.
Can you please review it?

Add 'lexographicSortSchema'

---

package.json
resources/gitpublish.sh

This consolidates copying of flat files into the build step.
This also removes "contributors" from the package since that's super outdated and no longer relevant.

Simplify build steps

---

src/index.js
src/utilities/__tests__/lexicographicSortSchema-test.js
src/utilities/index.js
src/utilities/lexicographicSortSchema.js

Reported by @marktani in #1208

Fix spelling, "lexographicSortSchema" => "lexicographicSortSchema"

---

src/__tests__/starWarsIntrospection-test.js

Switch introspection tests to graphqlSync

---

src/utilities/__tests__/extendSchema-test.js
src/utilities/extendSchema.js

v0.13.0-rc.1 adds the `allowedLegacyNames` option from #1194. Unfortunately, while trying to make a PR for [Relay](https://github.com/facebook/relay) that adds support for this, it turns out that Relay internally uses `extendSchema` from `graphql-js` but that function does not maintain this option and thus the new schema still complains.
This PR addresses that, it would be nice if this could go into a v0.13.0-rc.2 release.

Maintain allowed legacy names when extending a schema.

---

src/utilities/__tests__/buildASTSchema-test.js

Tested that 'buildASTSchema' can build invalid schema suggested here:
https://github.com/graphql/graphql-js/pull/1222/files#r166484638

Add more 'buildASTSchema' tests + cleanup

---

src/utilities/__tests__/assertValidName-test.js
src/utilities/assertValidName.js

This `__configs__` special case for assertValidName is no longer necessary now that we have the allowedLegacyNames mechanism.

Remove special case in assertValidName

---

src/utilities/astFromValue.js
src/utilities/typeComparators.js

Now that we're `@flow strict` we can remove some unnatural patterns for telling flow that we expect function args to be const.

Strict const args

---

src/index.js
src/utilities/index.js

PR mentioned in https://github.com/graphql/graphql-js/pull/1234#issuecomment-364283068

export isValidNameError

---

src/index.js
src/language/index.js

Makes it easier to use standard fragment/operation definitions without pulling in schema definitions.

Export ExecutableDefinitionNode

---

.github/ISSUE_TEMPLATE.md

Currently, GFM renders this link as:
`https://github.com/graphql/graphql-js/blob/master/.github/github.com/facebook/graphql`

ISSUE_TEMPLATE: Fix 'facebook/graphql' link

---

src/type/__tests__/schema-test.js
src/type/schema.js
src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/buildClientSchema-test.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/buildASTSchema.js
src/utilities/buildClientSchema.js
src/utilities/extendSchema.js

Since yesterday I went back and did some more code reviewing and realised there’s another few situations where the allowed legacy names configuration isn’t being passed on, apologies for not catching that yesterday.

More allowed legacy names

---

src/utilities/buildASTSchema.js
src/utilities/extendSchema.js

It's part of #1199 
Its primary purpose is to make  'ASTDefinitionBuilder' responsible only for build types from AST.
It's not only made possible to extract `transformSchema` into the separate function but also make the code more modular and simple.

Make 'ASTDefinitionBuilder' responsible only for build types from AST

---

src/index.js
src/utilities/buildASTSchema.js
src/utilities/index.js

buildSchema() is essentially just short hand for buildASTSchema(parse()), however since both of these composed functions accept options, it's nice to allow buildSchema() to accept options as well - it accepts the combined set of options which it passes to both functions.
This also names and exports the options for buildASTSchema() such that they can be used in the same way by third party code.

Allow buildSchema() to take options.

---

src/utilities/__tests__/extendSchema-test.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js

It's a preparation for the #1095

Unify extending of type system

---

resources/mocha-bootload.js
src/execution/__tests__/abstract-promise-test.js
src/execution/__tests__/abstract-test.js
src/execution/__tests__/directives-test.js
src/execution/__tests__/executor-test.js
src/execution/__tests__/schema-test.js
src/execution/__tests__/union-interface-test.js
src/type/__tests__/enumType-test.js
src/utilities/__tests__/buildClientSchema-test.js
yarn.lock

After seeing async/await on sync test I had an OCD episode 😄
I think I removed ~70% of excessive async/await keywords.

Tests: Remove excessive dependencies and async/await

---

src/type/__tests__/validation-test.js
src/type/schema.js
src/type/validate.js

Throws descriptive error when non-type used instead of interface

---

src/execution/values.js
src/type/__tests__/definition-test.js
src/type/schema.js
src/utilities/valueFromAST.js

Not sure I catch all places since I used RegExp:
```sh
grep ' (.*: [A-Za-z0-9]*)[^ ]' -R src/ | grep -v any
```
Would be great if flow itself will produce errors/warnings on redundant casts.

Remove redundant Flow type casts

---

src/type/__tests__/definition-test.js
src/type/definition.js

During profiling of #1286 I notice that `completeValue` is deoptimize (optimised again after some more calls) by V8 on first `serialize` call of an enum. See log:
```
[deoptimizing (DEOPT eager): begin  <JSFunction completeValue (sfi = )> (opt #21) @85, FP to SP delta: 64, caller sp: ]
;;; deoptimize at </Users/ivang/dev/graphql-js/perf_test/baseDist/type/definition.js:726:26> inlined at </Users/ivang/dev/graphql-js/perf_test/baseDist/execution/execute.js:1:1>, wrong map
[deoptimizing (eager): end  <JSFunction completeValue (sfi = )> @85 => node=38, pc=, caller sp=, state=TOS_REGISTER, took 2.873 ms]
[deoptimizer unlinked: completeValue / 30d1490930a9]
[deoptimizing (DEOPT lazy): begin  <JSFunction completeValue (sfi = )> (opt #21) @94, FP to SP delta: 64, caller sp: ]
[deoptimizing …
```

Fix `execute` deoptimisation caused by GraphQLEnumType

---

src/language/__tests__/schema-kitchen-sink.graphql
src/language/__tests__/schema-printer-test.js
src/language/printer.js

Descriptions were not separated on their own lines, which made for technically parseable but hard to read output.
Fixes #1285

Fix printing of ASTs of argument definitions with descriptions.

---

src/execution/execute.js

Using benchmark, I didn't measure any performance difference.

Execute: Remove excessive arguments

---

src/type/__tests__/schema-test.js
src/type/__tests__/validation-test.js
src/type/schema.js
src/type/validate.js

fix #1277 ensure interface has at least 1 concrete type

---

src/error/locatedError.js

Not sure how to fix other `$FlowFixMe` introduced in #1291 but this was a low hanging fruit.

locatedError: correct definition to pass Flow 0.68 check

---

src/error/GraphQLError.js
src/error/__tests__/GraphQLError-test.js
src/error/formatError.js
src/execution/__tests__/executor-test.js

Mirrors https://github.com/facebook/graphql/pull/407
This is breaking change, however, `extensions` is the relatively new feature that was added in `0.12.0`. 
Also, it could be easily workaround by providing `formatError` property to a server:
https://github.com/graphql/express-graphql#options
https://github.com/apollographql/apollo-server#options
Unintended changes: I didn't want to add `extensions: undefined` to every error inside tests so I refactored them.

 formatError: put all extensions inside 'extensions' property

---

src/type/__tests__/validation-test.js

> Ideally these should detect the exact set of schema validation errors and we should write the test so that each test introduces only the validation error it expects to catch
@leebyron Done

Match exact set of errors in schema validation tests

---

package.json

Context: I'm [experimenting](https://twitter.com/motiz88/status/985573076854288390) with ways to make `graphql-js`'s footprint smaller for the use case of executing requests directly on the client.
While I haven't audited all the code in this package (perhaps the big caveat of this PR), from what I've seen I feel safe concluding it's all written in a side-effect-free style, where all modules simply export sets of values ( / functions) which are fundamentally safe to cherry-pick.
On that assumption, this PR communicates this as a guarantee to bundlers via the `sideEffects` flag in `package.json` (introduced by Webpack 4). This enables further tree-shaking optimisations than Webpack is able to perform otherwise, particularly on re-exports, which `graphql-js` uses quite heavily. Anecdotally, …

Mark all modules as having no side effects for bundling

---

src/execution/execute.js

For a feature, I'm working on I needed to understand how `execute` is working so I read through its implementation. I notice that `completeValueWithLocatedError` is called only from `completeValueCatchingError` and would be simpler to just merge them together.
So main reason of this PR is to remove one layout of try/catch & isPromise/then and make error handling more obvious.
To check that I didn't introduce any performance regressions I profiled modified version of [introspectionFromSchema-benchmark.js](https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/introspectionFromSchema-benchmark.js)
During this profiling I discovered that hottest function is a fat arrow callback inside `executeFields` function:
```
Statistical profiling result from base3-v8.log, (9005 …
```

Execute: simplify + speedup

---

src/execution/__tests__/nonnull-test.js

It was really hard to read those tests.
Moreover, explicit version is shorter and this PR increase line count only because I added `path` to every error.

Make "nonnull-test.js" more explicit

---

src/error/__tests__/printError-test.js
src/error/printError.js
src/language/__tests__/lexer-test.js

I noticed that if an error happens on the last line 9 lines string all line numbers are padded with extra space.
It's happening because the padding is calculated based on the size of next line number without checking if this line exists.

printError: fix padding of line numbers

---

src/type/__tests__/validation-test.js
src/type/validate.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/extendSchema.js

I was rebasing WIP PR for 'toConfig' feature and spotted couple problems with #1314.

Fix extend schema from #1314

---

src/type/__tests__/introspection-test.js
src/type/introspection.js

Fixes #1015 
I also measured performance and the new version is ~~7% faster~~ in this test:
Update: I corrected my measurements and it became only 2.5% faster
```js
const {
GraphQLObjectType,
GraphQLSchema,
GraphQLString,
getIntrospectionQuery,
execute,
parse,
} = require('../dist');
const QueryRoot = new GraphQLObjectType({
name: 'QueryRoot',
fields: {
onlyField: { type: GraphQLString },
},
});
const schema = new GraphQLSchema({ query: QueryRoot });
const document = parse(getIntrospectionQuery());
for (let i = 0; i < 10000; ++i) {
execute({ schema, document });
}
```
Probably because `obj => obj.property` is faster than:
https://github.com/graphql/graphql-js/blob/ae5b163d2e6c124107fa0971f6d838c8a7d29f51/src/execution/execute.js#L1264

Don't call global fieldResolver on introspection fields

---

src/execution/execute.js
src/index.js
src/subscription/subscribe.js
src/type/schema.js
src/utilities/__tests__/getOperationRootType-test.js
src/utilities/getOperationRootType.js
src/utilities/index.js

We're finding we frequently do switch statements on an OperationDefinition's operation to pull the right type out of the schema. This hardens that approach: if for some reason we added a new operation kind, you could just update this function, rather than all the callsites that match on the operation type.

Expose getOperationRootType(schema, operationNode)

---

package.json
resources/prepublish.sh

NPM 6 produces this warning:
```js
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```
Yarn/NPM support new `prepublishOnly` property:
> As of npm@4.0.0, a new event has been introduced, prepare, that preserves this existing behavior. A new event, prepublishOnly has been added as a transitional strategy to allow users to avoid the confusing behavior of existing npm versions and only run on npm publish (for instance, running the tests one last time to ensure they're in good shape).
Currently NPM deploy done using: …

Fix npm@6 warnings about deprecated "prepublish"

---

.npmignore
.nycrc
package.json
resources/copy-package-json.js
yarn.lock

Isparta produces incorrect coverage reports:
Moreover there is zero chance it will be fixed since `isparta` is [officially unmantained](https://github.com/douglasduteil/isparta/commit/7e89d4e467f54558396533462122e73ea4e9dc31).
So I switched `isparta` to [nyc]() which is official CLI for istanbul and also replaced `babel-node` workaround with [offically recomended](https://babeljs.io/docs/setup/) `babel-registry`/`babel-polyfill`.

Coverage: Switch isparta to nyc

---

src/language/__tests__/visitor-test.js
src/language/visitor.js

This description is incorrect:
https://github.com/graphql/graphql-js/blob/86d33b49a92eda05ee9ca7b3a6fe3a449a21de4c/src/language/visitor.js#L43-L46
Since `ancestors` never includes parent, and it's already tested here:
https://github.com/graphql/graphql-js/blob/86d33b49a92eda05ee9ca7b3a6fe3a449a21de4c/src/language/__tests__/visitor-test.js#L54
But I added a separate test to make it more obvious.

Visitor: fix description of "ancestors" arg + test

---

package.json

This PR fixes issue introduced in #1342
It results in one node version always being green even if others will fail:
https://travis-ci.org/graphql/graphql-js/builds/379852096?utm_source=github_status&utm_medium=notification
Fix is based on this comment: https://github.com/istanbuljs/nyc/issues/433#issuecomment-260173503

CI: fix nyc doesn't proxy error status from mocha

---

.babelrc
.travis.yml
package.json

Based on the discussion in #1005 next release should be `14.0.0`.
I think it's important to drop node 4.0 before this release.

Run tests on node 10. Drop support for node 4.0

---

src/execution/__tests__/abstract-test.js
src/execution/execute.js
src/execution/values.js
src/jsutils/inspect.js
src/language/parser.js
src/subscription/subscribe.js
src/type/definition.js
src/type/scalars.js
src/type/schema.js
src/type/validate.js
src/utilities/astFromValue.js
src/utilities/coerceValue.js
src/validation/rules/FragmentsOnCompositeTypes.js
src/validation/rules/OverlappingFieldsCanBeMerged.js
src/validation/rules/PossibleFragmentSpreads.js
src/validation/rules/ProvidedRequiredArguments.js
src/validation/rules/ScalarLeafs.js
src/validation/rules/ValuesOfCorrectType.js
src/validation/rules/VariablesInAllowedPosition.js

I noticed this bug when I worked on #1332 I accidentally returned an array of types from typeResolver function and got this error:
```
Abstract type FooInterface must resolve to an Object type at runtime for field
Query.foo with value \"[object Object]\", received \"FooObject\". Either the 
FooInterface type should provide a \"resolveType\" function or each possible types 
should provide an \"isTypeOf\" function.
```
The relevant part here is:
```
must resolve to an Object type at runtime ..., received \"FooObject\".
```
It required me some time in the debugger to figure out that I wrapped GraphQLObjectType into an array. But it's impossible to figure out this from error message itself:
https://github.com/graphql/graphql-js/blob/2eccaadfa95f3e50f5d0d1aba42c419a70c61fc5/src/execution/execut …

Errors: fix how error messages represent arrays

---

src/execution/__tests__/variables-test.js
src/type/__tests__/serialization-test.js
src/type/scalars.js
src/utilities/__tests__/coerceValue-test.js

Working on #1333 I noticed that you can pass arrays as scalars in a query variable, e.g. [SWAPI example](http://graphql.org/swapi-graphql/?query=query%20(%24id%3A%20ID)%20%7B%0A%20%20person(personID%3A%20%24id)%20%7B%0A%20%20%20%20name%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22id%22%3A%20%5B1%5D%0A%7D)
This PR is based on #925 but fixing same issue for types other than `String` e.g.
```js
Number([1]) // 1
```

Scalars: reject array serialization/coercion

---

src/jsutils/applyToStringTag.js
src/language/source.js
src/type/__tests__/toStringTag-test.js
src/type/definition.js
src/type/directives.js
src/type/schema.js

**Changes**
* Add static and instance property getters for Symbol.toStringTag for
each exported class.
**Purpose**
Being able to compare class and class instances via internal class type
as per the definition and usage of Symbol.toStringTag allows other
libraries to validate types during runtime in this manner. It also
prevents them from having to patch the live values in their own
codebases.
**Contrived Example**
With no modules and vanilla JavaScript we should be able to do something
like the following.
```javascript
let type = new GraphQLObjectType({name: 'Sample'});
if (({}).toString.call(type) === '[object GraphQLObjectType]') {
// we have the right type of class
}
```
However, with libraries such as `type-detect` or `ne-types` the code can
look far cleaner.
```javascript
// …
```

Add support for Symbol.toStringTag

---

src/type/schema.js
src/type/validate.js
src/utilities/extendSchema.js

This PR makes `extensionASTNodes` and `__allowedLegacyNames` fields to always be arrays similar to other places in this lib:
https://github.com/graphql/graphql-js/blob/499a75939f70c4863d44149371d6a99d57ff7c35/src/type/definition.js#L619
https://github.com/graphql/graphql-js/blob/499a75939f70c4863d44149371d6a99d57ff7c35/src/type/definition.js#L947

Use empty arrays instead of undefined properties

---

src/jsutils/isInteger.js
src/subscription/__tests__/subscribe-test.js
src/type/__tests__/serialization-test.js
src/type/scalars.js
src/utilities/__tests__/coerceValue-test.js

Reject Infinity supplied as Int or Float value

---

src/execution/__tests__/variables-test.js
src/utilities/__tests__/valueFromAST-test.js

I clean up some existing tests but the main purpose of this PR is to report problem with enum values(test case added in 9452661).
From #836 it looks like both `undefined` and `NaN` could be used as an enum values:
```js
const TestEnum = new GraphQLEnumType({
name: 'TestEnum',
values: {
UNDEFINED: { value: undefined },
NAN: { value: NaN },
},
});
```
And run this query:
```graphql
{
undefined: fieldWithEnumInput(input: UNDEFINED)
NaN: fieldWithEnumInput(input: NAN)
}
```
It will result in:
```json
{
"data": {
"undefined": null,
"NaN": null
},
"errors": [
{
"message": "Argument \"input\" has invalid value UNDEFINED.",
"path": [ "undefined" ]
}
{
"message": "Argument \"input\" has invalid value NAN.",
"path": [ "NaN" ]
}
]
}
```
Because of this check: …

[Bug Reproduce] Can't use undefined and NaN as enum values

---

src/type/definition.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js

Taking the code from #1322 and pulling it to current master to fix merge conflicts. Additionally, did some minor naming changes.
@mgrenier is primarily responsible for this, I'm just pushing it along for the 14.0.0 release.

Merge extendType functionality changes from #1322

---

src/type/__tests__/validation-test.js
src/type/validate.js

Reverts #1277, and implements spec removal from https://github.com/facebook/graphql/pull/459 (which reverts spec change https://github.com/facebook/graphql/pull/424). While it's an open question whether this validation is good, we need to provide an upgrade path for schemas that currently do not satisfy this validation rule.

Allow interfaces to have no implementors

---

src/execution/__tests__/executor-test.js
src/execution/__tests__/variables-test.js
src/execution/execute.js
src/execution/values.js
src/jsutils/inspect.js
src/language/__tests__/parser-test.js
src/subscription/__tests__/subscribe-test.js
src/type/__tests__/definition-test.js
src/type/__tests__/enumType-test.js
src/type/__tests__/serialization-test.js
src/type/__tests__/validation-test.js
src/utilities/__tests__/coerceValue-test.js
src/validation/rules/FragmentsOnCompositeTypes.js
src/validation/rules/PossibleFragmentSpreads.js
src/validation/rules/ProvidedRequiredArguments.js
src/validation/rules/ScalarLeafs.js
src/validation/rules/VariablesInAllowedPosition.js

As well as use it in more places, replace use of JSON.stringify, and ensure validation rule message formatters expect strings instead of types.

Improve the inspect() function.

---

src/validation/rules/NoFragmentCycles.js

Refactor NoFragmentCycles rule

---

src/index.js
src/language/parser.js
src/utilities/index.js
src/utilities/introspectionQuery.js
src/utilities/isValidJSValue.js
src/utilities/isValidLiteralValue.js

Some methods have been marked as deprecated for a while - add explicit versions for each.
As recommended in #1383, this marks long deprecated methods as to be removed in v15, and newly deprecated options (legacy sdl) to be removed in v16

Add deprecation notices with explicit removal versions

---

src/type/__tests__/introspection-test.js
src/type/introspection.js
src/utilities/__tests__/schemaPrinter-test.js

These fields are holdovers from the first version of the spec, before directives had more control over their exact location and could be located in more places.
This is potentially breaking to any clients which relied on these fields, which will need to migrate to use the spec-compliant `locations` field before upgrading to a version including this patch
As described in #1383

BREAKING: Remove deprecated introspection fields

---

src/execution/__tests__/executor-test.js
src/execution/__tests__/variables-test.js
src/jsutils/isFinite.js
src/type/__tests__/serialization-test.js
src/type/scalars.js
src/utilities/__tests__/astFromValue-test.js
src/utilities/__tests__/coerceValue-test.js

This no longer accepts incoming variable values in a potentially lossy way, mirroring the existing behavior for literals. This fixes an issue with GraphQL.js being not spec compliant.
This is breaking since servers which used to accept incorrect variable values will now return errors to clients.
Serialization of values is not affected in the same way, since this is not a client-visible behavior.
As a bonus, this adds unique serialization and coercion functions for the ID type, allowing to be more restrictive on numeric types and un-stringable object types, while directly supporting valueOf() methods (ala MongoDB). The changes to how the ID type serializes and coerces data could be potentially breaking.
Fixes #1324

BREAKING/BUGFIX Strict coercion of scalar types

---

src/type/definition.js
src/utilities/__tests__/extendSchema-test.js

Cleanup tests in preparation to #1388 and also found a bug with `extensionASTNodes`

Fix `extensionASTNodes` assigment

---

src/type/definition.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/extendSchema.js

Fixes #1388 
Also contains #1390 and should be merged after it.

Extend scalar

---

src/type/definition.js
src/type/introspection.js
src/utilities/buildClientSchema.js

I was wondering why #1390 happened and I think we need to make config types exact.
This PR dependence on #1390 and should be merged after it.

Convert 'GraphQL*Config' to exact types

---

src/index.js
src/type/schema.js
src/utilities/buildASTSchema.js
src/utilities/index.js

Mark more stuff as deprecated

---

src/utilities/__tests__/introspectionFromSchema-test.js
src/utilities/introspectionFromSchema.js

Allows to just write 
`introspectionFromSchema(schema)`
instead of 
`introspectionFromSchema(schema, {descriptions: true})`.

Make introspectionFromSchema options argument optional

---

src/utilities/__tests__/extendSchema-test.js

Add missing extend scalar tests

---

src/error/printError.js
src/execution/values.js
src/language/__tests__/parser-test.js
src/subscription/__tests__/eventEmitterAsyncIterator.js
src/type/__tests__/definition-test.js
src/type/__tests__/validation-test.js
src/type/definition.js
src/type/schema.js
src/utilities/astFromValue.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js
src/utilities/findBreakingChanges.js
src/utilities/separateOperations.js
src/validation/rules/ExecutableDefinitions.js
src/validation/rules/FieldsOnCorrectType.js
src/validation/rules/NoUndefinedVariables.js
src/validation/rules/NoUnusedFragments.js
src/validation/rules/NoUnusedVariables.js
src/validation/rules/OverlappingFieldsCanBeMerged.js
src/validation/rules/ProvidedRequiredArguments.js
src/validation/rules/UniqueDirectivesPerLocation.js
src/validation/rules/ValuesOfCorrectType.js
src/validation/rules/VariablesInAllowedPosition.js

> Is there a concrete reason to make this change? .forEach is how most things are done in this library, and I'd prefer to maintain consistency.
@mjmahone `for of` is 4x faster than `forEach` + arrow function: https://jsperf.com/for-of-vs-foreach5
If we enable `loose` mode for `for of` than it will be 12x speedup.
Also, `for of` don't force us to create closures so it should lower memory usage in recursive functions.
But more importantly, the main purpose of this library is to be the reference implementation of GraphQL so code readability is very important.

Replace all 'Array.forEach' with 'for of' cycle

---

src/type/__tests__/validation-test.js
src/type/validate.js

Validate schema use new extension ast nodes

---

src/execution/__tests__/schema-test.js
src/type/__tests__/serialization-test.js
src/type/scalars.js

Idea is to make coercion code more strict and explicit.

Scalar coercion cleanup

---

src/execution/execute.js
src/subscription/subscribe.js
src/utilities/findBreakingChanges.js
src/utilities/findDeprecatedUsages.js
src/utilities/getOperationRootType.js
src/utilities/introspectionFromSchema.js
src/validation/ValidationContext.js
src/validation/validate.js

Missing `type` prefix results in unused imports in generated code, e.g.:
https://github.com/graphql/graphql-js/blob/6ca4079f8cddc97365ea9f4b002ed79ff5bc97f6/validation/validate.mjs#L12

Add missing 'type' prefixes to imports

---

src/utilities/__tests__/buildClientSchema-test.js
src/utilities/buildClientSchema.js

BREAKING: Remove support for deprecated directive locations

---

src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js

Even though recursive unions are invalid they trigger infinite recursion during buildSchema/extendSchema.
\+ small refactoring

Prevent infinite recursion on invalid unions

---

src/type/definition.js
src/type/validate.js

@mjmahone It's PR on top of #1435 so it will be merged on your feature branch.
There some technical issues with #1435 but `.getDirectives` is a major one.
This PR shows that you don't need this function and could use generic one instead.
If you need this functionality for Relay we can figure out how to make generic function public.
Motivation: `*.getDirectives` conflicts with #1343 and more global effort to expose directives through introspection: https://github.com/facebook/graphql/issues/300
Also, we shouldn't add methods that are easily implemented as an external function or we will get a bunch of "god" classes.

Replace '.getDirectives' with generic method

---

src/validation/__tests__/harness.js
src/validation/specifiedRules.js
src/validation/validate.js

Improve typings for validation functions

---

src/utilities/__tests__/buildASTSchema-test.js

Test absence of name clash between type names and directives

---

src/utilities/__tests__/extendSchema-test.js
src/utilities/extendSchema.js

Split out from #1438
Allows to inject directives and types into SDL-based schema:
```js
import { GrapQLDateTime } from 'somepackage';
let schema = new GraphQLSchema({
types: [GrapQLDateTime],
});
const ast = parse(`
type Query {
timestamp: DateTime
}
`);
schema = extendSchema(schema, ast);
```
```js
let schema = new GraphQLSchema({
directives: [
new GraphQLDirective({
name: 'onSchema',
locations: ['SCHEMA'],
}),
],
});
const ast = parse(`
schema @onSchema {
query: Foo
}
type Foo {
bar: String
}
`);
schema = extendSchema(schema, ast);
```

Allows to add schema definition missing in the original schema

---

.travis.yml
package.json

See: https://github.com/nodejs/Release#end-of-life-releases

Drop Node 9 support

---

src/type/__tests__/validation-test.js
src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js
src/validation/ValidationContext.js
src/validation/__tests__/KnownDirectives-test.js
src/validation/__tests__/UniqueDirectivesPerLocation-test.js
src/validation/__tests__/harness.js
src/validation/rules/KnownDirectives.js
src/validation/rules/LoneSchemaDefinition.js
src/validation/specifiedRules.js
src/validation/validate.js

[RFC]SDL validation

---

src/language/__tests__/parser-test.js
src/language/__tests__/printer-test.js
src/language/parser.js
src/validation/__tests__/KnownDirectives-test.js

Putting this behind an experimental flag, as @leebyron has reverted the GraphQL spec changes from https://github.com/facebook/graphql/pull/486. This can now go through normal RFC process to make it into the spec.

VariableDefinition Directives: hide behind experimental flag

---

src/language/parser.js

Reviewing #1454 I saw this low hanging fruit 🍎

Reuse 'many' for parsing document

---

src/language/__tests__/parser-test.js
src/language/__tests__/printer-test.js
src/validation/__tests__/KnownDirectives-test.js
src/validation/__tests__/harness.js

Added a parsing option to the test harness `expectPassesRule` and `expectFailsRule` functions.
Also added experimental flags on all tests with variable definition directives.

Fixup: add Experimental note to variable-directive tests

---

src/index.js
src/language/index.js
src/language/predicates.js
src/utilities/buildASTSchema.js
src/utilities/extendSchema.js
src/validation/rules/ExecutableDefinitions.js

For SDL validation rules I need to distinguish type definition node from type extension nodes.
\+ I saw same in couple other projects, e.g. `relay`:
https://github.com/facebook/relay/blob/04aac482538b83548c25e878205ecc1a581bcb25/packages/graphql-compiler/core/GraphQLSchemaUtils.js#L198-L203

Add Node Predicates

---

src/language/kinds.js
src/language/predicates.js

This was an easy mistake to make: the ordering in the `Kind` object made it seem like `Variable` belonged with `VariableDefinition`, when in fact it belongs with the values (as a variable definition defines that a value can be used).
Additionally, `ObjectField` is not itself a value: it's more of a key-value pair that itself contains a value.

Fix typo in AST predicates

---

resources/benchmark.js

In order to have a better discussion around #1463 we need to add benchmarks for `validate` and `validateSDL`. I split out refactoring part into this PR.
@mjmahone Can you please take a look?

Benchmark: replace shell scripts with JS code

---

src/__tests__/starWarsData.js
src/execution/execute.js
src/language/ast.js
src/language/source.js

No extremes only input types to help with detecting typos and similar to all other types in this lib.

Convert more object types to be exact

---

src/type/__tests__/predicate-test.js

The two new predicates isRequiredArgument and isRequiredInputField did not yet have unit tests.

Add unit tests for isRequired predicates

---

src/type/directives.js
src/utilities/__tests__/schemaPrinter-test.js

See: http://facebook.github.io/graphql/June2018/#sec--deprecated

Fix link and description of supported Markdown

---

src/type/__tests__/validation-test.js
src/type/validate.js

I reviewed all `isNonNullType` calls and it the last one that needs to be fixed to complete #1274

Allow to add optional args to fields implemented from interfaces

---

package.json

Currently `__fixtures__` include in NPM package:
https://github.com/graphql/graphql-js/tree/npm/__fixtures__
Cleanup from #1471
Don't like how it's make `package.json` less readable but it's a normal temporary solution.

Exclude __fixtures__ from dist

---

package.json

Some of use are using node 9.x

update package.json file to support node 9.x

---

src/index.js
src/validation/index.js

Intended to be used here:
https://github.com/graphql/express-graphql/blob/ab2262fa60f9f6e38a626642f08573c7698628a6/src/index.js#L84
And in other similar tools that accept validation rules.

Export "ValidationRule" type

---

src/execution/__tests__/executor-test.js
src/execution/__tests__/lists-test.js
src/execution/__tests__/mutations-test.js
src/execution/execute.js
src/language/__tests__/parser-test.js
src/language/__tests__/schema-parser-test.js
src/language/blockStringValue.js
src/language/lexer.js
src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/extendSchema-test.js
src/validation/__tests__/KnownArgumentNames-test.js
src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js

Run spell checker on all JS files

---

src/utilities/__tests__/buildASTSchema-benchmark.js
src/utilities/__tests__/buildClientSchema-benchmark.js

We measure SDL validation separately so it shouldn't affect benchmarks that measure schema build time.

Benchmark: always assume schema is valid

---

.eslintrc.yml

Idea is to first add all of them as comment and than enable on per rule
basis.

Add missing ESLint rules as comments

---

src/utilities/__tests__/coerceValue-test.js

Add some test cases to cover coercion of list values, especially nested lists where some non-list values are involved. These exercise the following special case from the [spec](http://facebook.github.io/graphql/June2018/#sec-Type-System.List):
> If the value passed as an input to a list type is not a list and not the null value, then the result of input coercion is a list of size one, where the single item value is the result of input coercion for the list’s item type on the provided value (note this may apply recursively for nested lists).
Most of these examples are copied directly from the spec. However, one of them actually coerces to a value different from what the example in the spec says, which I believe to be a mistake in the spec: https://github.com/facebook/graphql/pull/515 …

add testcases for nested list coercion

---

yarn.lock

The field was added in yarn@1.1.0.
See yarnpkg/yarn#5042 for more information.
It fully compatible with previous versions of Yarn

Add integrity hashes to yarn.lock

---

src/language/__tests__/parser-test.js
src/language/__tests__/printer-test.js
src/language/parser.js
src/validation/__tests__/KnownDirectives-test.js

[Variable Definition Directives](https://github.com/facebook/graphql/pull/486) are part of the spec. So there is no need to hide them behind a feature flag anymore.
We should bump the minor version after merging this.

[Spec] Move variable definition directive off of experimental flag

---

src/language/parser.js

based on 'expectOptionalKeyword' from #1541

Parser: Add 'skipKeyword' function

---

src/type/__tests__/serialization-test.js
src/type/scalars.js

Fixes #1518 
`class ObjectId` doesn't have `valueOf` only `toString` and `toJSON`:
https://github.com/mongodb/js-bson/blob/5acdebf7a63ed02d3bc1eb8481cdcb709fb5c886/lib/objectid.js#L213-L215
We can't use `toString` because:
```js
class A {}
const a = new A();
a.toString()
// '[object Object]'
```
So I added support for `toJSON`.

Call 'toJSON' if present for ID and String serialize

---

src/language/printer.js

I encountered a runtime type error while printing some hand-constructed `FieldDefinition` AST nodes which conform to the type spec.
Type spec - declaring it's optional:
https://github.com/graphql/graphql-js/blob/26c9874107e65f19576aae0a32638287820f68aa/src/language/ast.js#L444
Printing implementation - requiring it:
https://github.com/graphql/graphql-js/blob/787422956c9554d12d063a41fe35705335ec6290/src/language/printer.js#L139
This PR fixes this discrepancy in the implementation with a default value.
https://github.com/awfulaxolotl/graphql-js/blob/df56ba3eadbfbc282ae6262927dfaeb162662158/src/language/printer.js#L139

Fix error when printing a `FieldDefinition` AST node without `arguments` field

---

src/language/__tests__/kitchen-sink.graphql
src/language/__tests__/printer-test.js
src/language/__tests__/schema-kitchen-sink.graphql
src/language/__tests__/schema-printer-test.js
src/language/__tests__/visitor-test.js

I was wondering if there is any place beyond definitions of query variables where directives would be useful and wanted to use kitchen sink as a playground.
But currently, it lacks a lot of language features so I updated it.

Extend kitchen-sink examples

---

src/execution/__tests__/variables-test.js

Motivated by Node 11.0.0 significant change in the output format, see
https://github.com/nodejs/node/commit/f4e4ef5cad#diff-c1778ece12049a0e08c6f646c02c10d7R1632
We need to support all LTS versions, so it's better to use our own `inspect` implementation.

Migrate variable tests to internal inspect

---

package.json
src/jsutils/__tests__/inspect-test.js
src/jsutils/defineToJSON.js
src/jsutils/inspect.js
src/jsutils/nodejsCustomInspectSymbol.js
src/language/lexer.js
src/language/parser.js

Remove nodejs deprecation warnings for custom 'inspect' functions

---

src/language/__tests__/lexer-test.js
src/language/lexer.js

Fix: Handle new lines inside block string correctly

---

src/utilities/buildClientSchema.js

fixes #1609
now it lists the type which fails the validation

add type name to information

---

.travis.yml

This api key was out of date preventing us from doing automatic version deployments.
Created the api key by running "travis encrypt": https://docs.travis-ci.com/user/deployment/npm/#npm-auth-token

Update travis api_key for npm deploys

---

src/language/parser.js

Based @OlegIlyenko suggestion:
https://github.com/graphql/graphql-js/pull/1545#issuecomment-427196059

Parser: Better names for parser util functions

---

src/execution/__tests__/abstract-promise-test.js
src/execution/__tests__/executor-test.js
src/execution/execute.js

This is a proposal to handle previously serialised error objects according to [section 7.1.2 of the spec](https://facebook.github.io/graphql/draft/#sec-Errors). The result of receiving an error as object, without being an instance of the Error type, is an error message of `[object Object]`. The serialisation problem can be observed when working with [remote executable schemas in Apollo GraphQL Tools](https://github.com/apollographql/graphql-tools/blob/master/src/stitching/makeRemoteExecutableSchema.ts), when throwing an Error in a remote resolver, it bubbles up as deserialised GraphQL Error according to the spec, but is not an Error instance.
A local resolver can also accidentally throw an Object/literal, which is valid JS, ~~but~~ and an error none-the-less.
```js
try { throw { …
```

Inspect non-error types to produce helpful error messages for failing resolvers

---

src/execution/__tests__/executor-test.js
src/execution/execute.js
src/execution/index.js
src/graphql.js
src/index.js
src/type/definition.js

Having global default `typeResolver` is very useful for writing GraphQL proxies and for mocking missing types. For example it would be very easy to mock types with missing resolver like this:
```js
import {
defaultFieldResolver,
defaultTypeResolver,
} from 'graphql';
function mockFieldResolver(value, args, ctx, info) {
const default = defaultFieldResolver(value, args, ctx, info);
return default === undefined ? mockType(info.returnType) : default;
}
function mockType(type) {
//...
if (type === GraphQLString) {
return 'mock string';
}
}
function mockTypeResolver(value, ctx, info) {
const defaultType = defaultTypeResolver(value, ctx, info);
if (defaultType === undefined) {
const types = info.schema.getPossibleTypes(info.valueType);
const random = Math.floor(Math.random() * (types.length - …
```

 Allow to override default type resolver

---

yarn.lock

Last commit I made the yarn.lock out of sync with package.json for codecov. This fixes.

Fix codecov in yarn.lock

---

src/language/__tests__/printer-test.js
src/language/__tests__/schema-printer-test.js
src/language/__tests__/visitor-test.js
src/subscription/__tests__/subscribe-test.js

Should be consistent with public API, e.g. buildASTSchema

Use AST abbreviation consistently

---

src/language/lexer.js

Speedup parser (~50%) by using 'slice' and 'charCodeAt' directly

---

src/validation/rules/UniqueEnumValueNames.js
src/validation/rules/UniqueFieldDefinitionNames.js

I think the control flow is a little bit better readable and cleaner that way.

Minor code simplification in validation rules

---

src/language/lexer.js

According to the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt#Return_value), `String.prototype.charCodeAt` will only ever return a `number` or `NaN`, never `null`.
This PR updates that check in each of the 4 places that it occurs.

fix out of range return check for charCodeAt in lexer (NaN instead of null)

---

src/validation/__tests__/PossibleTypeExtensions-test.js
src/validation/rules/PossibleTypeExtensions.js

Fixed minor spelling issues in JSDoc string and test names.

Minor spelling errors in PossibleTpyeExtensions

---

src/type/__tests__/directive-test.js
src/type/__tests__/predicate-test.js

The predicates for directives were not yet tested.

Add directive predicates tests and fix test names

---

src/jsutils/__tests__/inspect-test.js
src/jsutils/inspect.js

It's a partial fix for #1753 
I basically copied how Node.js `inspect` limits output but with different limits:
* `10` array items instead of `100`
* `2` levels of recursion instead of `3`
Note: Node.js `inspect` has no limits on the max number of properties inside the object so I didn't add it either.
@mjmahone Can you please take a look?
@Cito AFAIK Python version also has this problem. So it would be great if you also review it.
Note: It doesn't fully fix #1753 since you can still produce a huge number of errors but at least those error messages become shorter in most of the cases.

Limit maximum output of 'inspect'

---

src/execution/execute.js
src/graphql.js
src/jsutils/PromiseOrValue.js
src/jsutils/promiseReduce.js
src/subscription/mapAsyncIterator.js
src/type/definition.js

Suggested by @martijnwalraven
`MaybePromise` name confuses users into thinking: `execute`/`graphql` returns either Promise or null/undefined.
Also in our codebase, we frequently use `[Mm]aybe*` to represent optional things,
e.g.:
https://github.com/graphql/graphql-js/blob/8c96dc8276f2de27b8af9ffbd71a4597d483523f/src/language/visitor.js#L353
https://github.com/graphql/graphql-js/blob/8c96dc8276f2de27b8af9ffbd71a4597d483523f/src/language/printer.js#L244

Rename 'MaybePromise' to 'PromiseOrValue'

---

src/utilities/__tests__/buildClientSchema-test.js
src/utilities/buildClientSchema.js

More details here: https://github.com/graphql/graphql-js/commit/183ff32bee4bc23eb23657f79f414c2400ecb06a#r32971387

buildClientSchema: Revert breaking change introduced in #1677

---

src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/extendSchema-test.js

Background: https://github.com/graphql/graphql-js/commit/183ff32bee4bc23eb23657f79f414c2400ecb06a#r32971387

buildSchema/extendSchema: test standard scalars

---

src/index.js
src/language/__tests__/blockString-test.js
src/language/__tests__/lexer-test.js
src/language/blockString.js
src/language/lexer.js
src/utilities/__tests__/stripIgnoredCharacters-test.js
src/utilities/index.js
src/utilities/stripIgnoredCharacters.js

Heavily based on work done by @rybon in #1628.
Fixes #1523.

Add stripIgnoredCharacters utility function

---

src/type/__tests__/predicate-test.js
src/type/directives.js
src/type/scalars.js

isSpecifiedDirective should not just check the name property, but also the type

isSpecifiedDirective should not assume Directive type

---

src/utilities/__tests__/buildASTSchema-test.js
src/utilities/__tests__/extendSchema-test.js

At first I didn't understand why Boolean was not tested,
therefore added a small comment with an explanation.
(Actually Boolean is also included via the standard directives).

Add comment to make test better understandable

---

package.json

To prevent situations similar to:
https://github.com/graphql/graphiql/pull/797

Add 'yarn check --integrity' to CI tests

---

src/language/__tests__/visitor-test.js

Enable Flow in "visitor-test.js"

---

resources/build.js

Makes "*.js" and "*.mjs" consistend with "*.js.flow" files and also
prevent diff artifacts, e.g.: https://github.com/graphql/graphql-js/commit/cf36cdbda2e9f884d35c5879e03370aab7a69c24#diff-0e28dd92524e3516b49eb5b753822f10R45

build: Add new lines to "*.js" and "*.mjs" files

---

src/utilities/findBreakingChanges.js

Note: Only functions exported by `index.js` are treated as part of
Public API https://github.com/graphql/graphql-js/blob/c0cf659d5036d2ec536a8805bc993cf85936d26d/src/utilities/index.js#L124-L130

findBreakingChanges: Remove 'export' from internal functions

---

src/utilities/__tests__/buildClientSchema-test.js
src/utilities/buildClientSchema.js

To be merged in `15.0.0`
Details: https://github.com/graphql/graphql-js/commit/183ff32bee4bc23eb23657f79f414c2400ecb06a#r32971387

buildClientSchema: include standard type only if it is used

---

src/language/visitor.js
src/type/directives.js
src/type/introspection.js
src/type/scalars.js
src/utilities/findBreakingChanges.js
src/validation/specifiedRules.js

We already using 'Object.freeze' for many constants, e.g.:
https://github.com/graphql/graphql-js/blob/8c96dc8276f2de27b8af9ffbd71a4597d483523f/src/language/directiveLocation.js#L13
https://github.com/graphql/graphql-js/blob/8c96dc8276f2de27b8af9ffbd71a4597d483523f/src/language/kinds.js#L13
https://github.com/graphql/graphql-js/blob/dec3cc5d5133118cdb19bb90a0a770c835497835/src/language/lexer.js#L102
It helps issues with Flow since without Object.freeze it assumes that constants can be mutated

Use 'Object.freeze' consistently on all exported Array/Object constants

---

src/utilities/__tests__/findBreakingChanges-test.js
src/utilities/findBreakingChanges.js

findBreakingChanges: use string representation to compare default values

---

package.json
resources/build.js
src/version.js

Happened because #1878 was authored before '14.3.1' release but merged
after it.
Also add 'npm run build' to CI to prevent simular problems in future

Manually update 'version.js'

---

docs/APIReference-Errors.md
docs/APIReference-Execution.md
docs/APIReference-ExpressGraphQL.md
docs/APIReference-GraphQL.md
docs/APIReference-Language.md
docs/APIReference-TypeSystem.md
docs/APIReference-Utilities.md
docs/APIReference-Validation.md
docs/Guides-ConstructingTypes.md
docs/Tutorial-Authentication.md
docs/Tutorial-BasicTypes.md
docs/Tutorial-ExpressGraphQL.md
docs/Tutorial-GettingStarted.md
docs/Tutorial-GraphQLClients.md
docs/Tutorial-Mutations.md
docs/Tutorial-ObjectTypes.md
docs/Tutorial-PassingArguments.md

Snapshot of https://github.com/graphql/graphql.github.io/tree/4e0f53e4a975302293240cf52ce80c9103851780/site/graphql-js

Copy 'site/graphql-js' folder from 'graphql.github.io' repo

---

src/graphql.js

Synchronise it with same argument of 'execute'
https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L102
Plus in most cases result of `JSON.parse` is passed, which is normal
object.

Accept normal object as 'variableValues' arg of 'graphql' function

---

src/subscription/subscribe.js

Duplicate #1937 but for 'subscribe' and 'createSourceEventStream'
functions

Accept normal object as 'variableValues' arg of subscribe functions

---

src/jsutils/__tests__/identityFunc-test.js
src/jsutils/identityFunc.js
src/type/__tests__/definition-test.js
src/type/definition.js
src/utilities/buildASTSchema.js
src/utilities/buildClientSchema.js

In theory should result in slightly small memory footprint and faster
execution. In practice, it simplifies testing of scalar's default behaviour.

Extract 'identityFunc' function to be used instead of 'x => x'

---

src/type/__tests__/definition-test.js
src/type/__tests__/predicate-test.js
src/type/__tests__/schema-test.js
src/type/__tests__/validation-test.js
src/type/definition.js
src/utilities/__tests__/extendSchema-test.js
src/utilities/__tests__/schemaPrinter-test.js
src/utilities/buildASTSchema.js
src/utilities/buildClientSchema.js
src/validation/__tests__/harness.js

It's logical step since it's what 'buildSchema', 'extendSchema' and'buildClientSchema' doing anyway:
https://github.com/graphql/graphql-js/blob/3d067958a3cbef00f0e5da48b9d9bc61bf9ce3fe/src/utilities/buildASTSchema.js#L403
https://github.com/graphql/graphql-js/blob/3d067958a3cbef00f0e5da48b9d9bc61bf9ce3fe/src/utilities/buildClientSchema.js#L234

GraphQLScalarType: make 'serialize' optional with 'identityFunc' as default

---

src/type/__tests__/validation-test.js
src/type/validate.js

Implements https://github.com/facebook/graphql/pull/445
Based on #1352

validateSchema: validate Input Objects self-references

---

src/error/__tests__/printError-test.js
src/error/printError.js
src/language/__tests__/lexer-test.js
src/language/__tests__/parser-test.js
src/utilities/__tests__/stripIgnoredCharacters-test.js

This is the format used by jest, flow, typescript, and many others.
As an example, this change [when used in relay](https://github.com/facebook/relay/pull/2752) changes the experience like so:

[printError] Make location formatting IDE friendly

---

src/type/__tests__/definition-test.js
src/type/definition.js
src/validation/__tests__/harness.js

Motivation:
https://github.com/graphql/graphql-js/issues/500
https://github.com/graphql/graphql-js/pull/1827#discussion_r280658590

Make 'parseLiteral' optional and use wrapped 'parseValue' by default

---

src/execution/execute.js
src/execution/values.js
src/language/lexer.js
src/type/definition.js
src/type/validate.js
src/utilities/assertValidName.js
src/utilities/buildClientSchema.js
src/utilities/findBreakingChanges.js
src/validation/rules/FragmentsOnCompositeTypes.js
src/validation/rules/PossibleFragmentSpreads.js
src/validation/rules/ProvidedRequiredArguments.js
src/validation/rules/ScalarLeafs.js
src/validation/rules/SingleFieldSubscriptions.js
src/validation/rules/UniqueDirectiveNames.js
src/validation/rules/UniqueDirectivesPerLocation.js
src/validation/rules/UniqueEnumValueNames.js
src/validation/rules/UniqueFieldDefinitionNames.js
src/validation/rules/UniqueOperationTypes.js
src/validation/rules/UniqueTypeNames.js
src/validation/rules/ValuesOfCorrectType.js
src/validation/rules/VariablesInAllowedPosition.js

Became possible after Prettier 1.18

Remove unnecessary concatenations from template strings
