package.json
It seems unnecessary dependency.
=> Remove bluebird dependency

.gitignore, src/executor/__tests__/directives.js, src/type/index.js
Adds IntelliJ Webstorm directory exception.
=> Add headers where missed and update .gitignore 

src/language/__tests__/lexer.js
Those tests are already in "lexes strings" and are not about numbers.
=> Remove redundant tests.

src/utilities/__tests__/buildASTSchema.js, src/utilities/buildASTSchema.js
Added a test that confirms issue #100 and a simple fix (one liner).
=> Fix issue with buildASTSchema when both query and mutation are passed

src/__tests__/starWarsData.js, src/__tests__/starWarsSchema.js
A back-end implementation with a real database wouldn't have direct access to the full dataset.
=> Update starWarsQueryTests to mimic real database API

src/type/__tests__/enumType.js
=> Add enum coercion test for mutation.

src/language/__tests__/lexer.js, src/language/lexer.js
When debugging https://github.com/facebook/relay/issues/121, I realized it would be useful to have the bad character listed in this case as well.
=> Add explanation of bad number character

src/language/lexer.js
I'm implementing a GraphQL compiler in another language and noticed this line can be removed while I was reading the code.
=> Minor change: remove unnecessary update of local variable

src/utilities/__tests__/buildASTSchema.js
capitalized 'ast' into 'AST' for consistency throughout
=> Correct capitalization

src/language/__tests__/schema-kitchen-sink.graphql, src/language/__tests__/schema-printer.js, src/language/parser.js
=> Fixed the issue #166 related to parsing of 'extend type' declaration

src/execution/__tests__/directives.js
=> Implement anonymous inline fragment directive tests

src/utilities/__tests__/buildASTSchema.js
Pretty simple. It happens to all of us ;P
=> Fix copy paste error in test description

src/validation/rules/ArgumentsOfCorrectType.js, src/validation/rules/DefaultValuesOfCorrectType.js, src/validation/rules/NoFragmentCycles.js, src/validation/rules/NoUnusedFragments.js, src/validation/rules/UniqueArgumentNames.js, src/validation/rules/UniqueFragmentNames.js, src/validation/rules/UniqueInputFieldNames.js, src/validation/rules/UniqueOperationNames.js, src/validation/validate.js
Fairly dramatic improvement of some validation rules by short-circuiting branches which do not need to be checked and memoizing the process of collecting fragment spreads from a given context - which is necessary by multiple rules.
=> [Validation] Performance improvements

src/validation/validate.js
This removes the mechanism that automatically expanded fragment spreads during a visit. It's no longer used after recent changes to some validator rules, but also makes over-visiting suboptimizations too easy to accidentally create.
=> [Validation] Remove visitFragmentSpreads

package.json
Addresses https://github.com/babel/babel-eslint/issues/243
=> [easy] Bump babel-eslint version

src/type/scalars.js
This commits updates the `GraphQLInt` type description to match the changes made in 06f97b6.
=> Update Int type description to match implementation

src/execution/execute.js
Reverts graphql/graphql-js#330
=> Revert "unnecessary call throwing errors"

src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js, src/validation/rules/OverlappingFieldsCanBeMerged.js
Implements https://github.com/facebook/graphql/pull/162
=> RFC: Return type overlap validation

src/type/definition.js
Needs for external flow type checking.
=> export type InputObjectConfigFieldMapThunk

src/type/__tests__/definition-test.js, src/type/__tests__/validation-test.js, src/type/definition.js
This should help with module loading order creating null types.
As this is my first PR for the project, please let me know if my tests/style are inline for `graphql-js`. More than happy to fix things up. Thanks!
=> Allow UnionTypes to accept a types thunk

src/type/__tests__/serialization-test.js, src/type/scalars.js
Addresses https://github.com/graphql/graphql-js/issues/476
=> Throw when parsing empty string to numeric scalar

src/execution/execute.js, src/graphql.js
=> Do not use .catch on Promises to supported a wider array of thenables

src/utilities/__tests__/isValidJSValue-test.js, src/utilities/isValidJSValue.js
=> Catch TypeErrors in isValidJSValue

src/utilities/buildASTSchema.js
=> Fix typo in buildASTSchema

src/execution/execute.js
=> Fix minor spelling error

src/type/__tests__/validation-test.js, src/type/definition.js
For details please see this PR: https://github.com/facebook/graphql/pull/266
=> Forbid to define duplicated member types in Union

src/type/__tests__/validation-test.js, src/type/definition.js
Suggested by @smolinari here:
https://github.com/graphql/graphql-js/pull/812#issuecomment-297898875
=> Fix grammar inside error message.

src/index.js, src/language/index.js, src/language/visitor.js
In need, this function in order to implement a custom wrapper for visitor function.
As a workaround, I copy-pasted this function into my lib which is not ideal :(
=> Export getVisitFn function

package.json
Closes #828
https://greenkeeper.io/
=> fix(package): update iterall to version 1.1.1

package.json, resources/mocha-bootload.js, src/utilities/__tests__/assertValidName-test.js, src/utilities/assertValidName.js, yarn.lock
This provides an opt-out of a spec compliance naming style for legacy schema
=> [RFC] Environment var to silence warning about invalid names.

src/subscription/__tests__/mapAsyncIterator-test.js, src/subscription/mapAsyncIterator.js
This adds proper behavior when the mapping function throws an error (As discussed in #868).
=> Handle abrupt closing in mapAsyncIterator()

src/README.md, src/subscription/README.md
I was reading through the source and noticed that there was a README of this format in every directory but this one. For consistency, I thought I'd add it here too :). While I was at it, I made the doc references link to the individual docs..
=> Add basic README for subscriptions

.eslintrc, package.json, src/utilities/__tests__/buildASTSchema-test.js, yarn.lock
=> chore(package): update eslint to version 4.1.1

src/index.js, src/utilities/index.js
Nothing to add to the title :)
@wincent Can you please merge it?
=> Add missing export for "findBreakingChanges" function

src/utilities/__tests__/findBreakingChanges-test.js, src/utilities/findBreakingChanges.js
Following the discussion in issue #968, adding a new type to a union is now considered a dangerous change.
=> Adding a type to a union is now a dangerous change.

src/utilities/buildASTSchema.js
Remove a little bit of dead code and more importantly a few unused exceptions.
@wincent Can you please review?
=> remove dead code from buildASTSchema

src/subscription/subscribe.js
We should avoid a runtime dependency on `async` support because we want the graphql package to work in as many contexts as possible with minimal configuration.
As of 0779c36f9ba621d2d4a045, even a simple invocation usage of the package like the one in the tutorial (http://graphql.org/graphql-js/) will cause an error in the absence of the regenerator runtime:
ReferenceError: regeneratorRuntime is not defined
Rather than depending on the runtime, let's just rewrite the function to not use `async`. In order to do this, we have to drop the use of the `await` keyword inside the function and make it explicitly return a promise.
Flow and tests pass.
There is a fair bit of whitespace-only change in this, so you may want to view the diff without it (with `git diff -b` or even `git diff -w` for …
=> Rewrite createSourceEventStream to avoid use of `async`

src/subscription/subscribe.js
Appy changes made by **leebyron** in 4fbfd22 on 'subscribe' function
@wincent  Can you please review it?
=> Simplify args processing in 'subscribe' function

README.md, src/utilities/__tests__/schemaPrinter-test.js
I fixed broken link to CONTRIBUTING.md on README.md.
=> fix broken link on README.md

src/language/parser.js
Just a minor change in formatting to match comments and function names to spec text
=> Update to latest SDL grammar formatting

src/language/printer.js
Makes code more readable, at least for me 😄
=> Printer: create special function to add description

src/jsutils/dedent.js
The code is about removing i**n**dentation
=> Fix typos in dedent code

.travis.yml
v9 was added in the fall. v4 sticking around in LTS until spring
=> Add node v9 to test matrix

src/utilities/__tests__/schemaPrinter-test.js
Made the exact same changes as in #1211
=> Fix Travis build on #1212

.travis.yml, package.json
* move script description to package
* colocate package scripts
* skip deploy job for PRs
=> Improve travis runs

src/utilities/__tests__/buildASTSchema-test.js
Same test has been added twice in buildASTSchema-test
=> Remove duplicate test

src/utilities/buildASTSchema.js
Fixes breaking change from #1249
=> buildSchema: Make options optional

src/execution/__tests__/variables-test.js
> want to factor this into two PRs? The improvements to test files should be mergeable as is
@leebyron Done. I will rebase #1267 after this PR will be merged.
=> Cleanup variables test (extracted from #1267)

.flowconfig, package.json, src/error/locatedError.js, src/subscription/mapAsyncIterator.js, yarn.lock
Summary:
This version of Flow erorrs on unknown properties.
I extended the error suppression comment to support versioned suppressions,
since this is only an error after 0.68.
Test Plan: flow
Reviewers: leeb
Subscribers:
Tasks:
Tags:
=> Update to Flow v0.68

package.json, yarn.lock
Ran `yarn prettier` and this resulted in no changes.
=> Upgrade to prettier@1.11.1

.flowconfig, package.json, yarn.lock
=> Upgrade to flow-bin@0.69.0

src/language/__tests__/lexer-test.js, src/utilities/__tests__/buildClientSchema-test.js
`containSubset` plugin used in many places where native `chai` checks would be enough.
=> Replace containSubset with native chai checks

src/jsutils/instanceOf.js
=> instanceOf: Check that one of the names in non-empty string

src/jsutils/__tests__/instanceOf-test.js
I wrote this test for #1357 but forgot to do `git add` 😞
=> Add simple test for `instanceOf`.

src/__tests__/starWarsIntrospection-test.js, src/__tests__/starWarsQuery-test.js, src/__tests__/starWarsSchema.js, src/__tests__/starWarsValidation-test.js
=> fix imports

package.json
Forgot to `git push --tags` to get Travis CI to publish this to github. So bumping the version and adding tags.
=> Bump RC version to publish on npm

src/utilities/__tests__/coerceValue-test.js, src/utilities/__tests__/extendSchema-test.js
An actual test was declared as a group
=> Fix extend schema test

src/graphql.js
Results in eslint error and blocks development.
=> Fix trailing space from #1400

src/utilities/__tests__/introspectionFromSchema-benchmark.js
Skip schema validation during introspection benchmark.
=> Benchmark: skip schema validation

src/validation/validate.js
After d00fbe9 `visitUsingRules` can't be used outside of `validate.js` so it makes sense to inline it.
=> Inline intermediate 'visitUsingRules' function

src/utilities/__tests__/buildASTSchema-test.js
Artifact from: https://github.com/graphql/graphql-js/blob/176076c8a674e7e718998a6519b327098ff6d457/src/utilities/__tests__/buildASTSchema.js#L23
=> Remove unused arguments to cycleOuput

src/type/directives.js, src/type/schema.js
=> Convert 'GraphQL*Config' to exact types (part 2)

resources/watch.js
Fixes bug I introduced in #1499
I forgot to change imports and more importantly to test `watch` without `babel-node` 😞
=> Fix imports in 'watch' script

src/type/introspection.js, src/utilities/__tests__/findBreakingChanges-test.js, src/validation/__tests__/FieldsOnCorrectType-test.js, src/validation/__tests__/KnownDirectives-test.js, src/validation/rules/FieldsOnCorrectType.js
mostly leftovers from Prettier conversion
=> Fix formatting

src/type/__tests__/definition-test.js, src/type/definition.js
=> Correct error message about resolve specified on input fields

src/utilities/__tests__/buildClientSchema-test.js, src/utilities/buildClientSchema.js
Motivation: https://github.com/dotansimha/graphql-code-generator/issues/556#issue-356000347
=> buildClientSchema: Throws when missing directive locations

.eslintrc.yml
Context:
https://github.com/graphql/graphql-js/pull/1503#issuecomment-419167396
> I think the re-order should be a separate PR: that way, it's clear in this PR which rules we want to add,
=> Rearrange ESLint rules, extracted from #1503

resources/copy-package-json.js
Prevents issues similar to #1375
See: https://docs.npmjs.com/files/package.json#publishconfig
=> Automatically setup npm publish tag

.eslintrc.yml
Based on this list: https://github.com/eslint/eslint/blob/caeb223c4f7b0b6fe35e5348ae0df4c6446b5bed/conf/eslint-recommended.js
=> ESLint: enable recommended rules

.eslintrc.yml
Configuration is fully based on our existing practices.
=> Configure majority of undecided relues for 'eslint-plugin-flowtype'

src/language/lexer.js
=> Lexer: Fix comments to reflex current behaviour

src/type/__tests__/definition-test.js
Reported by @zonr here:
https://github.com/graphql/graphql-js/commit/461392db1eb05b21dc8b048ac352ea2fb37bdbbd#r31021840
=> Fix test description

README.md
=> fix(README): Use https in graphql.org url

src/validation/rules/PossibleTypeExtensions.js
=> Fix error message typo for extend types

package.json, resources/benchmark.js, yarn.lock
Also fixes https://github.com/Fishrock123/beautify-benchmark/issues/3
=> Inline 'beautify-benchmark' + heavy refactoring

src/execution/__tests__/union-interface-test.js
Reported by @zonr here: https://github.com/graphql/graphql-js/commit/323f2d2d2763b2f0502cc55beaa6ccaf89d8f423#r32669772
=> Fix test case description

src/validation/__tests__/UniqueInputFieldNames-test.js, src/validation/rules/UniqueInputFieldNames.js
When checking input fields, also descend into nested fields.
=> Duplicate fields in deep inputs not validated properly (#1791)

src/execution/__tests__/abstract-test.js, src/execution/execute.js, src/language/__tests__/lexer-test.js, src/language/lexer.js, src/type/__tests__/introspection-test.js, src/type/definition.js, src/type/directives.js, src/type/introspection.js, src/type/scalars.js, src/utilities/buildClientSchema.js
Makes editing strings easier and clean resulting diffs
Plus all modern editors support wrapping of long lines.
=> Manually concat all static strings

src/utilities/__tests__/buildClientSchema-test.js
Motivation: Improves code coverage
=> tests: replace `invariant` with `assertEnumType`

src/error/GraphQLError.js, src/execution/execute.js, src/jsutils/__tests__/isObjectLike-test.js, src/jsutils/isObjectLike.js, src/language/__tests__/toJSONDeep.js, src/type/definition.js, src/type/directives.js, src/type/scalars.js, src/type/schema.js, src/utilities/astFromValue.js, src/utilities/coerceValue.js
Inspired by https://lodash.com/docs/4.17.11#isObjectLike
=> Extract 'isObjectLike' utility function

.travis.yml
Since NPM settings require 2FA to publish this package
=> Travis: Disable automatic publishing on NPM

src/validation/__tests__/validateInvalidGQL-benchmark.js
=> Add benchmark for validating invalid query

src/type/definition.js
Fixes #2114
Partly reverts #2089
=> Copy non-standard properites from field's config

src/type/definition.js
=> Removes non-standard properties from field objects

src/type/__tests__/definition-test.js, src/type/definition.js, src/utilities/__tests__/valueFromAST-test.js
Motivation: https://github.com/graphql/graphql-js/issues/1383#issuecomment-417147188
Fixes #1367
=> GraphQLEnumType: Drop support for 'undefined' custom value

src/utilities/astFromValue.js
Minor fix to improve comment/documentation for `astFromValue` function
=> Improve documentation for astFromValue

src/execution/__tests__/variables-test.js, src/execution/values.js
Fixes #2190
Port of #2191 from `14.x.x` branch
=> Fixes variable values of non-null type with default value

src/validation/validate.js
=> Remove unussed 'ABORT_VALIDATION' constant

src/validation/validate.js
=> Remove unused 'ABORT_VALIDATION' constant

src/utilities/__tests__/schemaPrinter-test.js, src/utilities/schemaPrinter.js
=> printSchema: don't break description lines

src/type/__tests__/serialization-test.js
=> serialization-test: Don't use 'delete' on test objects

README.md
I was reading the documentation and noticed this spelling error.
=> chore: Spelling

resources/benchmark.js
Caching build resulted in buggy behaviour when updating node version
=> benchmark: make clean build every time

.babelrc.js, src/execution/__tests__/schema-test.js
=> tests: Transpile tests less aggressively

src/utilities/__tests__/findDeprecatedUsages-test.js, src/utilities/findDeprecatedUsages.js
=> Simplify findDeprecatedUsages since "deprecationReason" is always present

src/index.d.ts, src/index.js
=> Add missing export for 'ExecutableDefinitionsRule'

src/utilities/lexicographicSortSchema.d.ts, src/utilities/lexicographicSortSchema.js
Replicates https://github.com/graphql-python/graphql-core-next/commit/c61c65d264044504accaa6d76b21479a2af68205
=> Improve description for lexicographicSortSchema

README.md
=> docs: Add note about 'NODE_ENV=production'

src/language/__tests__/visitor-test.js
test name has been duplicated and not adapted
=> visitor-test: use proper test name

src/validation/__tests__/KnownArgumentNamesRule-test.js, src/validation/__tests__/ProvidedRequiredArgumentsRule-test.js, src/validation/rules/KnownArgumentNamesRule.d.ts, src/validation/rules/KnownArgumentNamesRule.js, src/validation/rules/ProvidedRequiredArgumentsRule.d.ts, src/validation/rules/ProvidedRequiredArgumentsRule.js, src/validation/specifiedRules.js
Not a breaking change since these rules are internal.
=> validation: Fix names of internal SDL rules

src/jsutils/__tests__/suggestionList-test.js, src/jsutils/suggestionList.js, src/type/__tests__/enumType-test.js, src/validation/__tests__/ValuesOfCorrectTypeRule-test.js
It becomes almost 2.5 times faster:
=> suggestionList: Speed up 

src/type/definition.d.ts, src/type/definition.js
partial revert of https://github.com/graphql/graphql-js/commit/23b427cacc3a6d16eb985ea3e5ab9b47d7a295d0#diff-15f6b6c92ff954f80995d31726f89851L477
Reported by @yaacovCR here:
https://github.com/yaacovCR/graphql-tools-fork/issues/40#issuecomment-586671219
=> getNullableType: fix TS signature

package.json, yarn.lock
=> package.json: change how 'eslint-plugin-graphql-internal' installed

.babelrc.json, src/__testUtils__/__tests__/genFuzzStrings-test.js, src/__testUtils__/__tests__/inspectStr-test.js, src/__testUtils__/genFuzzStrings.js, src/__testUtils__/inspectStr.js, src/language/__tests__/blockString-test.js, src/utilities/__tests__/stripIgnoredCharacters-test.js
=> blockString-test: add fuzzing test for 'printBlockString'

src/execution/execute.d.ts, src/jsutils/Path.d.ts, src/language/ast.d.ts, src/tslint.json, src/type/definition.d.ts, src/type/schema.d.ts, src/validation/ValidationContext.d.ts
Motivation: https://www.typescriptlang.org/docs/handbook/advanced-types.html#interfaces-vs-type-aliases
=> ts: switch more types to interfaces

src/execution/execute.d.ts
TS specific change.
Motivation https://github.com/graphql/graphql-js/pull/2490#issuecomment-639154229
=> TS: add TData template argument to ExecutionResult type

src/jsutils/instanceOf.js
This reverts commit 916e69709f40808469dc1adfa47a989d3f229745.
=> Revert "instanceOf: support Deno (#2642)"

src/execution/__tests__/abstract-test.js, src/execution/__tests__/directives-test.js, src/execution/__tests__/executor-test.js, src/execution/__tests__/mutations-test.js, src/execution/__tests__/nonnull-test.js, src/execution/__tests__/resolve-test.js, src/execution/__tests__/schema-test.js, src/execution/__tests__/sync-test.js, src/execution/__tests__/union-interface-test.js, src/execution/__tests__/variables-test.js, src/execution/execute.d.ts, src/execution/execute.js, src/execution/index.d.ts, src/execution/index.js, src/index.d.ts, src/index.js, src/utilities/__tests__/introspectionFromSchema-benchmark.js, src/utilities/introspectionFromSchema.js
=> Added 'executeSync': promise free version of `execute`.

src/type/definition.d.ts, src/type/definition.js, src/type/introspection.js, src/utilities/printSchema.js
=> Deprecate 'isDeprecated'

src/execution/__tests__/lists-test.js
=> list-test: improve test readability (part 3)

src/language/__tests__/blockString-test.js
=> blockString-test: add test for not escaping characters

src/__tests__/starWarsSchema.js, src/execution/__tests__/abstract-promise-test.js, src/execution/__tests__/abstract-test.js, src/execution/__tests__/executor-test.js, src/execution/__tests__/nonnull-test.js, src/execution/__tests__/schema-test.js, src/execution/__tests__/union-interface-test.js, src/execution/__tests__/variables-test.js, src/subscription/__tests__/subscribe-test.js, src/type/__tests__/definition-test.js, src/type/__tests__/predicate-test.js, src/type/__tests__/schema-test.js, src/type/__tests__/validation-test.js, src/type/definition.js, src/type/directives.js, src/type/introspection.js, src/utilities/__tests__/astFromValue-test.js, src/utilities/__tests__/coerceInputValue-test.js, src/utilities/__tests__/printSchema-test.js, src/utilities/__tests__/typeComparators-test.js, src/utilities/__tests__/valueFromAST-test.js, src/utilities/buildClientSchema.js, src/utilities/extendSchema.js, src/utilities/lexicographicSortSchema.js, src/utilities/typeFromAST.js
Done in preparation for switching GraphQLList/GraphQLNonNull to proper classes in upcoming v16.0.0
=> Switch all code to create GraphQLList/GraphQLNonNull instances with new

src/language/printer.js
Also restore coverage back to 100%
=> parser: simplify a few utility functions

src/__testUtils__/__tests__/resolveOnNextTick-test.js, src/__testUtils__/resolveOnNextTick.js, src/execution/__tests__/executor-test.js, src/execution/__tests__/mutations-test.js, src/subscription/__tests__/subscribe-test.js
instead of Node.js specific methods
=> Add 'resolveOnNextTick' to use in tests

src/__tests__/starWarsSchema.js, src/execution/__tests__/abstract-test.js, src/execution/__tests__/union-interface-test.js, src/execution/execute.js, src/type/definition.js
=> resolveType: add workaround for transformed schemas

.babelrc-deno.json, .babelrc-npm.json, .babelrc.json, .browserslistrc, .eslintrc.yml, package.json, resources/build-npm.js, tsconfig.json
Older browsers can still be supported through transpilation and
polyfills
=> Drop support for older browsers

package-lock.json
=> build: commit package-lock for drop support node10

src/type/definition.js
It became out of date after #2905
=> definition: Remove deprecation comment

.eslintrc.yml
As suggested in https://github.com/graphql/graphql-js/pull/3146#discussion_r648311878
=> fix: broken link to prettier rules

src/type/definition.ts, src/type/scalars.ts
=> Add type params to GraphQLScalar

src/language/__tests__/lexer-test.ts, src/language/lexer.ts
=> Lexer: fix line & column for multiline BLOCK_STRING tokens

src/execution/__tests__/directives-test.ts
=> tests(execution): add missing new lines

.eslintrc.yml
Motivation: https://github.com/graphql/graphql-js/pull/3537#issuecomment-1104502226
=> ESLint: add 'shared-node-browser' environment

.eslintrc.yml
=> Remove superficial ESLint config

.github/workflows/ci.yml, .github/workflows/cmd-publish-pr-on-npm.yml, .github/workflows/cmd-run-benchmark.yml, .github/workflows/deploy-artifact-as-branch.yml, .github/workflows/github-actions-bot.yml, .github/workflows/mutation-testing.yml, .github/workflows/pull_request.yml, .github/workflows/pull_request_opened.yml
Nothing major, GH just did a version bump to update their actions to Node16.
=> Update GitHub actions dependencies

resources/gen-changelog.ts, tsconfig.json
=> gen-changelog: Use `fetch` instead of `http.request`

resources/build-deno.ts, resources/build-npm.ts, resources/diff-npm-package.ts, resources/utils.ts
Context: less repetition and better code reuse
=> resources: Move `mkdirSync` into `writeGeneratedFile`

.github/workflows/pull_request.yml
Motivation: increase security.
Discovered while looking into #3162
=> ci: add dependency review workflow

package.json, resources/benchmark.ts, resources/build-docusaurus.ts, resources/diff-npm-package.ts, resources/integration-test.ts, resources/utils.ts
Motivation: Extract common functionality in utility function
=> resources: add utility function to create tmp dir

src/jsutils/promiseForObject.ts
Motivation: TS LSP shows warning about it so I used LSP action to fix it.
=> promiseForObject: convert to be async function

src/execution/execute.ts
which can be used when completing an iterable or an asyncIterator, as suggested by the TODO.
extracted from #3728
=> refactor: introduce completeListItemValue

src/execution/__tests__/executor-test.js, src/execution/execute.js
Fixes #3528 in the `15.x.x` branch
=> Fix crash in node when mixing sync/async resolvers (backport of #3706)

src/execution/execute.ts
....it will never return a promise.
extracted from #3796
=> polish: narrow mapSourceToResponse return type

resources/gen-changelog.ts
Context: I made this mistake in #3872, fixing in this PR
=> gen-changelog: Fix error introduced in #3872

src/execution/IncrementalPublisher.ts
extracted from #3960
thanks @benjie for pointing this out
=> fix(types): path is required within incremental results

src/jsutils/instanceOf.ts
Port of #3923 from v16 to main (v17)
=> instanceOf: workaround bundler issue with process.env

src/execution/execute.ts
-- improve variable naming:
`parentDeferUsage` => `parentTarget`
`deferUsage` => `newDeferUsage`
-- add comments
=> polish: addDeferredFragments

README.md
Adds instructions for Bun package manager to the readme
=> docs: add installation instructions for bun

integrationTests/ts/test.js, src/index.d.ts, src/index.js, src/validation/__tests__/MaxIntrospectionDepthRule-test.js, src/validation/index.d.ts, src/validation/index.js, src/validation/rules/MaxIntrospectionDepthRule.d.ts, src/validation/rules/MaxIntrospectionDepthRule.js, src/validation/specifiedRules.d.ts, src/validation/specifiedRules.js
For details, see: https://github.com/graphql/graphql-js/pull/4118
=> backport[v15]: Introduce "recommended" validation rules

package.json, resources/checkgit.sh
=> port[v17]: Fix publish scripts

package.json, resources/checkgit.sh
=> backport(v15): fix publish scripts

src/execution/buildFieldPlan.ts
main improvement is to remove additional intermediate variables, i.e. `map`, `inOriginalResult`.
=> incremental: optimize build field plan

src/language/__tests__/lexer-test.ts, src/language/lexer.ts
extracted from @leebyron 's excellent #3807
will reduce that diff
=> improve errors around around dots

src/language/ast.ts
re: fragment variables/arguments
=> update comments regarding fragment arguments and variables

src/type/definition.ts
=> chore(deps): remove prettier-ignore

.husky/pre-commit, package.json
https://github.com/graphql/graphql-js/pull/4217#discussion_r1790144268
=> move to separate script

src/utilities/__tests__/replaceVariables-test.ts, src/utilities/replaceVariables.ts
=> fix(replaceVariables): handle missing individual variable source

src/error/formatError.js
=> Re-export GraphQLFormattedError as type

website/vercel.json
This is popular on google as an index page
=> Add redirect for /api

src/utilities/__tests__/buildASTSchema-test.ts, src/utilities/__tests__/extendSchema-test.ts, src/utilities/__tests__/separateOperations-test.ts
There were a few tests that broke due to changes to print params
=> fixed tests that were using print

website/pages/docs/getting-started.mdx
* removes extra parenthesis from getting started code snippet
=> typofix: removes extra parenthesis from getting started code snippet

website/pages/docs/object-types.mdx, website/pages/docs/passing-arguments.mdx
Fixes https://github.com/graphql/graphql-js/issues/4346
=> Correct some syntax

.github/workflows/ci.yml, .github/workflows/cmd-publish-pr-on-npm.yml, .github/workflows/cmd-run-benchmark.yml, .github/workflows/pull_request.yml
Attempting to fix all our failing actions
=> Chore: bump setup-node
